-- Fridge Mate 레시피 시드 데이터 (100개 양식 레시피)
-- Supabase SQL Editor에서 실행하세요
-- tags: spicy, mild, soupy, stir_fry, grilled, steamed, raw, meat, seafood, veggie, heavy, light, quick, noodle, rice, side_dish, bread, pasta, salad, baked

-- 기존 양식 시드 데이터 중복 방지
DELETE FROM public.recipes WHERE source = 'seed' AND external_id LIKE 'western-%';

INSERT INTO public.recipes (external_id, source, title, description, cooking_time, difficulty, servings, ingredients, instructions, tags) VALUES

-- === 파스타 (Pasta) ===
('western-001', 'seed',
 '{"ko":"까르보나라","en":"Carbonara","ja":"カルボナーラ","zh":"培根蛋面"}',
 '{"ko":"크림과 베이컨으로 만든 이탈리아 파스타","en":"Italian pasta with cream and bacon"}',
 25, 'medium', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"베이컨","quantity":"100g"},{"name":"달걀노른자","quantity":"2개"},{"name":"파마산치즈","quantity":"50g"},{"name":"생크림","quantity":"100ml"},{"name":"마늘","quantity":"2쪽"}]',
 '{"ko":["스파게티면을 삶는다","베이컨과 마늘을 볶는다","달걀노른자, 생크림, 치즈를 섞는다","삶은 면을 베이컨에 넣는다","불을 끄고 크림 소스를 넣어 섞는다","후추를 뿌린다"]}',
 ARRAY['pasta','heavy','meat']),

('western-002', 'seed',
 '{"ko":"토마토 파스타","en":"Tomato Pasta","ja":"トマトパスタ","zh":"番茄意面"}',
 '{"ko":"신선한 토마토로 만든 건강한 파스타","en":"Healthy pasta with fresh tomatoes"}',
 30, 'easy', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"토마토","quantity":"4개"},{"name":"양파","quantity":"1개"},{"name":"마늘","quantity":"3쪽"},{"name":"올리브오일","quantity":"3큰술"},{"name":"바질","quantity":"5장"}]',
 '{"ko":["토마토를 데쳐서 껍질을 벗기고 다진다","양파와 마늘을 올리브오일에 볶는다","토마토를 넣고 끓인다","삶은 면을 넣고 섞는다","바질을 올린다"]}',
 ARRAY['pasta','veggie','light']),

('western-003', 'seed',
 '{"ko":"알리오 올리오","en":"Aglio e Olio","ja":"ペペロンチーノ","zh":"蒜香辣椒意面"}',
 '{"ko":"마늘과 올리브오일로 만든 심플한 파스타","en":"Simple pasta with garlic and olive oil"}',
 15, 'easy', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"마늘","quantity":"6쪽"},{"name":"올리브오일","quantity":"5큰술"},{"name":"페페론치노","quantity":"2개"},{"name":"파슬리","quantity":"약간"}]',
 '{"ko":["스파게티면을 삶는다","마늘을 얇게 썬다","올리브오일에 마늘과 페페론치노를 볶는다","삶은 면과 면수를 넣어 섞는다","파슬리를 뿌린다"]}',
 ARRAY['pasta','veggie','light','quick']),

('western-004', 'seed',
 '{"ko":"봉골레 파스타","en":"Vongole Pasta","ja":"ボンゴレパスタ","zh":"蛤蜊意面"}',
 '{"ko":"조개와 화이트와인으로 만든 파스타","en":"Pasta with clams and white wine"}',
 25, 'medium', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"바지락","quantity":"300g"},{"name":"마늘","quantity":"4쪽"},{"name":"화이트와인","quantity":"50ml"},{"name":"올리브오일","quantity":"3큰술"},{"name":"페페론치노","quantity":"1개"}]',
 '{"ko":["바지락을 해감한다","마늘을 올리브오일에 볶는다","바지락과 화이트와인을 넣는다","조개가 입을 열면 삶은 면을 넣는다","면수를 넣어 섞는다"]}',
 ARRAY['pasta','seafood','light']),

('western-005', 'seed',
 '{"ko":"페스토 파스타","en":"Pesto Pasta","ja":"ジェノベーゼパスタ","zh":"香蒜酱意面"}',
 '{"ko":"바질 페스토로 만든 향긋한 파스타","en":"Aromatic pasta with basil pesto"}',
 20, 'easy', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"바질","quantity":"50g"},{"name":"잣","quantity":"30g"},{"name":"파마산치즈","quantity":"40g"},{"name":"올리브오일","quantity":"100ml"},{"name":"마늘","quantity":"2쪽"}]',
 '{"ko":["바질, 잣, 마늘, 치즈를 믹서에 간다","올리브오일을 넣어 페스토를 만든다","스파게티면을 삶는다","삶은 면에 페스토를 넣어 섞는다","치즈를 뿌린다"]}',
 ARRAY['pasta','veggie','light']),

('western-006', 'seed',
 '{"ko":"크림 파스타","en":"Cream Pasta","ja":"クリームパスタ","zh":"奶油意面"}',
 '{"ko":"버섯과 생크림으로 만든 부드러운 파스타","en":"Smooth pasta with mushrooms and cream"}',
 25, 'easy', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"양송이버섯","quantity":"150g"},{"name":"생크림","quantity":"200ml"},{"name":"양파","quantity":"1/2개"},{"name":"파마산치즈","quantity":"30g"},{"name":"버터","quantity":"20g"}]',
 '{"ko":["양파와 버섯을 버터에 볶는다","생크림을 넣고 끓인다","삶은 면을 넣는다","치즈를 넣어 섞는다","후추를 뿌린다"]}',
 ARRAY['pasta','veggie','heavy']),

('western-007', 'seed',
 '{"ko":"로제 파스타","en":"Rose Pasta","ja":"ローゼパスタ","zh":"玫瑰酱意面"}',
 '{"ko":"토마토와 크림을 섞은 로제 소스 파스타","en":"Pasta with rose sauce mixing tomato and cream"}',
 25, 'easy', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"토마토소스","quantity":"150ml"},{"name":"생크림","quantity":"100ml"},{"name":"베이컨","quantity":"80g"},{"name":"양파","quantity":"1/2개"},{"name":"마늘","quantity":"2쪽"}]',
 '{"ko":["베이컨, 양파, 마늘을 볶는다","토마토소스를 넣고 끓인다","생크림을 넣어 로제 소스를 만든다","삶은 면을 넣어 섞는다","파슬리를 뿌린다"]}',
 ARRAY['pasta','meat','heavy']),

('western-008', 'seed',
 '{"ko":"알프레도 파스타","en":"Alfredo Pasta","ja":"アルフレッドパスタ","zh":"阿尔弗雷多意面"}',
 '{"ko":"버터와 치즈로 만든 진한 크림 파스타","en":"Rich cream pasta with butter and cheese"}',
 20, 'easy', 2,
 '[{"name":"페투치네면","quantity":"200g"},{"name":"버터","quantity":"50g"},{"name":"생크림","quantity":"150ml"},{"name":"파마산치즈","quantity":"60g"},{"name":"마늘","quantity":"2쪽"}]',
 '{"ko":["페투치네면을 삶는다","버터에 마늘을 볶는다","생크림을 넣고 끓인다","치즈를 넣어 녹인다","삶은 면을 넣어 섞는다"]}',
 ARRAY['pasta','veggie','heavy']),

('western-009', 'seed',
 '{"ko":"아라비아타","en":"Arrabbiata","ja":"アラビアータ","zh":"辣味番茄意面"}',
 '{"ko":"매콤한 토마토 소스 파스타","en":"Spicy tomato sauce pasta"}',
 25, 'easy', 2,
 '[{"name":"펜네면","quantity":"200g"},{"name":"토마토","quantity":"4개"},{"name":"페페론치노","quantity":"3개"},{"name":"마늘","quantity":"4쪽"},{"name":"올리브오일","quantity":"3큰술"},{"name":"바질","quantity":"약간"}]',
 '{"ko":["마늘과 페페론치노를 올리브오일에 볶는다","토마토를 넣고 졸인다","삶은 펜네를 넣는다","바질을 올린다","파마산치즈를 뿌린다"]}',
 ARRAY['pasta','spicy','veggie']),

('western-010', 'seed',
 '{"ko":"해산물 파스타","en":"Seafood Pasta","ja":"シーフードパスタ","zh":"海鲜意面"}',
 '{"ko":"새우와 오징어로 만든 해산물 파스타","en":"Pasta with shrimp and squid"}',
 30, 'medium', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"새우","quantity":"150g"},{"name":"오징어","quantity":"100g"},{"name":"토마토소스","quantity":"200ml"},{"name":"마늘","quantity":"3쪽"},{"name":"화이트와인","quantity":"50ml"}]',
 '{"ko":["해산물을 손질한다","마늘을 볶고 해산물을 넣는다","화이트와인을 넣는다","토마토소스를 넣고 끓인다","삶은 면을 넣어 섞는다"]}',
 ARRAY['pasta','seafood','heavy']),

-- === 피자 (Pizza) ===
('western-011', 'seed',
 '{"ko":"마르게리타 피자","en":"Margherita Pizza","ja":"マルゲリータピザ","zh":"玛格丽特披萨"}',
 '{"ko":"토마토, 모짜렐라, 바질로 만든 클래식 피자","en":"Classic pizza with tomato, mozzarella and basil"}',
 45, 'medium', 2,
 '[{"name":"피자도우","quantity":"1장"},{"name":"토마토소스","quantity":"100ml"},{"name":"모짜렐라치즈","quantity":"150g"},{"name":"바질","quantity":"10장"},{"name":"올리브오일","quantity":"2큰술"}]',
 '{"ko":["도우에 토마토소스를 바른다","모짜렐라치즈를 올린다","200도 오븐에서 15분 굽는다","바질을 올린다","올리브오일을 뿌린다"]}',
 ARRAY['baked','veggie','heavy']),

('western-012', 'seed',
 '{"ko":"페퍼로니 피자","en":"Pepperoni Pizza","ja":"ペパロニピザ","zh":"意式香肠披萨"}',
 '{"ko":"페퍼로니 소시지가 듬뿍 올라간 피자","en":"Pizza loaded with pepperoni sausage"}',
 40, 'medium', 2,
 '[{"name":"피자도우","quantity":"1장"},{"name":"토마토소스","quantity":"100ml"},{"name":"모짜렐라치즈","quantity":"150g"},{"name":"페퍼로니","quantity":"100g"},{"name":"오레가노","quantity":"약간"}]',
 '{"ko":["도우에 토마토소스를 바른다","치즈를 올린다","페퍼로니를 올린다","200도 오븐에서 15분 굽는다","오레가노를 뿌린다"]}',
 ARRAY['baked','meat','heavy']),

('western-013', 'seed',
 '{"ko":"하와이안 피자","en":"Hawaiian Pizza","ja":"ハワイアンピザ","zh":"夏威夷披萨"}',
 '{"ko":"햄과 파인애플의 달콤짭짤한 피자","en":"Sweet and savory pizza with ham and pineapple"}',
 40, 'medium', 2,
 '[{"name":"피자도우","quantity":"1장"},{"name":"토마토소스","quantity":"100ml"},{"name":"모짜렐라치즈","quantity":"150g"},{"name":"햄","quantity":"100g"},{"name":"파인애플","quantity":"100g"}]',
 '{"ko":["도우에 토마토소스를 바른다","치즈를 올린다","햄과 파인애플을 올린다","200도 오븐에서 15분 굽는다","파슬리를 뿌린다"]}',
 ARRAY['baked','meat','heavy']),

('western-014', 'seed',
 '{"ko":"콤비네이션 피자","en":"Combination Pizza","ja":"コンビネーションピザ","zh":"综合披萨"}',
 '{"ko":"다양한 토핑이 들어간 풍성한 피자","en":"Abundant pizza with various toppings"}',
 45, 'medium', 3,
 '[{"name":"피자도우","quantity":"1장"},{"name":"토마토소스","quantity":"100ml"},{"name":"모짜렐라치즈","quantity":"150g"},{"name":"소시지","quantity":"50g"},{"name":"베이컨","quantity":"50g"},{"name":"양파","quantity":"1/4개"},{"name":"피망","quantity":"1/2개"},{"name":"올리브","quantity":"10개"}]',
 '{"ko":["도우에 토마토소스를 바른다","치즈를 올린다","모든 토핑을 올린다","200도 오븐에서 15분 굽는다","오레가노를 뿌린다"]}',
 ARRAY['baked','meat','heavy']),

('western-015', 'seed',
 '{"ko":"쉬림프 피자","en":"Shrimp Pizza","ja":"シュリンプピザ","zh":"虾仁披萨"}',
 '{"ko":"새우가 듬뿍 올라간 해산물 피자","en":"Seafood pizza loaded with shrimp"}',
 45, 'medium', 2,
 '[{"name":"피자도우","quantity":"1장"},{"name":"토마토소스","quantity":"100ml"},{"name":"모짜렐라치즈","quantity":"150g"},{"name":"새우","quantity":"150g"},{"name":"마늘","quantity":"3쪽"},{"name":"파슬리","quantity":"약간"}]',
 '{"ko":["새우를 마늘과 볶는다","도우에 토마토소스를 바른다","치즈와 새우를 올린다","200도 오븐에서 15분 굽는다","파슬리를 뿌린다"]}',
 ARRAY['baked','seafood','heavy']),

-- === 스테이크 & 그릴 (Steak & Grilled) ===
('western-016', 'seed',
 '{"ko":"티본 스테이크","en":"T-Bone Steak","ja":"Tボーンステーキ","zh":"丁骨牛排"}',
 '{"ko":"완벽하게 구운 티본 스테이크","en":"Perfectly grilled T-bone steak"}',
 25, 'medium', 2,
 '[{"name":"티본 스테이크","quantity":"500g"},{"name":"소금","quantity":"적당량"},{"name":"후추","quantity":"적당량"},{"name":"올리브오일","quantity":"2큰술"},{"name":"마늘","quantity":"4쪽"},{"name":"로즈마리","quantity":"2줄기"}]',
 '{"ko":["스테이크에 소금, 후추를 뿌린다","팬을 뜨겁게 달군다","올리브오일을 두르고 스테이크를 굽는다","마늘과 로즈마리를 넣는다","취향에 맞게 굽고 5분 휴지시킨다"]}',
 ARRAY['grilled','meat','heavy']),

('western-017', 'seed',
 '{"ko":"립아이 스테이크","en":"Ribeye Steak","ja":"リブアイステーキ","zh":"肋眼牛排"}',
 '{"ko":"마블링이 풍부한 립아이 스테이크","en":"Ribeye steak with rich marbling"}',
 20, 'medium', 1,
 '[{"name":"립아이 스테이크","quantity":"300g"},{"name":"소금","quantity":"적당량"},{"name":"후추","quantity":"적당량"},{"name":"버터","quantity":"20g"},{"name":"타임","quantity":"2줄기"}]',
 '{"ko":["스테이크를 실온에 둔다","소금, 후추로 간을 한다","팬을 뜨겁게 달구고 스테이크를 굽는다","버터와 타임을 넣는다","5분 휴지시킨다"]}',
 ARRAY['grilled','meat','heavy','quick']),

('western-018', 'seed',
 '{"ko":"안심 스테이크","en":"Tenderloin Steak","ja":"ヒレステーキ","zh":"里脊牛排"}',
 '{"ko":"부드러운 안심 스테이크","en":"Tender tenderloin steak"}',
 20, 'easy', 1,
 '[{"name":"안심 스테이크","quantity":"200g"},{"name":"소금","quantity":"적당량"},{"name":"후추","quantity":"적당량"},{"name":"올리브오일","quantity":"1큰술"},{"name":"버터","quantity":"10g"}]',
 '{"ko":["안심을 실온에 둔다","소금, 후추로 간을 한다","팬에 올리브오일을 두르고 굽는다","버터를 넣어 향을 낸다","5분 휴지시킨다"]}',
 ARRAY['grilled','meat','heavy','quick']),

('western-019', 'seed',
 '{"ko":"등심 스테이크","en":"Sirloin Steak","ja":"サーロインステーキ","zh":"西冷牛排"}',
 '{"ko":"고소한 등심 스테이크","en":"Savory sirloin steak"}',
 25, 'easy', 2,
 '[{"name":"등심 스테이크","quantity":"400g"},{"name":"소금","quantity":"적당량"},{"name":"후추","quantity":"적당량"},{"name":"올리브오일","quantity":"2큰술"},{"name":"마늘","quantity":"3쪽"}]',
 '{"ko":["스테이크를 실온에 둔다","소금, 후추로 간을 한다","팬을 달구고 올리브오일을 두른다","스테이크를 굽는다","마늘을 넣고 5분 휴지시킨다"]}',
 ARRAY['grilled','meat','heavy']),

('western-020', 'seed',
 '{"ko":"폭 찹","en":"Pork Chop","ja":"ポークチョップ","zh":"猪排"}',
 '{"ko":"허브로 양념한 구운 돼지 등심","en":"Grilled pork loin seasoned with herbs"}',
 30, 'easy', 2,
 '[{"name":"돼지 등심","quantity":"2장"},{"name":"소금","quantity":"적당량"},{"name":"후추","quantity":"적당량"},{"name":"올리브오일","quantity":"2큰술"},{"name":"로즈마리","quantity":"2줄기"},{"name":"마늘","quantity":"3쪽"}]',
 '{"ko":["돼지 등심에 칼집을 낸다","소금, 후추, 로즈마리로 양념한다","팬에 올리브오일을 두른다","돼지 등심을 굽는다","마늘을 넣고 버터로 마무리한다"]}',
 ARRAY['grilled','meat','heavy']),

-- === 햄버거 & 샌드위치 (Burgers & Sandwiches) ===
('western-021', 'seed',
 '{"ko":"클래식 햄버거","en":"Classic Burger","ja":"クラシックバーガー","zh":"经典汉堡"}',
 '{"ko":"100% 소고기 패티로 만든 수제 햄버거","en":"Homemade burger with 100% beef patty"}',
 30, 'easy', 2,
 '[{"name":"소고기 간것","quantity":"300g"},{"name":"햄버거번","quantity":"2개"},{"name":"양상추","quantity":"2장"},{"name":"토마토","quantity":"1개"},{"name":"양파","quantity":"1/4개"},{"name":"치즈","quantity":"2장"},{"name":"피클","quantity":"4장"}]',
 '{"ko":["소고기로 패티를 만든다","패티를 구운다","번을 토스트한다","번에 양상추, 패티, 치즈, 토마토, 양파, 피클을 올린다","소스를 뿌린다"]}',
 ARRAY['grilled','meat','heavy']),

('western-022', 'seed',
 '{"ko":"치즈버거","en":"Cheeseburger","ja":"チーズバーガー","zh":"芝士汉堡"}',
 '{"ko":"치즈가 듬뿍 들어간 햄버거","en":"Burger loaded with cheese"}',
 25, 'easy', 2,
 '[{"name":"소고기 간것","quantity":"300g"},{"name":"햄버거번","quantity":"2개"},{"name":"체더치즈","quantity":"4장"},{"name":"양상추","quantity":"2장"},{"name":"토마토","quantity":"1개"},{"name":"양파","quantity":"1/4개"}]',
 '{"ko":["소고기로 패티를 만든다","패티를 굽고 치즈를 올린다","번을 토스트한다","번에 양상추, 패티, 토마토, 양파를 올린다","소스를 뿌린다"]}',
 ARRAY['grilled','meat','heavy']),

('western-023', 'seed',
 '{"ko":"베이컨 버거","en":"Bacon Burger","ja":"ベーコンバーガー","zh":"培根汉堡"}',
 '{"ko":"바삭한 베이컨이 들어간 햄버거","en":"Burger with crispy bacon"}',
 30, 'easy', 2,
 '[{"name":"소고기 간것","quantity":"300g"},{"name":"햄버거번","quantity":"2개"},{"name":"베이컨","quantity":"6장"},{"name":"치즈","quantity":"2장"},{"name":"양상추","quantity":"2장"},{"name":"토마토","quantity":"1개"}]',
 '{"ko":["베이컨을 바삭하게 굽는다","소고기로 패티를 만들어 굽는다","번을 토스트한다","번에 양상추, 패티, 치즈, 베이컨, 토마토를 올린다","소스를 뿌린다"]}',
 ARRAY['grilled','meat','heavy']),

('western-024', 'seed',
 '{"ko":"클럽 샌드위치","en":"Club Sandwich","ja":"クラブサンドイッチ","zh":"总会三明治"}',
 '{"ko":"3단으로 쌓은 풍성한 샌드위치","en":"Abundant three-layer sandwich"}',
 20, 'easy', 2,
 '[{"name":"식빵","quantity":"6장"},{"name":"치킨 가슴살","quantity":"150g"},{"name":"베이컨","quantity":"4장"},{"name":"토마토","quantity":"1개"},{"name":"양상추","quantity":"4장"},{"name":"계란","quantity":"2개"},{"name":"마요네즈","quantity":"3큰술"}]',
 '{"ko":["식빵을 토스트한다","치킨과 베이컨을 굽는다","계란을 삶는다","빵에 마요네즈를 바른다","양상추, 치킨, 베이컨, 토마토, 계란을 올려 3단으로 쌓는다","대각선으로 자른다"]}',
 ARRAY['bread','meat','heavy']),

('western-025', 'seed',
 '{"ko":"BLT 샌드위치","en":"BLT Sandwich","ja":"BLTサンドイッチ","zh":"培根生菜番茄三明治"}',
 '{"ko":"베이컨, 양상추, 토마토의 클래식 샌드위치","en":"Classic sandwich with bacon, lettuce and tomato"}',
 15, 'easy', 2,
 '[{"name":"식빵","quantity":"4장"},{"name":"베이컨","quantity":"6장"},{"name":"양상추","quantity":"4장"},{"name":"토마토","quantity":"1개"},{"name":"마요네즈","quantity":"2큰술"}]',
 '{"ko":["식빵을 토스트한다","베이컨을 바삭하게 굽는다","빵에 마요네즈를 바른다","양상추, 베이컨, 토마토를 올린다","빵으로 덮고 반으로 자른다"]}',
 ARRAY['bread','meat','light','quick']),

-- === 샐러드 (Salad) ===
('western-026', 'seed',
 '{"ko":"시저 샐러드","en":"Caesar Salad","ja":"シーザーサラダ","zh":"凯撒沙拉"}',
 '{"ko":"크루통과 파마산 치즈가 들어간 샐러드","en":"Salad with croutons and parmesan cheese"}',
 15, 'easy', 2,
 '[{"name":"로메인 상추","quantity":"1포기"},{"name":"크루통","quantity":"50g"},{"name":"파마산치즈","quantity":"30g"},{"name":"베이컨","quantity":"4장"},{"name":"시저 드레싱","quantity":"4큰술"}]',
 '{"ko":["상추를 씻어 물기를 뺀다","베이컨을 바삭하게 굽는다","상추를 먹기 좋게 자른다","크루통, 베이컨, 치즈를 올린다","드레싱을 뿌린다"]}',
 ARRAY['salad','veggie','light','quick']),

('western-027', 'seed',
 '{"ko":"그릭 샐러드","en":"Greek Salad","ja":"グリークサラダ","zh":"希腊沙拉"}',
 '{"ko":"페타 치즈와 올리브가 들어간 그리스식 샐러드","en":"Greek salad with feta cheese and olives"}',
 15, 'easy', 2,
 '[{"name":"토마토","quantity":"2개"},{"name":"오이","quantity":"1개"},{"name":"양파","quantity":"1/2개"},{"name":"페타치즈","quantity":"100g"},{"name":"올리브","quantity":"20개"},{"name":"올리브오일","quantity":"3큰술"},{"name":"레몬즙","quantity":"1큰술"}]',
 '{"ko":["채소를 먹기 좋게 자른다","페타 치즈를 큐브로 자른다","모든 재료를 섞는다","올리브오일과 레몬즙을 뿌린다","오레가노를 뿌린다"]}',
 ARRAY['salad','veggie','light','quick']),

('western-028', 'seed',
 '{"ko":"코브 샐러드","en":"Cobb Salad","ja":"コブサラダ","zh":"科布沙拉"}',
 '{"ko":"다양한 재료가 줄지어 담긴 미국식 샐러드","en":"American salad with various ingredients in rows"}',
 20, 'easy', 2,
 '[{"name":"로메인 상추","quantity":"1포기"},{"name":"치킨 가슴살","quantity":"150g"},{"name":"베이컨","quantity":"4장"},{"name":"계란","quantity":"2개"},{"name":"아보카도","quantity":"1개"},{"name":"토마토","quantity":"1개"},{"name":"블루치즈","quantity":"50g"}]',
 '{"ko":["상추를 씻어 깐다","치킨과 베이컨을 굽는다","계란을 삶는다","모든 재료를 썰어 줄지어 담는다","드레싱을 뿌린다"]}',
 ARRAY['salad','meat','heavy']),

('western-029', 'seed',
 '{"ko":"카프레제 샐러드","en":"Caprese Salad","ja":"カプレーゼサラダ","zh":"卡普雷塞沙拉"}',
 '{"ko":"토마토와 모짜렐라의 이탈리아 샐러드","en":"Italian salad with tomato and mozzarella"}',
 10, 'easy', 2,
 '[{"name":"토마토","quantity":"3개"},{"name":"모짜렐라치즈","quantity":"200g"},{"name":"바질","quantity":"10장"},{"name":"올리브오일","quantity":"3큰술"},{"name":"발사믹 식초","quantity":"1큰술"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["토마토와 모짜렐라를 같은 두께로 썬다","접시에 번갈아 담는다","바질을 올린다","올리브오일과 발사믹을 뿌린다","소금을 뿌린다"]}',
 ARRAY['salad','veggie','light','quick']),

('western-030', 'seed',
 '{"ko":"니코이즈 샐러드","en":"Nicoise Salad","ja":"ニース風サラダ","zh":"尼斯沙拉"}',
 '{"ko":"참치와 감자가 들어간 프랑스 샐러드","en":"French salad with tuna and potato"}',
 25, 'medium', 2,
 '[{"name":"참치 캔","quantity":"1개"},{"name":"감자","quantity":"2개"},{"name":"그린빈","quantity":"100g"},{"name":"계란","quantity":"2개"},{"name":"토마토","quantity":"2개"},{"name":"올리브","quantity":"10개"},{"name":"양상추","quantity":"1포기"}]',
 '{"ko":["감자와 그린빈을 삶는다","계란을 삶는다","양상추를 깐다","모든 재료를 보기 좋게 담는다","비네그레트 드레싱을 뿌린다"]}',
 ARRAY['salad','seafood','light']),

-- === 수프 (Soup) ===
('western-031', 'seed',
 '{"ko":"양송이 크림 수프","en":"Mushroom Cream Soup","ja":"マッシュルームクリームスープ","zh":"蘑菇奶油汤"}',
 '{"ko":"부드러운 양송이 크림 수프","en":"Smooth mushroom cream soup"}',
 30, 'easy', 2,
 '[{"name":"양송이버섯","quantity":"300g"},{"name":"양파","quantity":"1개"},{"name":"생크림","quantity":"200ml"},{"name":"우유","quantity":"200ml"},{"name":"버터","quantity":"30g"},{"name":"밀가루","quantity":"2큰술"}]',
 '{"ko":["양파와 버섯을 다진다","버터에 양파를 볶는다","버섯을 넣고 볶는다","밀가루를 넣어 섞는다","우유와 생크림을 넣고 끓인다","믹서로 곱게 간다"]}',
 ARRAY['soupy','veggie','heavy']),

('western-032', 'seed',
 '{"ko":"클램 차우더","en":"Clam Chowder","ja":"クラムチャウダー","zh":"蛤蜊浓汤"}',
 '{"ko":"조개와 감자가 들어간 크림 수프","en":"Cream soup with clams and potato"}',
 35, 'medium', 3,
 '[{"name":"조개","quantity":"300g"},{"name":"감자","quantity":"2개"},{"name":"양파","quantity":"1개"},{"name":"베이컨","quantity":"4장"},{"name":"생크림","quantity":"200ml"},{"name":"우유","quantity":"200ml"},{"name":"밀가루","quantity":"2큰술"}]',
 '{"ko":["조개를 삶아 육수를 낸다","베이컨을 볶는다","양파와 감자를 넣고 볶는다","밀가루를 넣는다","조개 육수와 우유를 넣고 끓인다","생크림과 조개살을 넣는다"]}',
 ARRAY['soupy','seafood','heavy']),

('western-033', 'seed',
 '{"ko":"미네스트로네","en":"Minestrone","ja":"ミネストローネ","zh":"意式蔬菜汤"}',
 '{"ko":"다양한 채소가 들어간 이탈리아 수프","en":"Italian soup with various vegetables"}',
 40, 'easy', 4,
 '[{"name":"토마토","quantity":"3개"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1개"},{"name":"셀러리","quantity":"2줄기"},{"name":"호박","quantity":"100g"},{"name":"파스타","quantity":"50g"},{"name":"채소 육수","quantity":"800ml"}]',
 '{"ko":["채소를 깍둑썰기 한다","양파를 올리브오일에 볶는다","채소를 넣고 볶는다","토마토와 육수를 넣고 끓인다","파스타를 넣고 10분 끓인다","바질을 올린다"]}',
 ARRAY['soupy','veggie','light']),

('western-034', 'seed',
 '{"ko":"양파 수프","en":"French Onion Soup","ja":"オニオングラタンスープ","zh":"法式洋葱汤"}',
 '{"ko":"캐러멜라이즈한 양파와 치즈가 들어간 프랑스 수프","en":"French soup with caramelized onions and cheese"}',
 50, 'medium', 2,
 '[{"name":"양파","quantity":"4개"},{"name":"버터","quantity":"50g"},{"name":"소고기 육수","quantity":"600ml"},{"name":"바게트","quantity":"4조각"},{"name":"그뤼에르 치즈","quantity":"100g"},{"name":"화이트와인","quantity":"50ml"}]',
 '{"ko":["양파를 얇게 썬다","버터에 양파를 30분 볶아 캐러멜라이즈한다","화이트와인을 넣는다","소고기 육수를 넣고 끓인다","그릇에 담고 바게트와 치즈를 올린다","오븐에서 치즈를 녹인다"]}',
 ARRAY['soupy','veggie','heavy','baked']),

('western-035', 'seed',
 '{"ko":"토마토 수프","en":"Tomato Soup","ja":"トマトスープ","zh":"番茄汤"}',
 '{"ko":"신선한 토마토로 만든 건강한 수프","en":"Healthy soup made with fresh tomatoes"}',
 30, 'easy', 2,
 '[{"name":"토마토","quantity":"6개"},{"name":"양파","quantity":"1개"},{"name":"마늘","quantity":"3쪽"},{"name":"채소 육수","quantity":"400ml"},{"name":"생크림","quantity":"100ml"},{"name":"바질","quantity":"약간"}]',
 '{"ko":["토마토를 데쳐 껍질을 벗긴다","양파와 마늘을 볶는다","토마토를 넣고 볶는다","육수를 넣고 20분 끓인다","믹서로 곱게 간다","생크림을 넣고 바질을 올린다"]}',
 ARRAY['soupy','veggie','light']),

-- === 리조또 & 라이스 (Risotto & Rice) ===
('western-036', 'seed',
 '{"ko":"버섯 리조또","en":"Mushroom Risotto","ja":"マッシュルームリゾット","zh":"蘑菇烩饭"}',
 '{"ko":"버섯과 파마산 치즈로 만든 크림 리조또","en":"Creamy risotto with mushrooms and parmesan"}',
 35, 'medium', 2,
 '[{"name":"아보리오 쌀","quantity":"200g"},{"name":"양송이버섯","quantity":"200g"},{"name":"양파","quantity":"1/2개"},{"name":"화이트와인","quantity":"100ml"},{"name":"채소 육수","quantity":"600ml"},{"name":"파마산치즈","quantity":"50g"},{"name":"버터","quantity":"30g"}]',
 '{"ko":["양파를 버터에 볶는다","쌀을 넣고 투명해질 때까지 볶는다","화이트와인을 넣는다","육수를 조금씩 넣으며 저어준다","버섯을 볶아 넣는다","치즈와 버터를 넣어 마무리한다"]}',
 ARRAY['rice','veggie','heavy']),

('western-037', 'seed',
 '{"ko":"해산물 리조또","en":"Seafood Risotto","ja":"シーフードリゾット","zh":"海鲜烩饭"}',
 '{"ko":"새우와 조개가 들어간 해산물 리조또","en":"Seafood risotto with shrimp and clams"}',
 40, 'medium', 2,
 '[{"name":"아보리오 쌀","quantity":"200g"},{"name":"새우","quantity":"150g"},{"name":"조개","quantity":"150g"},{"name":"양파","quantity":"1/2개"},{"name":"화이트와인","quantity":"100ml"},{"name":"해산물 육수","quantity":"600ml"},{"name":"토마토","quantity":"2개"}]',
 '{"ko":["양파를 올리브오일에 볶는다","쌀을 넣고 볶는다","화이트와인을 넣는다","육수를 조금씩 넣으며 저어준다","해산물과 토마토를 넣는다","파슬리를 뿌린다"]}',
 ARRAY['rice','seafood','heavy']),

('western-038', 'seed',
 '{"ko":"토마토 리조또","en":"Tomato Risotto","ja":"トマトリゾット","zh":"番茄烩饭"}',
 '{"ko":"신선한 토마토로 만든 상큼한 리조또","en":"Fresh risotto made with tomatoes"}',
 35, 'medium', 2,
 '[{"name":"아보리오 쌀","quantity":"200g"},{"name":"토마토","quantity":"4개"},{"name":"양파","quantity":"1/2개"},{"name":"화이트와인","quantity":"100ml"},{"name":"채소 육수","quantity":"600ml"},{"name":"파마산치즈","quantity":"50g"},{"name":"바질","quantity":"약간"}]',
 '{"ko":["토마토를 다진다","양파를 올리브오일에 볶는다","쌀을 넣고 볶는다","화이트와인을 넣는다","육수와 토마토를 넣으며 저어준다","치즈와 바질을 넣는다"]}',
 ARRAY['rice','veggie','light']),

('western-039', 'seed',
 '{"ko":"치킨 라이스","en":"Chicken Rice","ja":"チキンライス","zh":"鸡肉饭"}',
 '{"ko":"케첩으로 맛을 낸 치킨 볶음밥","en":"Chicken fried rice seasoned with ketchup"}',
 20, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"닭가슴살","quantity":"150g"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1/2개"},{"name":"케첩","quantity":"4큰술"},{"name":"버터","quantity":"20g"}]',
 '{"ko":["닭가슴살을 깍둑썰기 한다","양파와 당근을 다진다","버터에 닭고기를 볶는다","채소를 넣고 볶는다","밥을 넣고 케첩을 넣어 볶는다"]}',
 ARRAY['rice','meat','light','quick']),

('western-040', 'seed',
 '{"ko":"필라프","en":"Pilaf","ja":"ピラフ","zh":"手抓饭"}',
 '{"ko":"버터로 볶은 쌀을 육수로 지은 밥","en":"Rice cooked in broth after being sautéed in butter"}',
 30, 'easy', 3,
 '[{"name":"쌀","quantity":"2컵"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1개"},{"name":"닭고기 육수","quantity":"3컵"},{"name":"버터","quantity":"30g"},{"name":"파슬리","quantity":"약간"}]',
 '{"ko":["쌀을 씻어 물기를 뺀다","양파와 당근을 다진다","버터에 쌀을 볶는다","채소를 넣고 볶는다","육수를 넣고 20분 끓인다","파슬리를 올린다"]}',
 ARRAY['rice','veggie','light']),

-- === 그라탕 & 캐서롤 (Gratin & Casserole) ===
('western-041', 'seed',
 '{"ko":"라자냐","en":"Lasagna","ja":"ラザニア","zh":"千层面"}',
 '{"ko":"미트 소스와 치즈가 층층이 쌓인 이탈리아 요리","en":"Italian dish with layers of meat sauce and cheese"}',
 60, 'hard', 4,
 '[{"name":"라자냐 면","quantity":"12장"},{"name":"소고기 간것","quantity":"400g"},{"name":"토마토소스","quantity":"400ml"},{"name":"모짜렐라치즈","quantity":"300g"},{"name":"리코타치즈","quantity":"200g"},{"name":"파마산치즈","quantity":"100g"},{"name":"양파","quantity":"1개"}]',
 '{"ko":["미트 소스를 만든다","라자냐 면을 삶는다","그릇에 소스, 면, 치즈를 층층이 쌓는다","맨 위에 치즈를 듬뿍 올린다","180도 오븐에서 30분 굽는다","10분 식힌다"]}',
 ARRAY['baked','pasta','meat','heavy']),

('western-042', 'seed',
 '{"ko":"감자 그라탕","en":"Potato Gratin","ja":"ポテトグラタン","zh":"焗土豆"}',
 '{"ko":"감자와 치즈, 크림으로 만든 그라탕","en":"Gratin made with potatoes, cheese and cream"}',
 50, 'medium', 3,
 '[{"name":"감자","quantity":"4개"},{"name":"생크림","quantity":"300ml"},{"name":"우유","quantity":"200ml"},{"name":"마늘","quantity":"2쪽"},{"name":"그뤼에르 치즈","quantity":"150g"},{"name":"파마산치즈","quantity":"50g"}]',
 '{"ko":["감자를 얇게 슬라이스한다","마늘을 문지른 그릇에 감자를 담는다","생크림과 우유를 섞어 붓는다","치즈를 올린다","180도 오븐에서 40분 굽는다","윗면이 노릇해질 때까지 굽는다"]}',
 ARRAY['baked','veggie','heavy']),

('western-043', 'seed',
 '{"ko":"새우 그라탕","en":"Shrimp Gratin","ja":"海老グラタン","zh":"焗虾"}',
 '{"ko":"새우와 화이트 소스로 만든 그라탕","en":"Gratin made with shrimp and white sauce"}',
 40, 'medium', 2,
 '[{"name":"새우","quantity":"200g"},{"name":"양송이버섯","quantity":"100g"},{"name":"양파","quantity":"1/2개"},{"name":"우유","quantity":"300ml"},{"name":"밀가루","quantity":"3큰술"},{"name":"버터","quantity":"40g"},{"name":"모짜렐라치즈","quantity":"100g"}]',
 '{"ko":["버터에 밀가루를 볶아 화이트 소스를 만든다","새우와 버섯을 볶는다","그릇에 담고 화이트 소스를 붓는다","치즈를 올린다","200도 오븐에서 15분 굽는다"]}',
 ARRAY['baked','seafood','heavy']),

('western-044', 'seed',
 '{"ko":"치킨 그라탕","en":"Chicken Gratin","ja":"チキングラタン","zh":"焗鸡肉"}',
 '{"ko":"치킨과 마카로니로 만든 그라탕","en":"Gratin made with chicken and macaroni"}',
 40, 'medium', 3,
 '[{"name":"닭가슴살","quantity":"200g"},{"name":"마카로니","quantity":"150g"},{"name":"양파","quantity":"1개"},{"name":"우유","quantity":"300ml"},{"name":"밀가루","quantity":"3큰술"},{"name":"버터","quantity":"40g"},{"name":"모짜렐라치즈","quantity":"150g"}]',
 '{"ko":["마카로니를 삶는다","닭고기를 볶는다","화이트 소스를 만든다","마카로니와 닭고기를 섞는다","그릇에 담고 치즈를 올린다","200도 오븐에서 15분 굽는다"]}',
 ARRAY['baked','meat','heavy']),

('western-045', 'seed',
 '{"ko":"무사카","en":"Moussaka","ja":"ムサカ","zh":"慕沙卡"}',
 '{"ko":"가지와 미트 소스로 만든 그리스 요리","en":"Greek dish made with eggplant and meat sauce"}',
 70, 'hard', 4,
 '[{"name":"가지","quantity":"3개"},{"name":"소고기 간것","quantity":"400g"},{"name":"토마토소스","quantity":"300ml"},{"name":"양파","quantity":"1개"},{"name":"우유","quantity":"400ml"},{"name":"밀가루","quantity":"4큰술"},{"name":"버터","quantity":"50g"},{"name":"파마산치즈","quantity":"80g"}]',
 '{"ko":["가지를 슬라이스해 구운다","미트 소스를 만든다","베샤멜 소스를 만든다","가지, 미트 소스, 베샤멜을 층층이 쌓는다","치즈를 뿌린다","180도 오븐에서 40분 굽는다"]}',
 ARRAY['baked','meat','heavy']),

-- === 계란 요리 (Egg Dishes) ===
('western-046', 'seed',
 '{"ko":"오믈렛","en":"Omelette","ja":"オムレツ","zh":"煎蛋卷"}',
 '{"ko":"부드러운 계란 오믈렛","en":"Soft egg omelette"}',
 10, 'easy', 1,
 '[{"name":"계란","quantity":"3개"},{"name":"우유","quantity":"2큰술"},{"name":"버터","quantity":"15g"},{"name":"소금","quantity":"약간"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["계란에 우유, 소금, 후추를 넣어 푼다","팬에 버터를 녹인다","계란물을 붓는다","젓가락으로 저으며 익힌다","반으로 접는다"]}',
 ARRAY['quick','veggie','light']),

('western-047', 'seed',
 '{"ko":"스크램블 에그","en":"Scrambled Eggs","ja":"スクランブルエッグ","zh":"炒蛋"}',
 '{"ko":"부드럽고 크리미한 스크램블 에그","en":"Soft and creamy scrambled eggs"}',
 10, 'easy', 2,
 '[{"name":"계란","quantity":"4개"},{"name":"우유","quantity":"3큰술"},{"name":"버터","quantity":"20g"},{"name":"소금","quantity":"약간"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["계란에 우유를 넣어 푼다","팬에 버터를 녹인다","약한 불에서 계란을 넣는다","젓가락으로 저으며 익힌다","소금, 후추로 간한다"]}',
 ARRAY['quick','veggie','light']),

('western-048', 'seed',
 '{"ko":"에그 베네딕트","en":"Eggs Benedict","ja":"エッグベネディクト","zh":"班尼迪克蛋"}',
 '{"ko":"포치드 에그와 홀란데이즈 소스가 올라간 아침 요리","en":"Breakfast dish with poached eggs and hollandaise sauce"}',
 25, 'hard', 2,
 '[{"name":"계란","quantity":"4개"},{"name":"잉글리시 머핀","quantity":"2개"},{"name":"햄","quantity":"4장"},{"name":"버터","quantity":"100g"},{"name":"레몬즙","quantity":"1큰술"},{"name":"식초","quantity":"1큰술"}]',
 '{"ko":["홀란데이즈 소스를 만든다","물에 식초를 넣고 포치드 에그를 만든다","머핀을 토스트하고 햄을 굽는다","머핀 위에 햄, 포치드 에그를 올린다","홀란데이즈 소스를 뿌린다"]}',
 ARRAY['baked','meat','heavy']),

('western-049', 'seed',
 '{"ko":"프리타타","en":"Frittata","ja":"フリッタータ","zh":"意式烘蛋"}',
 '{"ko":"채소와 치즈가 들어간 이탈리아식 오믈렛","en":"Italian omelette with vegetables and cheese"}',
 30, 'medium', 3,
 '[{"name":"계란","quantity":"6개"},{"name":"감자","quantity":"2개"},{"name":"양파","quantity":"1개"},{"name":"파프리카","quantity":"1개"},{"name":"모짜렐라치즈","quantity":"100g"},{"name":"올리브오일","quantity":"3큰술"}]',
 '{"ko":["감자를 얇게 썰어 익힌다","양파와 파프리카를 볶는다","계란을 풀어 채소와 섞는다","팬에 붓고 약불로 익힌다","치즈를 올리고 오븐에서 마무리한다"]}',
 ARRAY['baked','veggie','heavy']),

('western-050', 'seed',
 '{"ko":"키쉬","en":"Quiche","ja":"キッシュ","zh":"法式咸派"}',
 '{"ko":"계란과 크림이 들어간 프랑스식 파이","en":"French pie with eggs and cream"}',
 50, 'medium', 4,
 '[{"name":"파이 반죽","quantity":"1장"},{"name":"계란","quantity":"4개"},{"name":"생크림","quantity":"200ml"},{"name":"베이컨","quantity":"100g"},{"name":"양파","quantity":"1/2개"},{"name":"그뤼에르 치즈","quantity":"100g"}]',
 '{"ko":["파이 틀에 반죽을 깐다","베이컨과 양파를 볶는다","계란과 생크림을 섞는다","파이에 베이컨과 치즈를 올린다","계란물을 붓는다","180도 오븐에서 35분 굽는다"]}',
 ARRAY['baked','meat','heavy']),

-- === 생선 요리 (Fish Dishes) ===
('western-051', 'seed',
 '{"ko":"피쉬 앤 칩스","en":"Fish and Chips","ja":"フィッシュアンドチップス","zh":"炸鱼薯条"}',
 '{"ko":"바삭한 생선 튀김과 감자튀김","en":"Crispy fried fish with french fries"}',
 35, 'medium', 2,
 '[{"name":"대구","quantity":"2토막"},{"name":"감자","quantity":"3개"},{"name":"밀가루","quantity":"100g"},{"name":"맥주","quantity":"100ml"},{"name":"베이킹파우더","quantity":"1작은술"},{"name":"식용유","quantity":"적당량"}]',
 '{"ko":["감자를 막대 모양으로 썰어 튀긴다","밀가루, 맥주, 베이킹파우더로 반죽을 만든다","대구에 반죽을 입힌다","170도 기름에 튀긴다","키친타올에 기름을 뺀다","타르타르 소스와 함께 낸다"]}',
 ARRAY['seafood','heavy']),

('western-052', 'seed',
 '{"ko":"연어 스테이크","en":"Salmon Steak","ja":"サーモンステーキ","zh":"三文鱼排"}',
 '{"ko":"허브로 양념한 구운 연어","en":"Grilled salmon seasoned with herbs"}',
 20, 'easy', 2,
 '[{"name":"연어","quantity":"2토막"},{"name":"레몬","quantity":"1개"},{"name":"딜","quantity":"약간"},{"name":"올리브오일","quantity":"2큰술"},{"name":"소금","quantity":"약간"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["연어에 소금, 후추를 뿌린다","팬에 올리브오일을 두른다","연어를 껍질 면부터 굽는다","뒤집어서 익힌다","딜과 레몬을 올린다"]}',
 ARRAY['grilled','seafood','light','quick']),

('western-053', 'seed',
 '{"ko":"참치 스테이크","en":"Tuna Steak","ja":"マグロステーキ","zh":"金枪鱼排"}',
 '{"ko":"겉은 바삭하고 속은 촉촉한 참치 스테이크","en":"Tuna steak with crispy outside and moist inside"}',
 15, 'easy', 2,
 '[{"name":"참치","quantity":"2토막"},{"name":"간장","quantity":"2큰술"},{"name":"레몬즙","quantity":"1큰술"},{"name":"올리브오일","quantity":"2큰술"},{"name":"마늘","quantity":"2쪽"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["참치에 간장, 레몬즙으로 밑간한다","팬을 뜨겁게 달군다","올리브오일을 두르고 참치를 굽는다","앞뒤로 각 1분씩만 굽는다","마늘칩을 올린다"]}',
 ARRAY['grilled','seafood','light','quick']),

('western-054', 'seed',
 '{"ko":"아쿠아파짜","en":"Acqua Pazza","ja":"アクアパッツァ","zh":"水煮鱼"}',
 '{"ko":"생선을 토마토와 화이트와인으로 끓인 이탈리아 요리","en":"Italian dish of fish simmered with tomato and white wine"}',
 30, 'medium', 2,
 '[{"name":"도미","quantity":"1마리"},{"name":"방울토마토","quantity":"15개"},{"name":"올리브","quantity":"10개"},{"name":"화이트와인","quantity":"100ml"},{"name":"마늘","quantity":"4쪽"},{"name":"올리브오일","quantity":"3큰술"},{"name":"바질","quantity":"약간"}]',
 '{"ko":["도미를 손질한다","팬에 올리브오일과 마늘을 넣는다","도미를 올리고 굽는다","토마토, 올리브, 화이트와인을 넣는다","뚜껑을 덮고 15분 끓인다","바질을 올린다"]}',
 ARRAY['soupy','seafood','light']),

('western-055', 'seed',
 '{"ko":"피쉬 타코","en":"Fish Taco","ja":"フィッシュタコス","zh":"鱼肉玉米卷"}',
 '{"ko":"생선 튀김이 들어간 멕시칸 타코","en":"Mexican taco with fried fish"}',
 30, 'medium', 3,
 '[{"name":"흰살생선","quantity":"300g"},{"name":"토르티야","quantity":"6장"},{"name":"양배추","quantity":"1/4통"},{"name":"라임","quantity":"2개"},{"name":"사워크림","quantity":"100ml"},{"name":"밀가루","quantity":"50g"}]',
 '{"ko":["생선에 밀가루를 묻혀 튀긴다","양배추를 채썬다","사워크림과 라임즙을 섞는다","토르티야를 데운다","토르티야에 양배추, 생선을 올린다","소스를 뿌린다"]}',
 ARRAY['seafood','light']),

-- === 멕시칸 (Mexican) ===
('western-056', 'seed',
 '{"ko":"타코","en":"Taco","ja":"タコス","zh":"墨西哥卷饼"}',
 '{"ko":"소고기와 채소가 들어간 멕시칸 타코","en":"Mexican taco with beef and vegetables"}',
 25, 'easy', 3,
 '[{"name":"소고기 간것","quantity":"300g"},{"name":"토르티야","quantity":"6장"},{"name":"양상추","quantity":"4장"},{"name":"토마토","quantity":"2개"},{"name":"치즈","quantity":"100g"},{"name":"타코 시즈닝","quantity":"2큰술"}]',
 '{"ko":["소고기를 타코 시즈닝으로 볶는다","양상추를 채썬다","토마토를 깍둑썰기한다","토르티야를 데운다","토르티야에 고기, 채소, 치즈를 올린다","살사 소스를 뿌린다"]}',
 ARRAY['meat','light','quick']),

('western-057', 'seed',
 '{"ko":"부리또","en":"Burrito","ja":"ブリトー","zh":"墨西哥卷"}',
 '{"ko":"밥과 고기를 토르티야로 말아 만든 멕시칸 요리","en":"Mexican dish of rice and meat rolled in tortilla"}',
 30, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"소고기 간것","quantity":"200g"},{"name":"토르티야","quantity":"2장"},{"name":"치즈","quantity":"100g"},{"name":"양상추","quantity":"4장"},{"name":"사워크림","quantity":"50ml"},{"name":"살사 소스","quantity":"4큰술"}]',
 '{"ko":["소고기를 양념해 볶는다","토르티야를 데운다","토르티야에 밥, 고기, 치즈, 양상추를 올린다","살사와 사워크림을 뿌린다","김밥처럼 말아 반으로 자른다"]}',
 ARRAY['rice','meat','heavy']),

('western-058', 'seed',
 '{"ko":"퀘사디아","en":"Quesadilla","ja":"ケサディーヤ","zh":"墨西哥起司饼"}',
 '{"ko":"치즈가 든 토르티야를 구운 멕시칸 요리","en":"Mexican dish of grilled tortilla with cheese"}',
 15, 'easy', 2,
 '[{"name":"토르티야","quantity":"2장"},{"name":"체더치즈","quantity":"150g"},{"name":"양파","quantity":"1/4개"},{"name":"피망","quantity":"1/2개"},{"name":"닭가슴살","quantity":"100g"}]',
 '{"ko":["닭고기와 채소를 볶는다","토르티야에 치즈를 뿌린다","닭고기와 채소를 올린다","토르티야를 반으로 접는다","팬에서 양면을 굽는다","삼각형으로 자른다"]}',
 ARRAY['meat','light','quick']),

('western-059', 'seed',
 '{"ko":"나초","en":"Nachos","ja":"ナチョス","zh":"玉米片"}',
 '{"ko":"치즈와 살사가 올라간 멕시칸 스낵","en":"Mexican snack with cheese and salsa"}',
 20, 'easy', 3,
 '[{"name":"나초 칩","quantity":"200g"},{"name":"체더치즈","quantity":"150g"},{"name":"할라피뇨","quantity":"50g"},{"name":"사워크림","quantity":"100ml"},{"name":"과카몰리","quantity":"100g"},{"name":"살사 소스","quantity":"100ml"}]',
 '{"ko":["접시에 나초 칩을 담는다","치즈를 뿌린다","전자레인지에서 치즈를 녹인다","할라피뇨를 올린다","사워크림, 과카몰리, 살사를 올린다"]}',
 ARRAY['veggie','light','quick']),

('western-060', 'seed',
 '{"ko":"엔칠라다","en":"Enchilada","ja":"エンチラーダ","zh":"墨西哥肉卷"}',
 '{"ko":"고기를 토르티야로 말아 소스를 뿌려 구운 멕시칸 요리","en":"Mexican dish of meat rolled in tortilla with sauce and baked"}',
 40, 'medium', 3,
 '[{"name":"토르티야","quantity":"6장"},{"name":"닭가슴살","quantity":"300g"},{"name":"체더치즈","quantity":"200g"},{"name":"양파","quantity":"1개"},{"name":"엔칠라다 소스","quantity":"400ml"},{"name":"사워크림","quantity":"100ml"}]',
 '{"ko":["닭고기를 삶아 찢는다","양파를 볶아 닭고기와 섞는다","토르티야에 닭고기를 넣어 만다","그릇에 담고 소스를 뿌린다","치즈를 올리고 180도 오븐에서 20분 굽는다"]}',
 ARRAY['baked','meat','heavy']),

-- === 기타 메인 요리 (Other Main Dishes) ===
('western-061', 'seed',
 '{"ko":"비프 스튜","en":"Beef Stew","ja":"ビーフシチュー","zh":"炖牛肉"}',
 '{"ko":"소고기와 채소를 푹 끓인 서양식 스튜","en":"Western stew with beef and vegetables simmered"}',
 120, 'medium', 4,
 '[{"name":"소고기","quantity":"500g"},{"name":"감자","quantity":"3개"},{"name":"당근","quantity":"2개"},{"name":"양파","quantity":"2개"},{"name":"토마토","quantity":"2개"},{"name":"레드와인","quantity":"200ml"},{"name":"소고기 육수","quantity":"600ml"}]',
 '{"ko":["소고기를 큼직하게 자른다","밀가루를 묻혀 갈색이 되도록 굽는다","양파를 볶는다","레드와인과 육수를 넣는다","감자와 당근을 넣고 1시간 끓인다","소금, 후추로 간한다"]}',
 ARRAY['soupy','meat','heavy']),

('western-062', 'seed',
 '{"ko":"치킨 카레","en":"Chicken Curry","ja":"チキンカレー","zh":"咖喱鸡"}',
 '{"ko":"닭고기와 채소로 만든 카레","en":"Curry made with chicken and vegetables"}',
 40, 'easy', 4,
 '[{"name":"닭고기","quantity":"400g"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"2개"},{"name":"카레가루","quantity":"100g"},{"name":"물","quantity":"800ml"}]',
 '{"ko":["닭고기와 채소를 자른다","양파를 볶는다","닭고기를 넣고 볶는다","물을 넣고 끓인다","채소를 넣고 20분 끓인다","불을 끄고 카레가루를 넣어 녹인다"]}',
 ARRAY['soupy','meat','heavy']),

('western-063', 'seed',
 '{"ko":"비프 스트로가노프","en":"Beef Stroganoff","ja":"ビーフストロガノフ","zh":"俄式炖牛肉"}',
 '{"ko":"사워크림을 넣은 러시아식 소고기 요리","en":"Russian beef dish with sour cream"}',
 35, 'medium', 3,
 '[{"name":"소고기","quantity":"400g"},{"name":"양송이버섯","quantity":"200g"},{"name":"양파","quantity":"1개"},{"name":"사워크림","quantity":"200ml"},{"name":"소고기 육수","quantity":"200ml"},{"name":"버터","quantity":"30g"}]',
 '{"ko":["소고기를 얇게 썬다","버터에 양파를 볶는다","소고기를 넣고 볶는다","버섯을 넣는다","육수를 넣고 끓인다","사워크림을 넣어 마무리한다"]}',
 ARRAY['soupy','meat','heavy']),

('western-064', 'seed',
 '{"ko":"미트볼","en":"Meatballs","ja":"ミートボール","zh":"肉丸"}',
 '{"ko":"토마토 소스에 넣은 소고기 미트볼","en":"Beef meatballs in tomato sauce"}',
 40, 'easy', 4,
 '[{"name":"소고기 간것","quantity":"500g"},{"name":"빵가루","quantity":"50g"},{"name":"계란","quantity":"1개"},{"name":"토마토소스","quantity":"400ml"},{"name":"양파","quantity":"1개"},{"name":"마늘","quantity":"3쪽"}]',
 '{"ko":["소고기, 빵가루, 계란을 섞는다","둥글게 빚어 미트볼을 만든다","팬에서 미트볼을 굽는다","양파와 마늘을 볶는다","토마토소스를 넣고 끓인다","미트볼을 넣고 20분 끓인다"]}',
 ARRAY['meat','heavy']),

('western-065', 'seed',
 '{"ko":"치킨 팟파이","en":"Chicken Pot Pie","ja":"チキンポットパイ","zh":"鸡肉派"}',
 '{"ko":"크림 소스 치킨을 파이로 덮어 구운 요리","en":"Cream sauce chicken covered with pie crust and baked"}',
 60, 'medium', 4,
 '[{"name":"닭가슴살","quantity":"300g"},{"name":"파이 반죽","quantity":"1장"},{"name":"당근","quantity":"1개"},{"name":"완두콩","quantity":"100g"},{"name":"우유","quantity":"300ml"},{"name":"밀가루","quantity":"3큰술"},{"name":"버터","quantity":"40g"}]',
 '{"ko":["닭고기와 채소를 자른다","버터로 화이트 소스를 만든다","닭고기와 채소를 섞는다","그릇에 담고 파이 반죽을 덮는다","계란물을 바른다","200도 오븐에서 30분 굽는다"]}',
 ARRAY['baked','meat','heavy']),

-- === 아침 요리 (Breakfast) ===
('western-066', 'seed',
 '{"ko":"프렌치 토스트","en":"French Toast","ja":"フレンチトースト","zh":"法式吐司"}',
 '{"ko":"달걀과 우유에 적신 빵을 구운 아침 요리","en":"Breakfast dish of bread soaked in egg and milk then fried"}',
 15, 'easy', 2,
 '[{"name":"식빵","quantity":"4장"},{"name":"계란","quantity":"2개"},{"name":"우유","quantity":"100ml"},{"name":"설탕","quantity":"2큰술"},{"name":"버터","quantity":"20g"},{"name":"시나몬","quantity":"약간"}]',
 '{"ko":["계란, 우유, 설탕, 시나몬을 섞는다","식빵을 계란물에 담근다","팬에 버터를 녹인다","빵을 앞뒤로 노릇하게 굽는다","메이플 시럽을 뿌린다"]}',
 ARRAY['bread','veggie','light','quick']),

('western-067', 'seed',
 '{"ko":"팬케이크","en":"Pancake","ja":"パンケーキ","zh":"煎饼"}',
 '{"ko":"푹신한 미국식 팬케이크","en":"Fluffy American pancakes"}',
 20, 'easy', 3,
 '[{"name":"밀가루","quantity":"200g"},{"name":"계란","quantity":"2개"},{"name":"우유","quantity":"200ml"},{"name":"베이킹파우더","quantity":"2작은술"},{"name":"설탕","quantity":"3큰술"},{"name":"버터","quantity":"적당량"}]',
 '{"ko":["밀가루, 베이킹파우더, 설탕을 섞는다","계란과 우유를 넣어 반죽을 만든다","팬에 버터를 녹인다","반죽을 붓고 기포가 생기면 뒤집는다","메이플 시럽과 버터를 올린다"]}',
 ARRAY['bread','veggie','light']),

('western-068', 'seed',
 '{"ko":"와플","en":"Waffle","ja":"ワッフル","zh":"华夫饼"}',
 '{"ko":"바삭한 겉과 부드러운 속의 와플","en":"Waffle with crispy outside and soft inside"}',
 20, 'easy', 3,
 '[{"name":"밀가루","quantity":"200g"},{"name":"계란","quantity":"2개"},{"name":"우유","quantity":"250ml"},{"name":"베이킹파우더","quantity":"2작은술"},{"name":"설탕","quantity":"3큰술"},{"name":"버터","quantity":"50g"}]',
 '{"ko":["밀가루, 베이킹파우더, 설탕을 섞는다","계란, 우유, 녹인 버터를 넣는다","와플 기계를 예열한다","반죽을 붓고 5분 굽는다","생크림과 과일을 올린다"]}',
 ARRAY['bread','veggie','light']),

('western-069', 'seed',
 '{"ko":"잉글리시 브렉퍼스트","en":"English Breakfast","ja":"イングリッシュブレックファスト","zh":"英式早餐"}',
 '{"ko":"소시지, 베이컨, 계란이 포함된 영국식 아침 식사","en":"British breakfast with sausage, bacon and eggs"}',
 25, 'easy', 2,
 '[{"name":"소시지","quantity":"4개"},{"name":"베이컨","quantity":"4장"},{"name":"계란","quantity":"2개"},{"name":"토마토","quantity":"2개"},{"name":"버섯","quantity":"100g"},{"name":"식빵","quantity":"2장"}]',
 '{"ko":["소시지를 굽는다","베이컨을 굽는다","버섯과 토마토를 굽는다","계란을 프라이한다","식빵을 토스트한다","모든 재료를 접시에 담는다"]}',
 ARRAY['grilled','meat','heavy']),

('western-070', 'seed',
 '{"ko":"그래놀라","en":"Granola","ja":"グラノーラ","zh":"格兰诺拉麦片"}',
 '{"ko":"요거트와 과일을 곁들인 건강한 그래놀라","en":"Healthy granola with yogurt and fruits"}',
 5, 'easy', 1,
 '[{"name":"그래놀라","quantity":"100g"},{"name":"요거트","quantity":"200ml"},{"name":"바나나","quantity":"1개"},{"name":"블루베리","quantity":"50g"},{"name":"꿀","quantity":"1큰술"}]',
 '{"ko":["볼에 요거트를 담는다","그래놀라를 올린다","바나나를 썰어 올린다","블루베리를 올린다","꿀을 뿌린다"]}',
 ARRAY['veggie','light','quick']),

-- === 디저트 & 베이킹 (Dessert & Baking) ===
('western-071', 'seed',
 '{"ko":"브라우니","en":"Brownie","ja":"ブラウニー","zh":"布朗尼"}',
 '{"ko":"진한 초콜릿 브라우니","en":"Rich chocolate brownie"}',
 40, 'easy', 8,
 '[{"name":"다크초콜릿","quantity":"200g"},{"name":"버터","quantity":"150g"},{"name":"설탕","quantity":"150g"},{"name":"계란","quantity":"3개"},{"name":"밀가루","quantity":"100g"},{"name":"호두","quantity":"50g"}]',
 '{"ko":["초콜릿과 버터를 녹인다","설탕과 계란을 섞는다","초콜릿을 넣는다","밀가루와 호두를 넣는다","틀에 붓는다","180도 오븐에서 25분 굽는다"]}',
 ARRAY['baked','veggie','heavy']),

('western-072', 'seed',
 '{"ko":"치즈케이크","en":"Cheesecake","ja":"チーズケーキ","zh":"芝士蛋糕"}',
 '{"ko":"부드러운 뉴욕 스타일 치즈케이크","en":"Smooth New York style cheesecake"}',
 90, 'hard', 8,
 '[{"name":"크림치즈","quantity":"500g"},{"name":"설탕","quantity":"150g"},{"name":"계란","quantity":"3개"},{"name":"생크림","quantity":"200ml"},{"name":"레몬즙","quantity":"2큰술"},{"name":"쿠키","quantity":"150g"},{"name":"버터","quantity":"70g"}]',
 '{"ko":["쿠키를 부수고 버터와 섞어 바닥에 깐다","크림치즈와 설탕을 섞는다","계란을 하나씩 넣는다","생크림과 레몬즙을 넣는다","160도 오븐에서 50분 굽는다","냉장고에서 4시간 식힌다"]}',
 ARRAY['baked','veggie','heavy']),

('western-073', 'seed',
 '{"ko":"티라미수","en":"Tiramisu","ja":"ティラミス","zh":"提拉米苏"}',
 '{"ko":"커피를 적신 이탈리아 디저트","en":"Italian dessert with coffee-soaked ladyfingers"}',
 30, 'easy', 6,
 '[{"name":"마스카포네치즈","quantity":"250g"},{"name":"계란","quantity":"3개"},{"name":"설탕","quantity":"100g"},{"name":"레이디핑거","quantity":"20개"},{"name":"에스프레소","quantity":"200ml"},{"name":"코코아가루","quantity":"적당량"}]',
 '{"ko":["노른자와 설탕을 섞는다","마스카포네를 넣는다","흰자를 휘핑해 섞는다","레이디핑거를 커피에 적신다","크림과 레이디핑거를 층층이 쌓는다","코코아가루를 뿌리고 냉장 보관한다"]}',
 ARRAY['veggie','heavy']),

('western-074', 'seed',
 '{"ko":"애플파이","en":"Apple Pie","ja":"アップルパイ","zh":"苹果派"}',
 '{"ko":"시나몬 향 나는 따뜻한 애플파이","en":"Warm apple pie with cinnamon"}',
 60, 'medium', 6,
 '[{"name":"사과","quantity":"5개"},{"name":"파이 반죽","quantity":"2장"},{"name":"설탕","quantity":"100g"},{"name":"시나몬","quantity":"1작은술"},{"name":"레몬즙","quantity":"2큰술"},{"name":"버터","quantity":"30g"}]',
 '{"ko":["사과를 얇게 썬다","설탕, 시나몬, 레몬즙과 섞는다","파이 틀에 반죽을 깐다","사과를 채운다","반죽으로 덮는다","200도 오븐에서 40분 굽는다"]}',
 ARRAY['baked','veggie','heavy']),

('western-075', 'seed',
 '{"ko":"크림 브륄레","en":"Creme Brulee","ja":"クレームブリュレ","zh":"焦糖布丁"}',
 '{"ko":"바삭한 카라멜 층이 있는 프랑스 디저트","en":"French dessert with crispy caramel layer"}',
 90, 'hard', 4,
 '[{"name":"생크림","quantity":"400ml"},{"name":"달걀노른자","quantity":"5개"},{"name":"설탕","quantity":"100g"},{"name":"바닐라빈","quantity":"1개"},{"name":"갈색설탕","quantity":"적당량"}]',
 '{"ko":["생크림과 바닐라를 데운다","노른자와 설탕을 섞는다","생크림을 넣어 섞는다","틀에 붓는다","150도 오븐에서 40분 굽는다","식힌 후 갈색설탕을 뿌려 토치로 굽는다"]}',
 ARRAY['baked','veggie','heavy']),

('western-076', 'seed',
 '{"ko":"마카롱","en":"Macaron","ja":"マカロン","zh":"马卡龙"}',
 '{"ko":"프랑스식 아몬드 쿠키","en":"French almond cookies"}',
 60, 'hard', 20,
 '[{"name":"아몬드가루","quantity":"100g"},{"name":"슈가파우더","quantity":"100g"},{"name":"계란흰자","quantity":"70g"},{"name":"설탕","quantity":"50g"},{"name":"버터크림","quantity":"적당량"}]',
 '{"ko":["아몬드가루와 슈가파우더를 체친다","흰자를 휘핑하며 설탕을 넣는다","가루를 섞는다","짤주머니로 원형으로 짠다","30분 말린다","150도 오븐에서 12분 굽는다","버터크림을 넣어 샌드한다"]}',
 ARRAY['baked','veggie','light']),

('western-077', 'seed',
 '{"ko":"푸딩","en":"Pudding","ja":"プリン","zh":"布丁"}',
 '{"ko":"부드러운 커스터드 푸딩","en":"Smooth custard pudding"}',
 60, 'easy', 4,
 '[{"name":"계란","quantity":"3개"},{"name":"우유","quantity":"300ml"},{"name":"설탕","quantity":"60g"},{"name":"바닐라 에센스","quantity":"약간"},{"name":"캐러멜용 설탕","quantity":"50g"}]',
 '{"ko":["설탕을 녹여 캐러멜을 만들어 틀에 붓는다","계란, 우유, 설탕, 바닐라를 섞는다","체에 거른다","틀에 붓는다","찜기에서 20분 찐다","냉장고에서 식힌다"]}',
 ARRAY['steamed','veggie','light']),

('western-078', 'seed',
 '{"ko":"초콜릿 무스","en":"Chocolate Mousse","ja":"チョコレートムース","zh":"巧克力慕斯"}',
 '{"ko":"가볍고 부드러운 초콜릿 무스","en":"Light and smooth chocolate mousse"}',
 30, 'medium', 4,
 '[{"name":"다크초콜릿","quantity":"200g"},{"name":"생크림","quantity":"300ml"},{"name":"계란","quantity":"3개"},{"name":"설탕","quantity":"50g"}]',
 '{"ko":["초콜릿을 녹인다","노른자를 넣어 섞는다","생크림을 휘핑한다","흰자를 휘핑하며 설탕을 넣는다","모두 부드럽게 섞는다","컵에 담아 냉장 보관한다"]}',
 ARRAY['veggie','heavy']),

('western-079', 'seed',
 '{"ko":"파운드 케이크","en":"Pound Cake","ja":"パウンドケーキ","zh":"磅蛋糕"}',
 '{"ko":"버터 향이 풍부한 파운드 케이크","en":"Pound cake rich in butter flavor"}',
 50, 'easy', 8,
 '[{"name":"버터","quantity":"150g"},{"name":"설탕","quantity":"150g"},{"name":"계란","quantity":"3개"},{"name":"밀가루","quantity":"150g"},{"name":"베이킹파우더","quantity":"1작은술"}]',
 '{"ko":["버터와 설탕을 크림화한다","계란을 하나씩 넣는다","밀가루와 베이킹파우더를 체쳐 넣는다","틀에 붓는다","170도 오븐에서 35분 굽는다","식혀서 자른다"]}',
 ARRAY['baked','veggie','heavy']),

('western-080', 'seed',
 '{"ko":"쿠키","en":"Cookies","ja":"クッキー","zh":"曲奇饼干"}',
 '{"ko":"바삭한 버터 쿠키","en":"Crispy butter cookies"}',
 30, 'easy', 30,
 '[{"name":"버터","quantity":"100g"},{"name":"설탕","quantity":"80g"},{"name":"계란","quantity":"1개"},{"name":"밀가루","quantity":"200g"},{"name":"바닐라 에센스","quantity":"약간"}]',
 '{"ko":["버터와 설탕을 크림화한다","계란을 넣는다","밀가루를 넣어 반죽한다","냉장고에서 30분 휴지시킨다","밀대로 밀어 모양을 낸다","170도 오븐에서 15분 굽는다"]}',
 ARRAY['baked','veggie','light']),

-- === 추가 파스타 & 면 요리 (Additional Pasta & Noodles) ===
('western-081', 'seed',
 '{"ko":"맥앤치즈","en":"Mac and Cheese","ja":"マカロニチーズ","zh":"芝士通心粉"}',
 '{"ko":"크림 치즈 소스의 마카로니","en":"Macaroni in creamy cheese sauce"}',
 25, 'easy', 3,
 '[{"name":"마카로니","quantity":"300g"},{"name":"체더치즈","quantity":"200g"},{"name":"우유","quantity":"400ml"},{"name":"밀가루","quantity":"3큰술"},{"name":"버터","quantity":"40g"},{"name":"빵가루","quantity":"50g"}]',
 '{"ko":["마카로니를 삶는다","버터에 밀가루를 볶는다","우유를 넣어 화이트 소스를 만든다","치즈를 넣어 녹인다","마카로니를 넣어 섞는다","빵가루를 뿌리고 오븐에서 굽는다"]}',
 ARRAY['pasta','veggie','heavy','baked']),

('western-082', 'seed',
 '{"ko":"파스타 프리마베라","en":"Pasta Primavera","ja":"パスタプリマヴェーラ","zh":"春季蔬菜意面"}',
 '{"ko":"다양한 채소가 들어간 봄 파스타","en":"Spring pasta with various vegetables"}',
 25, 'easy', 2,
 '[{"name":"펜네면","quantity":"200g"},{"name":"브로콜리","quantity":"100g"},{"name":"파프리카","quantity":"1개"},{"name":"호박","quantity":"100g"},{"name":"방울토마토","quantity":"10개"},{"name":"올리브오일","quantity":"3큰술"},{"name":"마늘","quantity":"3쪽"}]',
 '{"ko":["채소를 먹기 좋게 자른다","마늘을 올리브오일에 볶는다","채소를 넣고 볶는다","삶은 펜네를 넣는다","면수를 넣어 섞는다","파마산치즈를 뿌린다"]}',
 ARRAY['pasta','veggie','light']),

('western-083', 'seed',
 '{"ko":"크림 베이컨 파스타","en":"Cream Bacon Pasta","ja":"クリームベーコンパスタ","zh":"奶油培根意面"}',
 '{"ko":"베이컨과 크림 소스의 파스타","en":"Pasta with bacon and cream sauce"}',
 20, 'easy', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"베이컨","quantity":"100g"},{"name":"생크림","quantity":"200ml"},{"name":"양파","quantity":"1/2개"},{"name":"파마산치즈","quantity":"40g"},{"name":"파슬리","quantity":"약간"}]',
 '{"ko":["베이컨과 양파를 볶는다","생크림을 넣고 끓인다","삶은 면을 넣는다","치즈를 넣어 섞는다","파슬리를 뿌린다"]}',
 ARRAY['pasta','meat','heavy','quick']),

('western-084', 'seed',
 '{"ko":"푸타네스카","en":"Puttanesca","ja":"プッタネスカ","zh":"娼妓意面"}',
 '{"ko":"앤초비와 올리브로 만든 이탈리아 파스타","en":"Italian pasta with anchovies and olives"}',
 25, 'easy', 2,
 '[{"name":"스파게티면","quantity":"200g"},{"name":"토마토","quantity":"4개"},{"name":"앤초비","quantity":"6조각"},{"name":"올리브","quantity":"15개"},{"name":"케이퍼","quantity":"2큰술"},{"name":"마늘","quantity":"3쪽"},{"name":"페페론치노","quantity":"2개"}]',
 '{"ko":["마늘과 페페론치노를 올리브오일에 볶는다","앤초비를 넣어 으깬다","토마토를 넣고 끓인다","올리브와 케이퍼를 넣는다","삶은 면을 넣어 섞는다"]}',
 ARRAY['pasta','seafood','spicy']),

('western-085', 'seed',
 '{"ko":"스파게티 미트볼","en":"Spaghetti Meatballs","ja":"ミートボールスパゲッティ","zh":"肉丸意面"}',
 '{"ko":"미트볼이 올라간 토마토 스파게티","en":"Tomato spaghetti with meatballs"}',
 40, 'medium', 3,
 '[{"name":"스파게티면","quantity":"250g"},{"name":"소고기 간것","quantity":"300g"},{"name":"토마토소스","quantity":"400ml"},{"name":"양파","quantity":"1개"},{"name":"빵가루","quantity":"50g"},{"name":"계란","quantity":"1개"},{"name":"파마산치즈","quantity":"50g"}]',
 '{"ko":["소고기, 빵가루, 계란으로 미트볼을 만든다","미트볼을 굽는다","토마토소스를 끓인다","미트볼을 넣고 20분 끓인다","삶은 스파게티를 담고 미트볼과 소스를 올린다","치즈를 뿌린다"]}',
 ARRAY['pasta','meat','heavy']),

-- === 추가 샐러드 & 사이드 (Additional Salads & Sides) ===
('western-086', 'seed',
 '{"ko":"콜슬로","en":"Coleslaw","ja":"コールスロー","zh":"卷心菜沙拉"}',
 '{"ko":"양배추와 당근의 상큼한 샐러드","en":"Refreshing salad with cabbage and carrot"}',
 15, 'easy', 4,
 '[{"name":"양배추","quantity":"1/4통"},{"name":"당근","quantity":"1개"},{"name":"마요네즈","quantity":"4큰술"},{"name":"식초","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["양배추와 당근을 채썬다","마요네즈, 식초, 설탕, 소금을 섞는다","채소와 드레싱을 섞는다","냉장고에서 30분 숙성시킨다"]}',
 ARRAY['salad','veggie','light','quick']),

('western-087', 'seed',
 '{"ko":"감자 샐러드","en":"Potato Salad","ja":"ポテトサラダ","zh":"土豆沙拉"}',
 '{"ko":"부드러운 감자 샐러드","en":"Smooth potato salad"}',
 30, 'easy', 4,
 '[{"name":"감자","quantity":"4개"},{"name":"계란","quantity":"2개"},{"name":"오이","quantity":"1개"},{"name":"당근","quantity":"1개"},{"name":"마요네즈","quantity":"5큰술"},{"name":"소금","quantity":"약간"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["감자와 계란을 삶는다","감자를 으깬다","오이와 당근을 깍둑썰기한다","계란을 다진다","모든 재료를 마요네즈로 버무린다","소금, 후추로 간한다"]}',
 ARRAY['salad','veggie','heavy']),

('western-088', 'seed',
 '{"ko":"마카로니 샐러드","en":"Macaroni Salad","ja":"マカロニサラダ","zh":"通心粉沙拉"}',
 '{"ko":"마카로니와 채소의 샐러드","en":"Salad with macaroni and vegetables"}',
 25, 'easy', 4,
 '[{"name":"마카로니","quantity":"200g"},{"name":"햄","quantity":"100g"},{"name":"오이","quantity":"1개"},{"name":"양파","quantity":"1/2개"},{"name":"마요네즈","quantity":"5큰술"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["마카로니를 삶아 식힌다","햄, 오이, 양파를 깍둑썰기한다","모든 재료를 섞는다","마요네즈로 버무린다","소금으로 간한다"]}',
 ARRAY['salad','meat','heavy']),

('western-089', 'seed',
 '{"ko":"시금치 샐러드","en":"Spinach Salad","ja":"ほうれん草サラダ","zh":"菠菜沙拉"}',
 '{"ko":"베이컨과 계란이 들어간 시금치 샐러드","en":"Spinach salad with bacon and egg"}',
 20, 'easy', 2,
 '[{"name":"시금치","quantity":"200g"},{"name":"베이컨","quantity":"4장"},{"name":"계란","quantity":"2개"},{"name":"방울토마토","quantity":"10개"},{"name":"파마산치즈","quantity":"30g"},{"name":"발사믹 드레싱","quantity":"3큰술"}]',
 '{"ko":["시금치를 씻어 물기를 뺀다","베이컨을 바삭하게 굽는다","계란을 삶는다","시금치에 토마토, 베이컨, 계란을 올린다","드레싱을 뿌리고 치즈를 갈아 올린다"]}',
 ARRAY['salad','meat','light']),

('western-090', 'seed',
 '{"ko":"프렌치 프라이","en":"French Fries","ja":"フレンチフライ","zh":"炸薯条"}',
 '{"ko":"바삭한 감자튀김","en":"Crispy french fries"}',
 30, 'easy', 3,
 '[{"name":"감자","quantity":"4개"},{"name":"식용유","quantity":"적당량"},{"name":"소금","quantity":"적당량"}]',
 '{"ko":["감자를 막대 모양으로 썬다","찬물에 담가 전분을 빼고 물기를 뺀다","160도 기름에서 1차 튀김한다","180도로 올려 2차 튀김한다","키친타올에 기름을 빼고 소금을 뿌린다"]}',
 ARRAY['veggie','side_dish','quick']),

-- === 추가 메인 요리 (Additional Mains) ===
('western-091', 'seed',
 '{"ko":"바비큐 립","en":"BBQ Ribs","ja":"BBQリブ","zh":"烧烤排骨"}',
 '{"ko":"달콤한 바비큐 소스의 돼지 갈비","en":"Pork ribs with sweet BBQ sauce"}',
 150, 'medium', 3,
 '[{"name":"돼지 갈비","quantity":"1kg"},{"name":"바비큐 소스","quantity":"200ml"},{"name":"양파","quantity":"1개"},{"name":"마늘","quantity":"5쪽"},{"name":"꿀","quantity":"2큰술"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["갈비를 물에 삶아 잡내를 제거한다","양파와 마늘로 육수를 낸다","바비큐 소스, 꿀, 간장을 섞는다","갈비에 소스를 발라 재운다","180도 오븐에서 1시간 굽는다","중간중간 소스를 더 발라준다"]}',
 ARRAY['baked','meat','heavy']),

('western-092', 'seed',
 '{"ko":"로스트 치킨","en":"Roast Chicken","ja":"ローストチキン","zh":"烤鸡"}',
 '{"ko":"허브로 양념한 오븐 구이 통닭","en":"Whole chicken roasted with herbs"}',
 90, 'medium', 4,
 '[{"name":"통닭","quantity":"1마리"},{"name":"로즈마리","quantity":"3줄기"},{"name":"타임","quantity":"3줄기"},{"name":"레몬","quantity":"1개"},{"name":"마늘","quantity":"6쪽"},{"name":"올리브오일","quantity":"4큰술"},{"name":"소금","quantity":"적당량"},{"name":"후추","quantity":"적당량"}]',
 '{"ko":["닭을 씻어 물기를 뺀다","소금, 후추를 안팎으로 문지른다","뱃속에 레몬, 마늘, 허브를 넣는다","올리브오일을 바른다","200도 오븐에서 1시간 굽는다","15분 휴지시킨다"]}',
 ARRAY['baked','meat','heavy']),

('western-093', 'seed',
 '{"ko":"치킨 윙","en":"Chicken Wings","ja":"チキンウィング","zh":"鸡翅"}',
 '{"ko":"바삭한 프라이드 치킨 윙","en":"Crispy fried chicken wings"}',
 40, 'easy', 3,
 '[{"name":"닭날개","quantity":"500g"},{"name":"밀가루","quantity":"100g"},{"name":"감자전분","quantity":"50g"},{"name":"마늘가루","quantity":"1큰술"},{"name":"소금","quantity":"1작은술"},{"name":"후추","quantity":"1작은술"},{"name":"식용유","quantity":"적당량"}]',
 '{"ko":["닭날개에 소금, 후추로 밑간한다","밀가루, 전분, 마늘가루를 섞는다","닭날개에 가루를 묻힌다","170도 기름에서 10분 튀긴다","키친타올에 기름을 뺀다","소스를 발라낸다"]}',
 ARRAY['meat','heavy']),

('western-094', 'seed',
 '{"ko":"쉐퍼드 파이","en":"Shepherd''s Pie","ja":"シェパーズパイ","zh":"牧羊人派"}',
 '{"ko":"으깬 감자를 올린 영국식 고기 파이","en":"British meat pie topped with mashed potato"}',
 60, 'medium', 4,
 '[{"name":"양고기 간것","quantity":"500g"},{"name":"감자","quantity":"5개"},{"name":"양파","quantity":"2개"},{"name":"당근","quantity":"2개"},{"name":"우유","quantity":"100ml"},{"name":"버터","quantity":"50g"},{"name":"토마토 페이스트","quantity":"2큰술"}]',
 '{"ko":["양파와 당근을 다져 볶는다","양고기를 넣고 볶는다","토마토 페이스트를 넣는다","감자를 삶아 으깬다","우유와 버터를 넣어 매시를 만든다","그릇에 고기를 담고 매시를 올린다","200도 오븐에서 20분 굽는다"]}',
 ARRAY['baked','meat','heavy']),

('western-095', 'seed',
 '{"ko":"미트로프","en":"Meatloaf","ja":"ミートローフ","zh":"肉饼"}',
 '{"ko":"오븐에 구운 미국식 고기 요리","en":"American baked meat dish"}',
 70, 'easy', 5,
 '[{"name":"소고기 간것","quantity":"500g"},{"name":"양파","quantity":"1개"},{"name":"빵가루","quantity":"100g"},{"name":"계란","quantity":"2개"},{"name":"케첩","quantity":"100ml"},{"name":"우스터소스","quantity":"2큰술"}]',
 '{"ko":["양파를 다져 볶는다","소고기, 양파, 빵가루, 계란을 섞는다","틀에 넣어 모양을 잡는다","케첩과 우스터소스를 섞어 바른다","180도 오븈에서 50분 굽는다","10분 휴지시킨 후 썬다"]}',
 ARRAY['baked','meat','heavy']),

-- === 추가 수프 & 스튜 (Additional Soups & Stews) ===
('western-096', 'seed',
 '{"ko":"치킨 누들 수프","en":"Chicken Noodle Soup","ja":"チキンヌードルスープ","zh":"鸡肉面汤"}',
 '{"ko":"면이 들어간 담백한 치킨 수프","en":"Light chicken soup with noodles"}',
 35, 'easy', 4,
 '[{"name":"닭가슴살","quantity":"200g"},{"name":"당근","quantity":"1개"},{"name":"셀러리","quantity":"2줄기"},{"name":"양파","quantity":"1개"},{"name":"면","quantity":"100g"},{"name":"닭 육수","quantity":"1L"}]',
 '{"ko":["닭고기를 육수에 넣고 끓인다","채소를 깍둑썰기한다","닭고기가 익으면 건져서 찢는다","채소를 넣고 끓인다","면을 넣는다","닭고기를 다시 넣는다"]}',
 ARRAY['soupy','meat','light','noodle']),

('western-097', 'seed',
 '{"ko":"비스크","en":"Bisque","ja":"ビスク","zh":"浓汤"}',
 '{"ko":"새우로 만든 진한 크림 수프","en":"Rich cream soup made with shrimp"}',
 45, 'medium', 3,
 '[{"name":"새우","quantity":"300g"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1개"},{"name":"셀러리","quantity":"1줄기"},{"name":"생크림","quantity":"200ml"},{"name":"토마토 페이스트","quantity":"2큰술"},{"name":"브랜디","quantity":"50ml"}]',
 '{"ko":["새우를 손질하고 껍질을 따로 모은다","껍질로 육수를 낸다","채소를 볶는다","새우를 넣고 브랜디를 플랑베한다","토마토 페이스트와 육수를 넣는다","믹서로 곱게 간다","생크림을 넣어 마무리한다"]}',
 ARRAY['soupy','seafood','heavy']),

('western-098', 'seed',
 '{"ko":"가스파초","en":"Gazpacho","ja":"ガスパチョ","zh":"西班牙冷汤"}',
 '{"ko":"차갑게 먹는 스페인 토마토 수프","en":"Spanish cold tomato soup"}',
 15, 'easy', 3,
 '[{"name":"토마토","quantity":"6개"},{"name":"오이","quantity":"1개"},{"name":"피망","quantity":"1개"},{"name":"양파","quantity":"1/2개"},{"name":"마늘","quantity":"2쪽"},{"name":"올리브오일","quantity":"3큰술"},{"name":"식초","quantity":"2큰술"}]',
 '{"ko":["모든 채소를 자른다","믹서에 넣고 간다","올리브오일과 식초를 넣는다","소금, 후추로 간한다","냉장고에서 2시간 차게 식힌다","차갑게 서빙한다"]}',
 ARRAY['soupy','veggie','light','quick']),

('western-099', 'seed',
 '{"ko":"보르시","en":"Borscht","ja":"ボルシチ","zh":"罗宋汤"}',
 '{"ko":"비트로 만든 러시아 전통 수프","en":"Traditional Russian soup made with beets"}',
 60, 'medium', 5,
 '[{"name":"비트","quantity":"2개"},{"name":"양배추","quantity":"1/4통"},{"name":"소고기","quantity":"300g"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"토마토 페이스트","quantity":"2큰술"},{"name":"사워크림","quantity":"100ml"}]',
 '{"ko":["소고기를 육수에 넣고 끓인다","비트, 채소를 썬다","양파와 당근을 볶는다","비트와 토마토 페이스트를 넣는다","육수에 모든 재료를 넣고 40분 끓인다","사워크림을 올려 낸다"]}',
 ARRAY['soupy','meat','heavy']),

('western-100', 'seed',
 '{"ko":"치킨 토르티야 수프","en":"Chicken Tortilla Soup","ja":"チキントルティーヤスープ","zh":"墨西哥鸡肉汤"}',
 '{"ko":"토르티야 칩이 들어간 멕시칸 치킨 수프","en":"Mexican chicken soup with tortilla chips"}',
 35, 'easy', 4,
 '[{"name":"닭가슴살","quantity":"200g"},{"name":"토마토","quantity":"3개"},{"name":"양파","quantity":"1개"},{"name":"옥수수","quantity":"100g"},{"name":"검은콩","quantity":"100g"},{"name":"토르티야 칩","quantity":"100g"},{"name":"치즈","quantity":"50g"},{"name":"라임","quantity":"1개"}]',
 '{"ko":["닭고기를 육수에 넣고 끓인다","토마토, 양파를 다져 넣는다","옥수수와 콩을 넣는다","20분 끓인다","그릇에 담고 토르티야 칩을 올린다","치즈와 라임을 올린다"]}',
 ARRAY['soupy','meat','heavy']);
