-- Fridge Mate 레시피 시드 데이터 (100개 한식 레시피)
-- Supabase SQL Editor에서 실행하세요
-- tags: spicy, mild, soupy, stir_fry, grilled, steamed, raw, meat, seafood, veggie, heavy, light, quick, noodle, rice, side_dish

-- 기존 시드 데이터 중복 방지
DELETE FROM public.recipes WHERE source = 'seed';

INSERT INTO public.recipes (external_id, source, title, description, cooking_time, difficulty, servings, ingredients, instructions, tags) VALUES

-- === 찌개/국 (Stews & Soups) ===
('seed-001', 'seed',
 '{"ko":"김치찌개","en":"Kimchi Stew","ja":"キムチチゲ","zh":"泡菜汤"}',
 '{"ko":"돼지고기와 김치로 만드는 한국 전통 찌개","en":"Traditional Korean stew with pork and kimchi"}',
 30, 'easy', 2,
 '[{"name":"김치","quantity":"200g"},{"name":"돼지고기","quantity":"150g"},{"name":"두부","quantity":"1모"},{"name":"대파","quantity":"1대"},{"name":"고춧가루","quantity":"1큰술"}]',
 '{"ko":["돼지고기를 먹기 좋은 크기로 썬다","냄비에 기름을 두르고 돼지고기를 볶는다","김치를 넣고 함께 볶는다","물을 붓고 끓인다","두부를 넣고 5분 더 끓인다","대파를 썰어 올린다"]}',
 ARRAY['spicy','soupy','meat','heavy']),

('seed-002', 'seed',
 '{"ko":"된장찌개","en":"Soybean Paste Stew","ja":"味噌チゲ","zh":"大酱汤"}',
 '{"ko":"구수한 된장으로 만든 건강한 찌개","en":"Healthy stew made with savory soybean paste"}',
 25, 'easy', 2,
 '[{"name":"된장","quantity":"2큰술"},{"name":"두부","quantity":"1모"},{"name":"호박","quantity":"100g"},{"name":"감자","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["감자와 호박을 썬다","냄비에 물을 붓고 된장을 풀어준다","감자를 먼저 넣고 끓인다","호박, 양파, 두부를 넣는다","대파를 올린다"]}',
 ARRAY['mild','soupy','veggie','light']),

('seed-003', 'seed',
 '{"ko":"순두부찌개","en":"Soft Tofu Stew","ja":"スンドゥブチゲ","zh":"嫩豆腐汤"}',
 '{"ko":"부드러운 순두부로 만든 얼큰한 찌개","en":"Spicy stew with soft tofu"}',
 20, 'easy', 1,
 '[{"name":"순두부","quantity":"1팩"},{"name":"계란","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"고춧가루","quantity":"1큰술"},{"name":"새우","quantity":"50g"}]',
 '{"ko":["냄비에 참기름을 두르고 고춧가루를 볶는다","물을 붓고 끓인다","순두부를 넣고 끓인다","새우를 넣는다","계란을 깨 넣는다","대파를 올린다"]}',
 ARRAY['spicy','soupy','seafood','light','quick']),

('seed-004', 'seed',
 '{"ko":"부대찌개","en":"Army Stew","ja":"プデチゲ","zh":"部队锅"}',
 '{"ko":"라면, 소시지, 햄이 들어간 얼큰한 찌개","en":"Spicy stew with ramen, sausage and ham"}',
 25, 'easy', 3,
 '[{"name":"라면","quantity":"1개"},{"name":"소시지","quantity":"4개"},{"name":"햄","quantity":"100g"},{"name":"김치","quantity":"100g"},{"name":"두부","quantity":"1/2모"},{"name":"떡","quantity":"100g"}]',
 '{"ko":["냄비에 재료를 보기 좋게 담는다","고추장, 고춧가루로 양념장을 만든다","양념장을 넣고 물을 부어 끓인다","라면을 넣고 3분 끓인다"]}',
 ARRAY['spicy','soupy','meat','heavy']),

('seed-005', 'seed',
 '{"ko":"미역국","en":"Seaweed Soup","ja":"ワカメスープ","zh":"海带汤"}',
 '{"ko":"생일에 먹는 고소한 미역국","en":"Savory seaweed soup traditionally eaten on birthdays"}',
 30, 'easy', 2,
 '[{"name":"미역","quantity":"30g"},{"name":"소고기","quantity":"100g"},{"name":"참기름","quantity":"1큰술"},{"name":"간장","quantity":"1큰술"},{"name":"다진마늘","quantity":"1큰술"}]',
 '{"ko":["미역을 물에 불린다","소고기를 참기름에 볶는다","미역을 넣고 함께 볶는다","물을 붓고 끓인다","간장으로 간을 한다"]}',
 ARRAY['mild','soupy','meat','light']),

('seed-006', 'seed',
 '{"ko":"떡국","en":"Rice Cake Soup","ja":"トック","zh":"年糕汤"}',
 '{"ko":"설날에 먹는 전통 떡국","en":"Traditional rice cake soup eaten on New Year"}',
 30, 'easy', 2,
 '[{"name":"떡국떡","quantity":"300g"},{"name":"소고기","quantity":"100g"},{"name":"계란","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["소고기를 삶아 육수를 만든다","떡국떡을 넣고 끓인다","간장으로 간을 한다","계란을 풀어 넣는다","대파를 올린다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('seed-007', 'seed',
 '{"ko":"감자탕","en":"Pork Bone Soup","ja":"カムジャタン","zh":"猪骨汤"}',
 '{"ko":"뼈해장국으로도 불리는 얼큰한 감자탕","en":"Spicy pork bone soup with potatoes"}',
 60, 'medium', 4,
 '[{"name":"돼지등뼈","quantity":"1kg"},{"name":"감자","quantity":"3개"},{"name":"배추","quantity":"3잎"},{"name":"대파","quantity":"2대"},{"name":"들깨가루","quantity":"3큰술"}]',
 '{"ko":["돼지등뼈를 삶아 핏물을 빼고 씻는다","냄비에 뼈와 물을 넣고 1시간 끓인다","감자, 배추를 넣는다","양념장을 넣고 끓인다","들깨가루를 넣고 마무리한다"]}',
 ARRAY['spicy','soupy','meat','heavy']),

('seed-008', 'seed',
 '{"ko":"육개장","en":"Spicy Beef Soup","ja":"ユッケジャン","zh":"辣牛肉汤"}',
 '{"ko":"소고기와 야채가 듬뿍 들어간 얼큰한 국","en":"Spicy beef soup with vegetables"}',
 50, 'medium', 3,
 '[{"name":"소고기","quantity":"300g"},{"name":"숙주","quantity":"100g"},{"name":"고사리","quantity":"100g"},{"name":"대파","quantity":"2대"},{"name":"고춧가루","quantity":"3큰술"}]',
 '{"ko":["소고기를 삶아 찢는다","육수에 고춧가루 양념을 넣는다","야채를 넣고 끓인다","대파를 넣고 마무리한다"]}',
 ARRAY['spicy','soupy','meat','heavy']),

('seed-009', 'seed',
 '{"ko":"콩나물국","en":"Bean Sprout Soup","ja":"もやしスープ","zh":"豆芽汤"}',
 '{"ko":"시원하고 깔끔한 콩나물국","en":"Clean and refreshing bean sprout soup"}',
 15, 'easy', 2,
 '[{"name":"콩나물","quantity":"200g"},{"name":"대파","quantity":"1대"},{"name":"다진마늘","quantity":"1큰술"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["냄비에 물을 끓인다","콩나물을 넣고 뚜껑을 덮고 끓인다","다진마늘을 넣는다","소금으로 간을 한다","대파를 올린다"]}',
 ARRAY['mild','soupy','veggie','light','quick']),

('seed-010', 'seed',
 '{"ko":"닭곰탕","en":"Chicken Gomtang","ja":"鶏コムタン","zh":"鸡汤"}',
 '{"ko":"담백하고 진한 닭 육수 곰탕","en":"Rich and clean chicken broth soup"}',
 60, 'easy', 2,
 '[{"name":"닭","quantity":"1마리"},{"name":"대파","quantity":"2대"},{"name":"마늘","quantity":"5쪽"},{"name":"소금","quantity":"약간"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["닭을 깨끗이 씻는다","냄비에 닭, 대파, 마늘을 넣고 물을 부어 끓인다","1시간 푹 끓인다","닭을 건져 살을 발라낸다","소금, 후추로 간을 한다"]}',
 ARRAY['mild','soupy','meat','light']),

-- === 볶음/구이 (Stir-fry & Grilled) ===
('seed-011', 'seed',
 '{"ko":"제육볶음","en":"Spicy Stir-fried Pork","ja":"豚肉の辛炒め","zh":"辣炒猪肉"}',
 '{"ko":"매콤하게 볶은 돼지고기 요리","en":"Spicy stir-fried pork with vegetables"}',
 20, 'easy', 2,
 '[{"name":"돼지고기","quantity":"300g"},{"name":"양파","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"고추장","quantity":"2큰술"},{"name":"고춧가루","quantity":"1큰술"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["돼지고기를 썬다","양념장을 만든다","돼지고기에 양념을 넣고 재운다","양파, 대파를 썬다","팬에 볶는다"]}',
 ARRAY['spicy','stir_fry','meat','heavy','quick']),

('seed-012', 'seed',
 '{"ko":"불고기","en":"Bulgogi","ja":"プルコギ","zh":"烤肉"}',
 '{"ko":"달콤한 양념에 재운 한국식 불고기","en":"Korean-style marinated beef"}',
 40, 'medium', 3,
 '[{"name":"소고기","quantity":"300g"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"3큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["소고기를 얇게 썬다","양념장을 만든다","소고기를 30분 재운다","야채와 함께 볶는다"]}',
 ARRAY['mild','stir_fry','meat','heavy']),

('seed-013', 'seed',
 '{"ko":"닭갈비","en":"Spicy Chicken Stir-fry","ja":"タッカルビ","zh":"辣炒鸡排"}',
 '{"ko":"매콤한 양념에 볶은 닭고기와 야채","en":"Spicy stir-fried chicken with vegetables"}',
 30, 'easy', 2,
 '[{"name":"닭가슴살","quantity":"300g"},{"name":"양배추","quantity":"200g"},{"name":"고구마","quantity":"1개"},{"name":"떡","quantity":"100g"},{"name":"고추장","quantity":"3큰술"}]',
 '{"ko":["닭고기를 양념에 재운다","양배추, 고구마를 썬다","팬에 닭고기를 먼저 볶는다","야채와 떡을 넣고 볶는다"]}',
 ARRAY['spicy','stir_fry','meat','heavy']),

('seed-014', 'seed',
 '{"ko":"오징어볶음","en":"Stir-fried Squid","ja":"イカ炒め","zh":"炒鱿鱼"}',
 '{"ko":"매콤하게 볶은 오징어와 야채","en":"Spicy stir-fried squid with vegetables"}',
 20, 'easy', 2,
 '[{"name":"오징어","quantity":"2마리"},{"name":"양파","quantity":"1개"},{"name":"양배추","quantity":"100g"},{"name":"당근","quantity":"1/2개"},{"name":"고추장","quantity":"2큰술"}]',
 '{"ko":["오징어를 손질하고 칼집을 넣는다","야채를 썬다","양념장을 만든다","팬에 오징어와 야채를 볶는다"]}',
 ARRAY['spicy','stir_fry','seafood','light','quick']),

('seed-015', 'seed',
 '{"ko":"삼겹살구이","en":"Grilled Pork Belly","ja":"サムギョプサル","zh":"烤五花肉"}',
 '{"ko":"두툼하게 썬 삼겹살 구이","en":"Grilled thick-cut pork belly"}',
 20, 'easy', 2,
 '[{"name":"삼겹살","quantity":"400g"},{"name":"상추","quantity":"10장"},{"name":"마늘","quantity":"5쪽"},{"name":"쌈장","quantity":"3큰술"},{"name":"고추","quantity":"3개"}]',
 '{"ko":["삼겹살을 두툼하게 썬다","팬을 달구고 삼겹살을 굽는다","마늘도 함께 굽는다","상추에 쌈장, 고기를 싸서 먹는다"]}',
 ARRAY['mild','grilled','meat','heavy','quick']),

('seed-016', 'seed',
 '{"ko":"계란볶음밥","en":"Egg Fried Rice","ja":"卵チャーハン","zh":"蛋炒饭"}',
 '{"ko":"간단하고 맛있는 계란볶음밥","en":"Simple and delicious egg fried rice"}',
 15, 'easy', 1,
 '[{"name":"밥","quantity":"2공기"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"당근","quantity":"50g"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["계란을 스크램블한다","야채를 잘게 썬다","팬에 야채를 볶는다","밥을 넣고 볶는다","간장으로 간을 한다","계란을 넣고 섞는다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick','rice']),

('seed-017', 'seed',
 '{"ko":"김치볶음밥","en":"Kimchi Fried Rice","ja":"キムチチャーハン","zh":"泡菜炒饭"}',
 '{"ko":"김치와 돼지고기로 만든 볶음밥","en":"Fried rice with kimchi and pork"}',
 15, 'easy', 1,
 '[{"name":"밥","quantity":"2공기"},{"name":"김치","quantity":"150g"},{"name":"돼지고기","quantity":"100g"},{"name":"계란","quantity":"1개"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["김치를 잘게 썬다","돼지고기를 볶는다","김치를 넣고 볶는다","밥을 넣고 볶는다","계란 후라이를 올린다"]}',
 ARRAY['spicy','stir_fry','meat','light','quick','rice']),

('seed-018', 'seed',
 '{"ko":"비빔밥","en":"Bibimbap","ja":"ビビンバ","zh":"拌饭"}',
 '{"ko":"다양한 나물과 고추장으로 비벼 먹는 비빔밥","en":"Mixed rice with vegetables and gochujang"}',
 35, 'medium', 1,
 '[{"name":"밥","quantity":"1공기"},{"name":"시금치","quantity":"100g"},{"name":"당근","quantity":"1개"},{"name":"계란","quantity":"1개"},{"name":"소고기","quantity":"100g"},{"name":"고추장","quantity":"2큰술"}]',
 '{"ko":["시금치를 데쳐 나물을 만든다","당근을 볶는다","소고기를 양념해 볶는다","계란 후라이를 만든다","밥 위에 재료를 올린다","고추장을 넣고 비빈다"]}',
 ARRAY['spicy','stir_fry','meat','heavy','rice']),

('seed-019', 'seed',
 '{"ko":"두부김치","en":"Tofu with Stir-fried Kimchi","ja":"豆腐キムチ","zh":"豆腐泡菜"}',
 '{"ko":"볶은 김치와 데운 두부의 조합","en":"Tofu served with stir-fried kimchi and pork"}',
 15, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"김치","quantity":"200g"},{"name":"돼지고기","quantity":"150g"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["두부를 끓는 물에 데운다","돼지고기를 볶는다","김치를 넣고 볶는다","두부를 썰어 접시에 담고 김치볶음을 올린다"]}',
 ARRAY['spicy','stir_fry','meat','light','quick']),

('seed-020', 'seed',
 '{"ko":"소불고기덮밥","en":"Bulgogi Rice Bowl","ja":"プルコギ丼","zh":"烤肉盖饭"}',
 '{"ko":"달콤한 불고기를 밥 위에 올린 덮밥","en":"Sweet bulgogi served over rice"}',
 30, 'easy', 1,
 '[{"name":"소고기","quantity":"200g"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1/2개"},{"name":"밥","quantity":"1공기"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["소고기를 양념에 재운다","야채를 썬다","팬에 볶는다","밥 위에 올린다"]}',
 ARRAY['mild','stir_fry','meat','heavy','quick','rice']),

-- === 면/만두 (Noodles & Dumplings) ===
('seed-021', 'seed',
 '{"ko":"잔치국수","en":"Banquet Noodles","ja":"チャンチグクス","zh":"宴会面"}',
 '{"ko":"멸치 육수에 삶은 소면을 말아먹는 잔치국수","en":"Noodles in anchovy broth"}',
 20, 'easy', 2,
 '[{"name":"소면","quantity":"200g"},{"name":"멸치","quantity":"30g"},{"name":"호박","quantity":"1/2개"},{"name":"계란","quantity":"1개"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["멸치로 육수를 낸다","소면을 삶아 찬물에 헹군다","호박을 채 썰어 볶는다","그릇에 국수를 담고 육수를 붓는다","고명을 올린다"]}',
 ARRAY['mild','soupy','veggie','light','quick','noodle']),

('seed-022', 'seed',
 '{"ko":"비빔국수","en":"Spicy Mixed Noodles","ja":"ビビン麺","zh":"拌面"}',
 '{"ko":"새콤매콤한 양념에 비벼 먹는 국수","en":"Cold noodles mixed with spicy-sweet sauce"}',
 15, 'easy', 1,
 '[{"name":"소면","quantity":"150g"},{"name":"오이","quantity":"1/2개"},{"name":"계란","quantity":"1개"},{"name":"고추장","quantity":"2큰술"},{"name":"식초","quantity":"1큰술"}]',
 '{"ko":["소면을 삶아 찬물에 헹군다","양념장을 만든다","오이를 채 썬다","국수에 양념장을 넣고 비빈다","계란을 올린다"]}',
 ARRAY['spicy','stir_fry','veggie','light','quick','noodle']),

('seed-023', 'seed',
 '{"ko":"칼국수","en":"Knife-cut Noodle Soup","ja":"カルグクス","zh":"刀削面"}',
 '{"ko":"손으로 직접 뽑은 면을 넣은 칼국수","en":"Hand-cut noodle soup"}',
 40, 'medium', 2,
 '[{"name":"밀가루","quantity":"200g"},{"name":"호박","quantity":"1/2개"},{"name":"감자","quantity":"1개"},{"name":"멸치","quantity":"30g"},{"name":"양파","quantity":"1개"}]',
 '{"ko":["밀가루를 반죽하고 숙성시킨다","멸치로 육수를 낸다","반죽을 밀어 면을 썬다","육수에 감자를 넣고 끓인다","면과 호박을 넣고 끓인다"]}',
 ARRAY['mild','soupy','veggie','heavy','noodle']),

('seed-024', 'seed',
 '{"ko":"떡볶이","en":"Spicy Rice Cakes","ja":"トッポッキ","zh":"辣炒年糕"}',
 '{"ko":"고추장 양념에 볶은 매콤한 떡볶이","en":"Spicy stir-fried rice cakes"}',
 20, 'easy', 2,
 '[{"name":"떡볶이떡","quantity":"300g"},{"name":"어묵","quantity":"100g"},{"name":"대파","quantity":"1대"},{"name":"고추장","quantity":"3큰술"},{"name":"고춧가루","quantity":"1큰술"}]',
 '{"ko":["물에 고추장, 고춧가루, 간장을 넣어 끓인다","떡과 어묵을 넣는다","양념이 졸아들 때까지 끓인다","대파를 넣고 마무리한다"]}',
 ARRAY['spicy','stir_fry','veggie','heavy','quick']),

('seed-025', 'seed',
 '{"ko":"라볶이","en":"Ramen Tteokbokki","ja":"ラポッキ","zh":"拉面炒年糕"}',
 '{"ko":"라면과 떡볶이를 합친 라볶이","en":"Ramen noodles with spicy rice cakes"}',
 20, 'easy', 2,
 '[{"name":"라면","quantity":"1개"},{"name":"떡볶이떡","quantity":"200g"},{"name":"어묵","quantity":"50g"},{"name":"고추장","quantity":"2큰술"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["물에 양념을 넣어 끓인다","떡과 어묵을 넣는다","라면을 넣고 끓인다","대파를 넣고 마무리한다"]}',
 ARRAY['spicy','soupy','veggie','heavy','quick','noodle']),

('seed-026', 'seed',
 '{"ko":"잡채","en":"Japchae","ja":"チャプチェ","zh":"杂菜"}',
 '{"ko":"당면과 야채를 볶은 한국 전통 요리","en":"Stir-fried glass noodles with vegetables"}',
 30, 'medium', 3,
 '[{"name":"당면","quantity":"200g"},{"name":"시금치","quantity":"100g"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"소고기","quantity":"100g"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["당면을 삶는다","야채를 각각 볶는다","소고기를 양념해 볶는다","모든 재료를 섞고 양념한다"]}',
 ARRAY['mild','stir_fry','meat','light','noodle']),

('seed-027', 'seed',
 '{"ko":"만두","en":"Korean Dumplings","ja":"マンドゥ","zh":"饺子"}',
 '{"ko":"고기와 야채를 넣은 한국식 만두","en":"Korean dumplings filled with meat and vegetables"}',
 50, 'medium', 4,
 '[{"name":"만두피","quantity":"30장"},{"name":"돼지고기","quantity":"200g"},{"name":"두부","quantity":"1/2모"},{"name":"김치","quantity":"100g"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["소를 만든다 (고기, 두부, 김치, 야채 섞기)","만두피에 소를 넣고 빚는다","찜기에 쪄낸다 또는 끓는 물에 삶는다"]}',
 ARRAY['mild','steamed','meat','heavy']),

('seed-028', 'seed',
 '{"ko":"수제비","en":"Hand-torn Noodle Soup","ja":"スジェビ","zh":"面疙瘩汤"}',
 '{"ko":"손으로 뜯어 넣은 밀가루 수제비","en":"Hand-torn flour noodle soup"}',
 30, 'easy', 2,
 '[{"name":"밀가루","quantity":"150g"},{"name":"감자","quantity":"1개"},{"name":"호박","quantity":"1/2개"},{"name":"양파","quantity":"1개"},{"name":"멸치","quantity":"20g"}]',
 '{"ko":["밀가루를 반죽한다","멸치로 육수를 낸다","감자를 넣고 끓인다","반죽을 손으로 뜯어 넣는다","호박을 넣고 끓인다"]}',
 ARRAY['mild','soupy','veggie','heavy','noodle']),

('seed-029', 'seed',
 '{"ko":"짜장면(짜장소스)","en":"Jajangmyeon","ja":"ジャージャー麺","zh":"炸酱面"}',
 '{"ko":"춘장 소스로 만든 한국식 짜장면","en":"Korean-style black bean noodles"}',
 30, 'medium', 2,
 '[{"name":"중면","quantity":"200g"},{"name":"춘장","quantity":"3큰술"},{"name":"돼지고기","quantity":"150g"},{"name":"양파","quantity":"1개"},{"name":"호박","quantity":"1/2개"},{"name":"감자","quantity":"1개"}]',
 '{"ko":["야채를 깍둑썰기한다","돼지고기를 볶는다","춘장을 넣고 볶는다","야채와 물을 넣고 끓인다","면을 삶아 소스를 올린다"]}',
 ARRAY['mild','stir_fry','meat','heavy','noodle']),

('seed-030', 'seed',
 '{"ko":"냉면","en":"Cold Noodles","ja":"冷麺","zh":"冷面"}',
 '{"ko":"시원한 육수에 말아먹는 물냉면","en":"Cold buckwheat noodles in chilled broth"}',
 30, 'medium', 1,
 '[{"name":"냉면","quantity":"1인분"},{"name":"소고기","quantity":"100g"},{"name":"오이","quantity":"1/2개"},{"name":"삶은계란","quantity":"1개"},{"name":"식초","quantity":"1큰술"},{"name":"겨자","quantity":"약간"}]',
 '{"ko":["소고기를 삶아 육수를 만들고 차갑게 식힌다","냉면을 삶아 찬물에 헹군다","그릇에 면을 담고 육수를 붓는다","오이, 계란, 고기를 올린다"]}',
 ARRAY['mild','soupy','meat','light','noodle']),

-- === 밥류 (Rice dishes) ===
('seed-031', 'seed',
 '{"ko":"돌솥비빔밥","en":"Stone Pot Bibimbap","ja":"石焼ビビンバ","zh":"石锅拌饭"}',
 '{"ko":"돌솥에 담아 누룽지가 생기는 비빔밥","en":"Bibimbap in hot stone pot with crispy rice"}',
 40, 'medium', 1,
 '[{"name":"밥","quantity":"1공기"},{"name":"시금치","quantity":"50g"},{"name":"콩나물","quantity":"50g"},{"name":"당근","quantity":"1/2개"},{"name":"계란","quantity":"1개"},{"name":"고추장","quantity":"2큰술"}]',
 '{"ko":["나물을 각각 준비한다","돌솥에 참기름을 바르고 밥을 넣는다","나물을 올린다","계란을 올려 불에 올린다","누룽지가 생기면 비벼 먹는다"]}',
 ARRAY['spicy','stir_fry','veggie','heavy','rice']),

('seed-032', 'seed',
 '{"ko":"참치마요덮밥","en":"Tuna Mayo Rice Bowl","ja":"ツナマヨ丼","zh":"金枪鱼蛋黄酱盖饭"}',
 '{"ko":"참치캔과 마요네즈로 만드는 간단한 덮밥","en":"Simple rice bowl with canned tuna and mayo"}',
 10, 'easy', 1,
 '[{"name":"참치캔","quantity":"1캔"},{"name":"마요네즈","quantity":"2큰술"},{"name":"밥","quantity":"1공기"},{"name":"김","quantity":"약간"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["참치를 기름을 빼고 마요네즈와 섞는다","밥 위에 올린다","김을 뿌린다","간장을 뿌린다"]}',
 ARRAY['mild','raw','seafood','light','quick','rice']),

('seed-033', 'seed',
 '{"ko":"카레라이스","en":"Curry Rice","ja":"カレーライス","zh":"咖喱饭"}',
 '{"ko":"감자, 당근, 고기가 들어간 카레라이스","en":"Japanese-Korean style curry with vegetables"}',
 40, 'easy', 3,
 '[{"name":"카레가루","quantity":"1팩"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"돼지고기","quantity":"200g"}]',
 '{"ko":["야채와 고기를 깍둑썰기한다","팬에 볶는다","물을 넣고 끓인다","카레가루를 넣고 걸쭉해질 때까지 끓인다","밥에 곁들인다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('seed-034', 'seed',
 '{"ko":"오므라이스","en":"Omurice","ja":"オムライス","zh":"蛋包饭"}',
 '{"ko":"케첩볶음밥을 계란으로 감싼 오므라이스","en":"Omelette-wrapped ketchup fried rice"}',
 20, 'easy', 1,
 '[{"name":"밥","quantity":"1공기"},{"name":"계란","quantity":"3개"},{"name":"양파","quantity":"1/2개"},{"name":"햄","quantity":"50g"},{"name":"케첩","quantity":"3큰술"}]',
 '{"ko":["양파와 햄을 잘게 썬다","볶다가 밥과 케첩을 넣는다","계란을 풀어 얇게 펴서 익힌다","볶음밥을 계란 위에 올리고 감싼다"]}',
 ARRAY['mild','stir_fry','meat','light','quick','rice']),

('seed-035', 'seed',
 '{"ko":"주먹밥","en":"Rice Balls","ja":"おにぎり","zh":"饭团"}',
 '{"ko":"참치, 김치 등 다양한 속재료의 주먹밥","en":"Rice balls with various fillings"}',
 15, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"참치캔","quantity":"1/2캔"},{"name":"김","quantity":"3장"},{"name":"마요네즈","quantity":"1큰술"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["밥에 소금과 참기름을 넣는다","속재료를 준비한다","랩에 밥을 올리고 속재료를 넣어 동그랗게 만든다","김으로 감싼다"]}',
 ARRAY['mild','raw','seafood','light','quick','rice']),

('seed-036', 'seed',
 '{"ko":"볶음밥","en":"Fried Rice","ja":"チャーハン","zh":"炒饭"}',
 '{"ko":"새우와 야채가 들어간 볶음밥","en":"Fried rice with shrimp and vegetables"}',
 15, 'easy', 1,
 '[{"name":"밥","quantity":"2공기"},{"name":"새우","quantity":"100g"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["새우를 손질한다","계란을 스크램블한다","팬에 새우를 볶는다","밥을 넣고 볶는다","간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','seafood','light','quick','rice']),

-- === 찜/조림 (Braised & Steamed) ===
('seed-037', 'seed',
 '{"ko":"닭볶음탕","en":"Braised Spicy Chicken","ja":"鶏肉の辛煮込み","zh":"辣炖鸡"}',
 '{"ko":"매콤하게 조린 닭고기 요리","en":"Spicy braised chicken with vegetables"}',
 40, 'medium', 3,
 '[{"name":"닭고기","quantity":"500g"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"고추장","quantity":"2큰술"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["닭고기를 데친다","야채를 큼직하게 썬다","양념장을 만든다","냄비에 닭, 야채, 양념장을 넣고 끓인다"]}',
 ARRAY['spicy','soupy','meat','heavy']),

('seed-038', 'seed',
 '{"ko":"고등어조림","en":"Braised Mackerel","ja":"サバの煮付け","zh":"炖鲭鱼"}',
 '{"ko":"무와 함께 조린 고등어 요리","en":"Mackerel braised with radish"}',
 30, 'medium', 2,
 '[{"name":"고등어","quantity":"1마리"},{"name":"무","quantity":"200g"},{"name":"대파","quantity":"1대"},{"name":"고춧가루","quantity":"1큰술"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["고등어를 손질한다","무를 1cm 두께로 썬다","양념장을 만든다","냄비에 무를 깔고 고등어를 올린다","양념장을 붓고 끓인다"]}',
 ARRAY['spicy','soupy','seafood','heavy']),

('seed-039', 'seed',
 '{"ko":"갈비찜","en":"Braised Short Ribs","ja":"カルビチム","zh":"炖排骨"}',
 '{"ko":"소갈비를 달콤하게 조린 갈비찜","en":"Sweet braised beef short ribs"}',
 90, 'hard', 4,
 '[{"name":"소갈비","quantity":"1kg"},{"name":"무","quantity":"200g"},{"name":"당근","quantity":"1개"},{"name":"밤","quantity":"5개"},{"name":"간장","quantity":"5큰술"},{"name":"설탕","quantity":"2큰술"}]',
 '{"ko":["갈비를 찬물에 담가 핏물을 뺀다","삶아서 기름을 제거한다","양념장을 만든다","갈비와 야채에 양념장을 넣고 조린다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('seed-040', 'seed',
 '{"ko":"찜닭","en":"Braised Soy Sauce Chicken","ja":"チムタク","zh":"酱鸡"}',
 '{"ko":"간장 양념에 조린 닭과 당면","en":"Chicken braised in soy sauce with glass noodles"}',
 40, 'medium', 3,
 '[{"name":"닭고기","quantity":"500g"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"당면","quantity":"100g"},{"name":"간장","quantity":"4큰술"},{"name":"설탕","quantity":"2큰술"}]',
 '{"ko":["닭고기를 데친다","야채를 썬다","양념장을 만든다","냄비에 닭, 야채, 양념장을 넣고 조린다","당면을 넣고 마무리한다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('seed-041', 'seed',
 '{"ko":"두부조림","en":"Braised Tofu","ja":"豆腐の煮物","zh":"炖豆腐"}',
 '{"ko":"양념장에 조린 두부 요리","en":"Tofu braised in seasoned sauce"}',
 20, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"2큰술"},{"name":"고춧가루","quantity":"1큰술"},{"name":"다진마늘","quantity":"1큰술"}]',
 '{"ko":["두부를 도톰하게 썬다","팬에 두부를 앞뒤로 굽는다","양념장을 만들어 붓는다","중불에서 조린다"]}',
 ARRAY['spicy','stir_fry','veggie','light','quick']),

('seed-042', 'seed',
 '{"ko":"계란찜","en":"Steamed Egg","ja":"茶碗蒸し","zh":"蒸蛋"}',
 '{"ko":"부드럽게 쪄낸 계란찜","en":"Soft steamed egg custard"}',
 15, 'easy', 2,
 '[{"name":"계란","quantity":"3개"},{"name":"물","quantity":"200ml"},{"name":"새우젓","quantity":"1/2큰술"},{"name":"대파","quantity":"약간"},{"name":"당근","quantity":"약간"}]',
 '{"ko":["계란을 풀고 물, 새우젓을 넣어 섞는다","그릇에 부어 당근을 넣는다","냄비에 물을 넣고 중불에서 찐다","대파를 올린다"]}',
 ARRAY['mild','steamed','veggie','light','quick']),

('seed-043', 'seed',
 '{"ko":"장조림","en":"Soy Braised Beef","ja":"牛肉の醤油煮","zh":"酱牛肉"}',
 '{"ko":"간장에 조린 소고기와 메추리알","en":"Beef and quail eggs braised in soy sauce"}',
 60, 'easy', 4,
 '[{"name":"소고기","quantity":"300g"},{"name":"메추리알","quantity":"20개"},{"name":"간장","quantity":"5큰술"},{"name":"마늘","quantity":"5쪽"},{"name":"꽈리고추","quantity":"10개"}]',
 '{"ko":["소고기를 삶아 결대로 찢는다","메추리알을 삶아 껍질을 벗긴다","간장, 마늘을 넣고 조린다","꽈리고추를 넣고 마무리한다"]}',
 ARRAY['mild','soupy','meat','light','side_dish']),

('seed-044', 'seed',
 '{"ko":"돼지갈비찜","en":"Braised Pork Ribs","ja":"豚カルビチム","zh":"炖猪排骨"}',
 '{"ko":"돼지갈비를 양념에 조린 요리","en":"Pork ribs braised in sweet soy sauce"}',
 60, 'medium', 3,
 '[{"name":"돼지갈비","quantity":"600g"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"간장","quantity":"4큰술"},{"name":"설탕","quantity":"2큰술"}]',
 '{"ko":["갈비를 핏물 뺀다","삶아서 기름을 제거한다","양념장에 재운다","야채와 함께 조린다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('seed-045', 'seed',
 '{"ko":"생선조림","en":"Braised Fish","ja":"魚の煮付け","zh":"炖鱼"}',
 '{"ko":"매콤한 양념에 조린 생선","en":"Fish braised in spicy sauce"}',
 30, 'medium', 2,
 '[{"name":"가자미","quantity":"2마리"},{"name":"무","quantity":"150g"},{"name":"대파","quantity":"1대"},{"name":"고추장","quantity":"1큰술"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["생선을 손질한다","무를 깔고 생선을 올린다","양념장을 만들어 붓는다","중불에서 조린다"]}',
 ARRAY['spicy','soupy','seafood','light']),

-- === 전/부침 (Pancakes & Fritters) ===
('seed-046', 'seed',
 '{"ko":"파전","en":"Green Onion Pancake","ja":"ネギチヂミ","zh":"葱饼"}',
 '{"ko":"대파를 듬뿍 넣은 바삭한 파전","en":"Crispy green onion pancake"}',
 20, 'easy', 2,
 '[{"name":"대파","quantity":"5대"},{"name":"밀가루","quantity":"100g"},{"name":"계란","quantity":"1개"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["대파를 길게 썬다","밀가루, 계란, 물로 반죽한다","팬에 기름을 두르고 대파를 올린다","반죽을 붓고 앞뒤로 바삭하게 굽는다"]}',
 ARRAY['mild','grilled','veggie','light','quick']),

('seed-047', 'seed',
 '{"ko":"김치전","en":"Kimchi Pancake","ja":"キムチチヂミ","zh":"泡菜煎饼"}',
 '{"ko":"신김치로 만든 바삭한 김치전","en":"Crispy kimchi pancake"}',
 15, 'easy', 2,
 '[{"name":"김치","quantity":"200g"},{"name":"밀가루","quantity":"80g"},{"name":"계란","quantity":"1개"},{"name":"돼지고기","quantity":"50g"}]',
 '{"ko":["김치를 잘게 썬다","밀가루, 계란, 김치국물로 반죽한다","팬에 기름을 두르고 반죽을 펼친다","앞뒤로 바삭하게 굽는다"]}',
 ARRAY['spicy','grilled','meat','light','quick']),

('seed-048', 'seed',
 '{"ko":"해물파전","en":"Seafood Pancake","ja":"海鮮チヂミ","zh":"海鲜葱饼"}',
 '{"ko":"해산물이 듬뿍 들어간 해물파전","en":"Seafood and green onion pancake"}',
 25, 'medium', 2,
 '[{"name":"대파","quantity":"3대"},{"name":"오징어","quantity":"1마리"},{"name":"새우","quantity":"100g"},{"name":"밀가루","quantity":"100g"},{"name":"계란","quantity":"2개"}]',
 '{"ko":["해산물을 손질한다","밀가루 반죽을 만든다","팬에 대파와 해산물을 올린다","반죽을 붓고 바삭하게 굽는다"]}',
 ARRAY['mild','grilled','seafood','light']),

('seed-049', 'seed',
 '{"ko":"감자전","en":"Potato Pancake","ja":"じゃがいもチヂミ","zh":"土豆饼"}',
 '{"ko":"감자를 갈아 부친 고소한 감자전","en":"Pan-fried grated potato pancake"}',
 20, 'easy', 2,
 '[{"name":"감자","quantity":"3개"},{"name":"소금","quantity":"약간"},{"name":"양파","quantity":"1/2개"}]',
 '{"ko":["감자를 갈아 물기를 빼고 전분을 모은다","양파를 갈아 넣는다","소금으로 간을 한다","팬에 기름을 두르고 바삭하게 굽는다"]}',
 ARRAY['mild','grilled','veggie','light','quick']),

('seed-050', 'seed',
 '{"ko":"동그랑땡","en":"Korean Meatball Patties","ja":"ドングランテン","zh":"肉丸饼"}',
 '{"ko":"고기와 두부로 만든 동그랑땡","en":"Pan-fried meat and tofu patties"}',
 30, 'medium', 3,
 '[{"name":"돼지고기","quantity":"200g"},{"name":"두부","quantity":"1/2모"},{"name":"양파","quantity":"1/2개"},{"name":"계란","quantity":"2개"},{"name":"밀가루","quantity":"약간"}]',
 '{"ko":["돼지고기, 두부, 양파를 다진다","섞어 반죽을 만든다","동그랗게 빚는다","밀가루, 계란옷을 입혀 굽는다"]}',
 ARRAY['mild','grilled','meat','light']),

-- === 반찬 (Side Dishes) ===
('seed-051', 'seed',
 '{"ko":"시금치나물","en":"Seasoned Spinach","ja":"ほうれん草ナムル","zh":"凉拌菠菜"}',
 '{"ko":"참기름으로 무친 시금치나물","en":"Blanched spinach seasoned with sesame oil"}',
 10, 'easy', 2,
 '[{"name":"시금치","quantity":"200g"},{"name":"참기름","quantity":"1큰술"},{"name":"간장","quantity":"1큰술"},{"name":"다진마늘","quantity":"1/2큰술"},{"name":"깨","quantity":"약간"}]',
 '{"ko":["시금치를 데쳐 찬물에 헹군다","물기를 짠다","참기름, 간장, 마늘, 깨를 넣고 무친다"]}',
 ARRAY['mild','raw','veggie','light','quick','side_dish']),

('seed-052', 'seed',
 '{"ko":"콩나물무침","en":"Seasoned Bean Sprouts","ja":"もやしナムル","zh":"凉拌豆芽"}',
 '{"ko":"아삭한 콩나물무침","en":"Crunchy seasoned bean sprouts"}',
 10, 'easy', 2,
 '[{"name":"콩나물","quantity":"200g"},{"name":"참기름","quantity":"1큰술"},{"name":"소금","quantity":"약간"},{"name":"다진마늘","quantity":"1/2큰술"},{"name":"대파","quantity":"약간"}]',
 '{"ko":["콩나물을 삶아 찬물에 헹군다","물기를 뺀다","양념을 넣고 무친다"]}',
 ARRAY['mild','raw','veggie','light','quick','side_dish']),

('seed-053', 'seed',
 '{"ko":"멸치볶음","en":"Stir-fried Anchovies","ja":"煮干し炒め","zh":"炒小鱼干"}',
 '{"ko":"달콤 짭짤한 멸치볶음","en":"Sweet and savory stir-fried dried anchovies"}',
 15, 'easy', 4,
 '[{"name":"멸치","quantity":"100g"},{"name":"간장","quantity":"1큰술"},{"name":"물엿","quantity":"2큰술"},{"name":"깨","quantity":"약간"},{"name":"고추","quantity":"1개"}]',
 '{"ko":["멸치를 마른 팬에 볶아 비린내를 없앤다","간장, 물엿을 넣고 볶는다","깨를 뿌린다"]}',
 ARRAY['mild','stir_fry','seafood','light','quick','side_dish']),

('seed-054', 'seed',
 '{"ko":"어묵볶음","en":"Stir-fried Fish Cake","ja":"おでん炒め","zh":"炒鱼糕"}',
 '{"ko":"달콤하게 볶은 어묵볶음","en":"Sweet stir-fried fish cake"}',
 10, 'easy', 2,
 '[{"name":"어묵","quantity":"200g"},{"name":"양파","quantity":"1/2개"},{"name":"간장","quantity":"1큰술"},{"name":"물엿","quantity":"1큰술"},{"name":"고추","quantity":"1개"}]',
 '{"ko":["어묵을 먹기 좋은 크기로 썬다","양파를 썬다","팬에 볶는다","간장, 물엿으로 양념한다"]}',
 ARRAY['mild','stir_fry','seafood','light','quick','side_dish']),

('seed-055', 'seed',
 '{"ko":"감자조림","en":"Braised Potatoes","ja":"じゃがいもの煮物","zh":"炖土豆"}',
 '{"ko":"간장에 조린 감자조림","en":"Potatoes braised in soy sauce"}',
 25, 'easy', 3,
 '[{"name":"감자","quantity":"3개"},{"name":"간장","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"물엿","quantity":"1큰술"}]',
 '{"ko":["감자를 깍둑썰기한다","팬에 감자, 간장, 설탕, 물을 넣고 조린다","물엿을 넣고 윤기나게 마무리한다"]}',
 ARRAY['mild','soupy','veggie','light','side_dish']),

('seed-056', 'seed',
 '{"ko":"계란말이","en":"Rolled Omelette","ja":"卵焼き","zh":"鸡蛋卷"}',
 '{"ko":"야채를 넣어 말아 구운 계란말이","en":"Rolled omelette with vegetables"}',
 15, 'easy', 2,
 '[{"name":"계란","quantity":"4개"},{"name":"당근","quantity":"약간"},{"name":"대파","quantity":"약간"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["계란을 풀고 야채를 잘게 썰어 넣는다","소금으로 간을 한다","팬에 기름을 두르고 얇게 펼친다","말아가며 여러 번 구운다"]}',
 ARRAY['mild','grilled','veggie','light','quick','side_dish']),

('seed-057', 'seed',
 '{"ko":"깍두기","en":"Cubed Radish Kimchi","ja":"カクテキ","zh":"萝卜泡菜"}',
 '{"ko":"무를 깍둑썰기하여 담근 깍두기","en":"Cubed radish kimchi"}',
 30, 'easy', 6,
 '[{"name":"무","quantity":"1개"},{"name":"고춧가루","quantity":"5큰술"},{"name":"새우젓","quantity":"2큰술"},{"name":"다진마늘","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["무를 깍둑썰기한다","소금에 절인다","양념을 만든다","무에 양념을 버무린다","밀폐용기에 담아 숙성시킨다"]}',
 ARRAY['spicy','raw','veggie','light','side_dish']),

('seed-058', 'seed',
 '{"ko":"오이소박이","en":"Stuffed Cucumber Kimchi","ja":"きゅうりキムチ","zh":"黄瓜泡菜"}',
 '{"ko":"오이에 양념소를 넣어 담근 김치","en":"Cucumber kimchi stuffed with spicy filling"}',
 30, 'easy', 4,
 '[{"name":"오이","quantity":"5개"},{"name":"부추","quantity":"50g"},{"name":"고춧가루","quantity":"3큰술"},{"name":"새우젓","quantity":"1큰술"},{"name":"다진마늘","quantity":"1큰술"}]',
 '{"ko":["오이를 소금에 절인다","부추를 잘게 썬다","양념소를 만든다","오이에 칼집을 넣고 소를 넣는다"]}',
 ARRAY['spicy','raw','veggie','light','side_dish']),

('seed-059', 'seed',
 '{"ko":"잡채밥","en":"Japchae Rice","ja":"チャプチェご飯","zh":"杂菜饭"}',
 '{"ko":"잡채를 밥 위에 올린 잡채밥","en":"Japchae served over steamed rice"}',
 35, 'medium', 2,
 '[{"name":"당면","quantity":"100g"},{"name":"소고기","quantity":"100g"},{"name":"시금치","quantity":"50g"},{"name":"당근","quantity":"1/2개"},{"name":"밥","quantity":"1공기"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["잡채를 만든다","밥을 그릇에 담는다","잡채를 밥 위에 올린다"]}',
 ARRAY['mild','stir_fry','meat','heavy','rice']),

('seed-060', 'seed',
 '{"ko":"무생채","en":"Spicy Radish Salad","ja":"大根サラダ","zh":"辣拌萝卜丝"}',
 '{"ko":"새콤매콤한 무생채","en":"Spicy-sour shredded radish salad"}',
 10, 'easy', 3,
 '[{"name":"무","quantity":"300g"},{"name":"고춧가루","quantity":"2큰술"},{"name":"식초","quantity":"1큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"대파","quantity":"약간"}]',
 '{"ko":["무를 채 썬다","고춧가루, 식초, 설탕으로 양념한다","버무린다"]}',
 ARRAY['spicy','raw','veggie','light','quick','side_dish']),

-- === 구이/튀김 (Grilled & Fried) ===
('seed-061', 'seed',
 '{"ko":"돈까스","en":"Pork Cutlet","ja":"とんかつ","zh":"炸猪排"}',
 '{"ko":"바삭하게 튀긴 돈까스","en":"Deep-fried breaded pork cutlet"}',
 30, 'medium', 1,
 '[{"name":"돼지고기(등심)","quantity":"200g"},{"name":"밀가루","quantity":"적당량"},{"name":"계란","quantity":"2개"},{"name":"빵가루","quantity":"적당량"},{"name":"양배추","quantity":"100g"}]',
 '{"ko":["돼지고기를 두들겨 펴준다","밀가루-계란-빵가루 순으로 입힌다","기름에 바삭하게 튀긴다","양배추를 채 썰어 곁들인다"]}',
 ARRAY['mild','grilled','meat','heavy']),

('seed-062', 'seed',
 '{"ko":"치킨","en":"Korean Fried Chicken","ja":"韓国フライドチキン","zh":"韩式炸鸡"}',
 '{"ko":"바삭한 한국식 치킨","en":"Crispy Korean-style fried chicken"}',
 40, 'medium', 3,
 '[{"name":"닭고기","quantity":"1마리"},{"name":"튀김가루","quantity":"200g"},{"name":"전분","quantity":"100g"},{"name":"마늘","quantity":"5쪽"}]',
 '{"ko":["닭을 토막낸다","튀김가루와 전분을 섞어 옷을 입힌다","170도에서 한번 튀긴다","180도에서 한번 더 바삭하게 튀긴다"]}',
 ARRAY['mild','grilled','meat','heavy']),

('seed-063', 'seed',
 '{"ko":"양념치킨","en":"Spicy Fried Chicken","ja":"ヤンニョムチキン","zh":"甜辣炸鸡"}',
 '{"ko":"달콤매콤한 소스를 입힌 양념치킨","en":"Fried chicken coated in sweet-spicy sauce"}',
 45, 'medium', 3,
 '[{"name":"닭고기","quantity":"1마리"},{"name":"튀김가루","quantity":"200g"},{"name":"고추장","quantity":"3큰술"},{"name":"물엿","quantity":"3큰술"},{"name":"케첩","quantity":"2큰술"}]',
 '{"ko":["닭을 토막내 튀긴다","양념소스를 만든다","튀긴 치킨에 양념을 버무린다"]}',
 ARRAY['spicy','grilled','meat','heavy']),

('seed-064', 'seed',
 '{"ko":"고기구이(소)","en":"Grilled Beef","ja":"焼肉","zh":"烤牛肉"}',
 '{"ko":"소고기를 직접 구워 먹는 고기구이","en":"Grilled beef served with lettuce wraps"}',
 20, 'easy', 2,
 '[{"name":"소고기(등심)","quantity":"300g"},{"name":"상추","quantity":"10장"},{"name":"쌈장","quantity":"3큰술"},{"name":"마늘","quantity":"5쪽"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["소고기를 적당한 크기로 썬다","팬 또는 그릴에 굽는다","상추, 쌈장과 함께 먹는다"]}',
 ARRAY['mild','grilled','meat','heavy','quick']),

('seed-065', 'seed',
 '{"ko":"생선구이","en":"Grilled Fish","ja":"焼き魚","zh":"烤鱼"}',
 '{"ko":"소금 간을 한 생선구이","en":"Salt-grilled fish"}',
 20, 'easy', 1,
 '[{"name":"고등어","quantity":"1마리"},{"name":"소금","quantity":"약간"},{"name":"레몬","quantity":"약간"}]',
 '{"ko":["생선에 소금을 뿌려 간을 한다","팬에 기름을 두르고 앞뒤로 굽는다","레몬을 곁들인다"]}',
 ARRAY['mild','grilled','seafood','light','quick']),

('seed-066', 'seed',
 '{"ko":"새우튀김","en":"Fried Shrimp","ja":"エビフライ","zh":"炸虾"}',
 '{"ko":"바삭하게 튀긴 새우튀김","en":"Crispy deep-fried shrimp"}',
 25, 'medium', 2,
 '[{"name":"새우","quantity":"10마리"},{"name":"밀가루","quantity":"적당량"},{"name":"계란","quantity":"1개"},{"name":"빵가루","quantity":"적당량"}]',
 '{"ko":["새우를 손질한다","밀가루-계란-빵가루 순으로 입힌다","170도에서 바삭하게 튀긴다"]}',
 ARRAY['mild','grilled','seafood','light']),

('seed-067', 'seed',
 '{"ko":"야채튀김","en":"Vegetable Tempura","ja":"野菜天ぷら","zh":"蔬菜天妇罗"}',
 '{"ko":"다양한 야채를 튀긴 야채튀김","en":"Assorted vegetable tempura"}',
 25, 'easy', 2,
 '[{"name":"고구마","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"깻잎","quantity":"10장"},{"name":"튀김가루","quantity":"100g"}]',
 '{"ko":["야채를 썬다","튀김가루로 반죽을 만든다","야채에 반죽을 입혀 튀긴다"]}',
 ARRAY['mild','grilled','veggie','light']),

('seed-068', 'seed',
 '{"ko":"떡갈비","en":"Grilled Short Rib Patties","ja":"トッカルビ","zh":"饼状烤排骨"}',
 '{"ko":"다진 갈비를 양념해 구운 떡갈비","en":"Seasoned ground short rib patties"}',
 30, 'medium', 2,
 '[{"name":"소고기(갈비살)","quantity":"300g"},{"name":"양파","quantity":"1/2개"},{"name":"간장","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"다진마늘","quantity":"1큰술"}]',
 '{"ko":["갈비살을 다진다","양파를 다져 섞는다","양념을 넣고 반죽한다","납작하게 빚어 굽는다"]}',
 ARRAY['mild','grilled','meat','heavy']),

-- === 해산물 (Seafood) ===
('seed-069', 'seed',
 '{"ko":"해물탕","en":"Spicy Seafood Stew","ja":"海鮮鍋","zh":"海鲜汤"}',
 '{"ko":"다양한 해산물이 들어간 얼큰한 탕","en":"Spicy stew with assorted seafood"}',
 30, 'medium', 3,
 '[{"name":"새우","quantity":"5마리"},{"name":"조개","quantity":"200g"},{"name":"오징어","quantity":"1마리"},{"name":"두부","quantity":"1/2모"},{"name":"고춧가루","quantity":"2큰술"}]',
 '{"ko":["해산물을 손질한다","냄비에 물과 양념을 넣고 끓인다","해산물과 두부를 넣는다","끓으면 대파를 넣는다"]}',
 ARRAY['spicy','soupy','seafood','heavy']),

('seed-070', 'seed',
 '{"ko":"조개탕","en":"Clam Soup","ja":"貝のスープ","zh":"蛤蜊汤"}',
 '{"ko":"시원한 조개 국물의 조개탕","en":"Clear clam soup"}',
 20, 'easy', 2,
 '[{"name":"조개","quantity":"300g"},{"name":"대파","quantity":"1대"},{"name":"마늘","quantity":"3쪽"},{"name":"소금","quantity":"약간"},{"name":"청주","quantity":"1큰술"}]',
 '{"ko":["조개를 해감한다","물에 조개, 마늘을 넣고 끓인다","거품을 걷는다","대파를 넣고 소금으로 간을 한다"]}',
 ARRAY['mild','soupy','seafood','light','quick']),

('seed-071', 'seed',
 '{"ko":"매운탕","en":"Spicy Fish Stew","ja":"メウンタン","zh":"辣鱼汤"}',
 '{"ko":"생선을 넣고 끓인 얼큰한 매운탕","en":"Spicy fish stew with tofu"}',
 25, 'easy', 2,
 '[{"name":"대구","quantity":"300g"},{"name":"두부","quantity":"1/2모"},{"name":"호박","quantity":"1/2개"},{"name":"고춧가루","quantity":"2큰술"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["생선을 토막낸다","냄비에 물과 양념을 넣고 끓인다","생선, 두부, 호박을 넣는다","대파를 넣고 마무리한다"]}',
 ARRAY['spicy','soupy','seafood','light']),

('seed-072', 'seed',
 '{"ko":"낙지볶음","en":"Stir-fried Octopus","ja":"タコ炒め","zh":"炒章鱼"}',
 '{"ko":"매콤하게 볶은 낙지볶음","en":"Spicy stir-fried baby octopus"}',
 20, 'easy', 2,
 '[{"name":"낙지","quantity":"2마리"},{"name":"양파","quantity":"1개"},{"name":"고추장","quantity":"2큰술"},{"name":"고춧가루","quantity":"1큰술"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["낙지를 손질한다","양념장을 만든다","팬에 낙지와 양파를 볶는다","양념장을 넣고 볶는다"]}',
 ARRAY['spicy','stir_fry','seafood','light','quick']),

('seed-073', 'seed',
 '{"ko":"새우볶음밥","en":"Shrimp Fried Rice","ja":"エビチャーハン","zh":"虾仁炒饭"}',
 '{"ko":"탱글한 새우가 들어간 볶음밥","en":"Fried rice with plump shrimp"}',
 15, 'easy', 1,
 '[{"name":"새우","quantity":"100g"},{"name":"밥","quantity":"2공기"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["새우를 손질한다","계란을 스크램블한다","새우를 볶는다","밥을 넣고 볶는다","간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','seafood','light','quick','rice']),

-- === 국민음식/간편식 (Comfort & Quick) ===
('seed-074', 'seed',
 '{"ko":"라면","en":"Ramyeon","ja":"ラーメン","zh":"方便面"}',
 '{"ko":"한국식 인스턴트 라면","en":"Korean instant noodles"}',
 10, 'easy', 1,
 '[{"name":"라면","quantity":"1개"},{"name":"계란","quantity":"1개"},{"name":"대파","quantity":"약간"}]',
 '{"ko":["물을 끓인다","면과 스프를 넣는다","계란을 넣는다","대파를 올린다"]}',
 ARRAY['spicy','soupy','veggie','light','quick','noodle']),

('seed-075', 'seed',
 '{"ko":"만두국","en":"Dumpling Soup","ja":"マンドゥクッ","zh":"饺子汤"}',
 '{"ko":"만두를 넣고 끓인 만두국","en":"Korean dumpling soup"}',
 20, 'easy', 2,
 '[{"name":"만두","quantity":"15개"},{"name":"계란","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"},{"name":"다시마","quantity":"1장"}]',
 '{"ko":["다시마로 육수를 낸다","만두를 넣고 끓인다","계란을 풀어 넣는다","대파를 올린다"]}',
 ARRAY['mild','soupy','meat','heavy','quick']),

('seed-076', 'seed',
 '{"ko":"토스트(길거리)","en":"Korean Street Toast","ja":"韓国トースト","zh":"韩式吐司"}',
 '{"ko":"길거리에서 파는 달콤한 토스트","en":"Korean-style sweet egg toast"}',
 10, 'easy', 1,
 '[{"name":"식빵","quantity":"2장"},{"name":"계란","quantity":"2개"},{"name":"양배추","quantity":"50g"},{"name":"당근","quantity":"약간"},{"name":"설탕","quantity":"약간"},{"name":"케첩","quantity":"약간"}]',
 '{"ko":["계란에 양배추, 당근을 섞어 부친다","식빵을 버터에 굽는다","계란부침을 식빵에 올린다","설탕, 케첩을 뿌리고 덮는다"]}',
 ARRAY['mild','grilled','veggie','light','quick']),

('seed-077', 'seed',
 '{"ko":"참치김밥","en":"Tuna Kimbap","ja":"ツナキンパ","zh":"金枪鱼紫菜包饭"}',
 '{"ko":"참치마요가 들어간 김밥","en":"Kimbap with tuna mayo filling"}',
 30, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"김","quantity":"3장"},{"name":"참치캔","quantity":"1캔"},{"name":"마요네즈","quantity":"2큰술"},{"name":"당근","quantity":"1/2개"},{"name":"시금치","quantity":"50g"}]',
 '{"ko":["밥에 참기름, 소금을 넣는다","참치와 마요네즈를 섞는다","야채를 손질한다","김 위에 밥을 펴고 속재료를 넣어 만다"]}',
 ARRAY['mild','raw','seafood','light','rice']),

('seed-078', 'seed',
 '{"ko":"김밥","en":"Kimbap","ja":"キンパ","zh":"紫菜包饭"}',
 '{"ko":"다양한 속재료를 넣은 클래식 김밥","en":"Classic Korean seaweed rice roll"}',
 40, 'medium', 3,
 '[{"name":"밥","quantity":"3공기"},{"name":"김","quantity":"5장"},{"name":"시금치","quantity":"100g"},{"name":"당근","quantity":"1개"},{"name":"계란","quantity":"3개"},{"name":"단무지","quantity":"3줄"},{"name":"햄","quantity":"100g"}]',
 '{"ko":["밥에 참기름, 소금을 넣는다","속재료를 각각 준비한다","김 위에 밥을 펴고 속재료를 올린다","말아서 참기름을 바르고 썬다"]}',
 ARRAY['mild','raw','meat','light','rice']),

('seed-079', 'seed',
 '{"ko":"유부초밥","en":"Inari Sushi","ja":"いなり寿司","zh":"豆皮寿司"}',
 '{"ko":"유부에 밥을 넣은 유부초밥","en":"Seasoned tofu pockets stuffed with rice"}',
 20, 'easy', 2,
 '[{"name":"유부","quantity":"10장"},{"name":"밥","quantity":"2공기"},{"name":"식초","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"깨","quantity":"약간"}]',
 '{"ko":["유부를 간장, 설탕에 조린다","밥에 식초, 설탕을 넣어 초밥을 만든다","유부에 초밥을 넣는다"]}',
 ARRAY['mild','raw','veggie','light','quick','rice']),

('seed-080', 'seed',
 '{"ko":"떡만둣국","en":"Rice Cake Dumpling Soup","ja":"トックマンドゥクッ","zh":"年糕饺子汤"}',
 '{"ko":"떡국과 만두국을 합친 든든한 국","en":"Rice cake and dumpling soup"}',
 25, 'easy', 2,
 '[{"name":"떡국떡","quantity":"200g"},{"name":"만두","quantity":"10개"},{"name":"소고기","quantity":"100g"},{"name":"계란","quantity":"1개"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["소고기를 삶아 육수를 만든다","떡과 만두를 넣고 끓인다","계란을 풀어 넣는다","대파를 올린다"]}',
 ARRAY['mild','soupy','meat','heavy']),

-- === 추가 한식 (More Korean) ===
('seed-081', 'seed',
 '{"ko":"북엇국","en":"Dried Pollack Soup","ja":"干しタラスープ","zh":"干明太鱼汤"}',
 '{"ko":"북어채로 끓인 해장 국","en":"Hangover soup with dried pollack"}',
 20, 'easy', 2,
 '[{"name":"북어채","quantity":"30g"},{"name":"두부","quantity":"1/2모"},{"name":"계란","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["북어채를 참기름에 볶는다","물을 넣고 끓인다","두부를 넣는다","계란을 풀어 넣고 대파를 올린다"]}',
 ARRAY['mild','soupy','seafood','light','quick']),

('seed-082', 'seed',
 '{"ko":"소떡소떡","en":"Sausage Rice Cake Skewers","ja":"ソトクソトク","zh":"香肠年糕串"}',
 '{"ko":"소시지와 떡을 번갈아 꽂은 소떡소떡","en":"Skewered sausages and rice cakes with sauce"}',
 15, 'easy', 2,
 '[{"name":"소시지","quantity":"6개"},{"name":"떡","quantity":"200g"},{"name":"고추장","quantity":"2큰술"},{"name":"물엿","quantity":"2큰술"},{"name":"케첩","quantity":"1큰술"}]',
 '{"ko":["소시지와 떡을 꼬치에 번갈아 꽂는다","팬에 굽는다","양념 소스를 만들어 발라가며 굽는다"]}',
 ARRAY['spicy','grilled','meat','light','quick']),

('seed-083', 'seed',
 '{"ko":"미역줄기볶음","en":"Stir-fried Seaweed Stems","ja":"わかめ茎炒め","zh":"炒海带茎"}',
 '{"ko":"쫄깃한 미역줄기를 볶은 반찬","en":"Stir-fried chewy seaweed stems"}',
 15, 'easy', 3,
 '[{"name":"미역줄기","quantity":"200g"},{"name":"참기름","quantity":"1큰술"},{"name":"간장","quantity":"1큰술"},{"name":"다진마늘","quantity":"1큰술"},{"name":"깨","quantity":"약간"}]',
 '{"ko":["미역줄기를 씻어 썬다","참기름에 마늘을 볶는다","미역줄기를 넣고 볶는다","간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','seafood','light','quick','side_dish']),

('seed-084', 'seed',
 '{"ko":"콩국수","en":"Cold Soy Milk Noodles","ja":"コングクス","zh":"豆浆面"}',
 '{"ko":"시원한 콩물에 국수를 말아먹는 여름 별미","en":"Noodles in chilled soy milk broth"}',
 40, 'medium', 2,
 '[{"name":"콩","quantity":"200g"},{"name":"소면","quantity":"200g"},{"name":"오이","quantity":"1/2개"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["콩을 삶아 갈아 콩물을 만든다","차갑게 식힌다","소면을 삶아 찬물에 헹군다","그릇에 면을 담고 콩물을 붓는다","오이를 올린다"]}',
 ARRAY['mild','soupy','veggie','light','noodle']),

('seed-085', 'seed',
 '{"ko":"볶음우동","en":"Stir-fried Udon","ja":"焼きうどん","zh":"炒乌冬面"}',
 '{"ko":"야채와 함께 볶은 우동면","en":"Stir-fried udon noodles with vegetables"}',
 15, 'easy', 1,
 '[{"name":"우동면","quantity":"1인분"},{"name":"양배추","quantity":"100g"},{"name":"양파","quantity":"1/2개"},{"name":"당근","quantity":"약간"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["야채를 썬다","팬에 야채를 볶는다","우동면을 넣고 볶는다","간장으로 양념한다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick','noodle']),

('seed-086', 'seed',
 '{"ko":"고추잡채","en":"Pepper Japchae","ja":"ピーマンチャプチェ","zh":"辣椒杂菜"}',
 '{"ko":"고추와 당면으로 만든 고추잡채","en":"Stir-fried peppers with glass noodles and beef"}',
 20, 'easy', 2,
 '[{"name":"피망","quantity":"3개"},{"name":"당면","quantity":"50g"},{"name":"소고기","quantity":"100g"},{"name":"간장","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["당면을 삶는다","피망, 소고기를 채 썬다","팬에 소고기를 볶는다","피망과 당면을 넣고 양념한다"]}',
 ARRAY['mild','stir_fry','meat','light','quick','side_dish']),

('seed-087', 'seed',
 '{"ko":"닭가슴살샐러드","en":"Chicken Breast Salad","ja":"チキンサラダ","zh":"鸡胸肉沙拉"}',
 '{"ko":"다이어트용 닭가슴살 샐러드","en":"Diet-friendly chicken breast salad"}',
 15, 'easy', 1,
 '[{"name":"닭가슴살","quantity":"150g"},{"name":"양상추","quantity":"100g"},{"name":"방울토마토","quantity":"5개"},{"name":"오이","quantity":"1/2개"},{"name":"드레싱","quantity":"2큰술"}]',
 '{"ko":["닭가슴살을 삶아 찢는다","야채를 씻어 준비한다","그릇에 담고 드레싱을 뿌린다"]}',
 ARRAY['mild','raw','meat','light','quick']),

('seed-088', 'seed',
 '{"ko":"순대볶음","en":"Stir-fried Sundae","ja":"スンデ炒め","zh":"炒血肠"}',
 '{"ko":"순대와 야채를 매콤하게 볶은 요리","en":"Spicy stir-fried Korean blood sausage"}',
 20, 'easy', 2,
 '[{"name":"순대","quantity":"300g"},{"name":"떡볶이떡","quantity":"100g"},{"name":"양배추","quantity":"100g"},{"name":"양파","quantity":"1개"},{"name":"고추장","quantity":"2큰술"}]',
 '{"ko":["순대를 적당한 크기로 썬다","야채를 썬다","팬에 양념을 넣고 볶는다","순대와 떡을 넣고 볶는다"]}',
 ARRAY['spicy','stir_fry','meat','heavy','quick']),

('seed-089', 'seed',
 '{"ko":"부추전","en":"Chive Pancake","ja":"ニラチヂミ","zh":"韭菜饼"}',
 '{"ko":"부추를 넣고 바삭하게 부친 전","en":"Crispy chive pancake"}',
 15, 'easy', 2,
 '[{"name":"부추","quantity":"150g"},{"name":"밀가루","quantity":"80g"},{"name":"계란","quantity":"1개"},{"name":"고추","quantity":"1개"}]',
 '{"ko":["부추를 5cm 길이로 썬다","밀가루, 계란, 물로 반죽한다","팬에 기름을 두르고 부친다"]}',
 ARRAY['mild','grilled','veggie','light','quick']),

('seed-090', 'seed',
 '{"ko":"닭도리탕","en":"Spicy Chicken Stew","ja":"鶏の辛煮","zh":"辣鸡汤"}',
 '{"ko":"통감자와 닭고기를 매콤하게 끓인 탕","en":"Spicy chicken stew with whole potatoes"}',
 45, 'medium', 3,
 '[{"name":"닭고기","quantity":"500g"},{"name":"감자","quantity":"3개"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1개"},{"name":"고춧가루","quantity":"3큰술"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["닭을 데친다","야채를 큼직하게 썬다","양념장을 만든다","모든 재료를 넣고 끓인다"]}',
 ARRAY['spicy','soupy','meat','heavy']),

-- === 일품요리 (Special Dishes) ===
('seed-091', 'seed',
 '{"ko":"떡갈비정식","en":"Tteokgalbi Set","ja":"トッカルビ定食","zh":"饼烤排骨套餐"}',
 '{"ko":"떡갈비에 밥과 반찬을 곁들인 정식","en":"Grilled short rib patties with rice and sides"}',
 40, 'medium', 1,
 '[{"name":"소고기","quantity":"200g"},{"name":"밥","quantity":"1공기"},{"name":"양파","quantity":"1/2개"},{"name":"간장","quantity":"2큰술"},{"name":"계란","quantity":"1개"}]',
 '{"ko":["고기를 다져 양념하고 빚는다","팬에 구운다","밥과 반찬을 함께 차린다"]}',
 ARRAY['mild','grilled','meat','heavy','rice']),

('seed-092', 'seed',
 '{"ko":"돼지불백","en":"Spicy Pork BBQ","ja":"豚プルベク","zh":"辣猪肉烧烤"}',
 '{"ko":"매콤달콤한 양념 돼지불백","en":"Sweet and spicy marinated pork BBQ"}',
 25, 'easy', 2,
 '[{"name":"돼지고기(목살)","quantity":"300g"},{"name":"양파","quantity":"1개"},{"name":"고추장","quantity":"2큰술"},{"name":"간장","quantity":"1큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["돼지고기를 양념에 재운다","팬에 양파와 함께 볶는다","밥과 함께 먹는다"]}',
 ARRAY['spicy','stir_fry','meat','heavy','quick']),

('seed-093', 'seed',
 '{"ko":"두부전골","en":"Tofu Hot Pot","ja":"豆腐鍋","zh":"豆腐火锅"}',
 '{"ko":"두부와 야채가 듬뿍 들어간 전골","en":"Hot pot with tofu and vegetables"}',
 30, 'easy', 3,
 '[{"name":"두부","quantity":"1모"},{"name":"버섯","quantity":"100g"},{"name":"대파","quantity":"2대"},{"name":"소고기","quantity":"100g"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["재료를 보기 좋게 썬다","전골냄비에 담는다","육수를 붓고 끓인다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('seed-094', 'seed',
 '{"ko":"스팸김치볶음밥","en":"Spam Kimchi Fried Rice","ja":"スパムキムチチャーハン","zh":"午餐肉泡菜炒饭"}',
 '{"ko":"스팸과 김치로 만든 간단 볶음밥","en":"Easy fried rice with spam and kimchi"}',
 15, 'easy', 1,
 '[{"name":"스팸","quantity":"1/2캔"},{"name":"김치","quantity":"100g"},{"name":"밥","quantity":"1공기"},{"name":"계란","quantity":"1개"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["스팸과 김치를 잘게 썬다","팬에 스팸을 볶는다","김치와 밥을 넣고 볶는다","계란 후라이를 올린다"]}',
 ARRAY['spicy','stir_fry','meat','light','quick','rice']),

('seed-095', 'seed',
 '{"ko":"된장국","en":"Soybean Paste Soup","ja":"味噌汁","zh":"大酱汤"}',
 '{"ko":"간단하게 끓인 된장국","en":"Simple soybean paste soup"}',
 15, 'easy', 2,
 '[{"name":"된장","quantity":"1.5큰술"},{"name":"두부","quantity":"1/2모"},{"name":"파","quantity":"1대"},{"name":"양파","quantity":"1/2개"}]',
 '{"ko":["물을 끓인다","된장을 풀어준다","두부와 양파를 넣는다","파를 넣고 마무리한다"]}',
 ARRAY['mild','soupy','veggie','light','quick']),

('seed-096', 'seed',
 '{"ko":"진미채볶음","en":"Seasoned Dried Squid","ja":"裂きイカ炒め","zh":"炒鱿鱼丝"}',
 '{"ko":"달콤매콤한 진미채볶음","en":"Sweet and spicy stir-fried dried shredded squid"}',
 15, 'easy', 4,
 '[{"name":"진미채","quantity":"100g"},{"name":"고추장","quantity":"1큰술"},{"name":"물엿","quantity":"2큰술"},{"name":"간장","quantity":"1큰술"},{"name":"깨","quantity":"약간"}]',
 '{"ko":["진미채를 물에 살짝 적신다","팬에 양념을 넣고 볶는다","진미채를 넣고 버무린다","깨를 뿌린다"]}',
 ARRAY['spicy','stir_fry','seafood','light','quick','side_dish']),

('seed-097', 'seed',
 '{"ko":"소고기무국","en":"Beef Radish Soup","ja":"牛肉大根スープ","zh":"牛肉萝卜汤"}',
 '{"ko":"소고기와 무로 끓인 맑은 국","en":"Clear soup with beef and radish"}',
 30, 'easy', 3,
 '[{"name":"소고기","quantity":"100g"},{"name":"무","quantity":"200g"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"},{"name":"다진마늘","quantity":"1큰술"}]',
 '{"ko":["소고기를 참기름에 볶는다","무를 넣고 볶는다","물을 붓고 끓인다","간장으로 간을 한다","대파를 넣는다"]}',
 ARRAY['mild','soupy','meat','light']),

('seed-098', 'seed',
 '{"ko":"김치만두","en":"Kimchi Dumplings","ja":"キムチマンドゥ","zh":"泡菜饺子"}',
 '{"ko":"김치와 돼지고기로 만든 만두","en":"Dumplings with kimchi and pork filling"}',
 50, 'medium', 4,
 '[{"name":"만두피","quantity":"30장"},{"name":"김치","quantity":"200g"},{"name":"돼지고기","quantity":"150g"},{"name":"두부","quantity":"1/2모"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["김치를 잘게 다진다","소를 만든다","만두피에 소를 넣고 빚는다","쪄내거나 굽는다"]}',
 ARRAY['spicy','steamed','meat','heavy']),

('seed-099', 'seed',
 '{"ko":"콩비지찌개","en":"Ground Soybean Stew","ja":"おからチゲ","zh":"豆渣汤"}',
 '{"ko":"콩비지로 끓인 구수한 찌개","en":"Stew made with ground soybean paste"}',
 30, 'easy', 2,
 '[{"name":"콩비지","quantity":"200g"},{"name":"김치","quantity":"100g"},{"name":"돼지고기","quantity":"100g"},{"name":"대파","quantity":"1대"},{"name":"된장","quantity":"1큰술"}]',
 '{"ko":["돼지고기를 볶는다","김치를 넣고 볶는다","콩비지와 물을 넣고 끓인다","된장으로 간을 한다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('seed-100', 'seed',
 '{"ko":"비빔냉면","en":"Spicy Cold Noodles","ja":"ビビン冷麺","zh":"拌冷面"}',
 '{"ko":"매콤새콤한 양념의 비빔냉면","en":"Cold noodles with spicy-sweet sauce"}',
 20, 'easy', 1,
 '[{"name":"냉면","quantity":"1인분"},{"name":"오이","quantity":"1/2개"},{"name":"삶은계란","quantity":"1개"},{"name":"고추장","quantity":"2큰술"},{"name":"식초","quantity":"1큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["냉면을 삶아 찬물에 헹군다","양념장을 만든다","오이를 채 썬다","면에 양념장을 넣고 비빈다","계란을 올린다"]}',
 ARRAY['spicy','stir_fry','veggie','light','quick','noodle']);
