-- Fridge Mate 레시피 시드 데이터 (100개 일식 레시피)
-- Supabase SQL Editor에서 실행하세요
-- tags: spicy, mild, soupy, stir_fry, grilled, steamed, raw, meat, seafood, veggie, heavy, light, quick, noodle, rice, side_dish, bread, pasta, salad, baked, deep_fried, dim_sum

-- 기존 일식 시드 데이터 삭제
DELETE FROM public.recipes WHERE external_id LIKE 'japanese-%';

INSERT INTO public.recipes (external_id, source, title, description, cooking_time, difficulty, servings, ingredients, instructions, tags) VALUES

-- === 초밥/사시미 (Sushi & Sashimi) ===
('japanese-001', 'seed',
 '{"ko":"연어 초밥","en":"Salmon Nigiri Sushi","ja":"サーモン握り寿司","zh":"三文鱼寿司"}',
 '{"ko":"신선한 연어로 만든 정통 니기리 초밥","en":"Traditional nigiri sushi with fresh salmon"}',
 20, 'medium', 2,
 '[{"name":"초밥용 쌀","quantity":"2컵"},{"name":"연어 회","quantity":"200g"},{"name":"식초","quantity":"3큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"와사비","quantity":"약간"}]',
 '{"ko":["밥을 짓고 식초, 설탕, 소금으로 초밥 식초를 만든다","밥에 초밥 식초를 섞어 식힌다","연어를 얇게 썬다","밥을 작게 뭉쳐 와사비를 바른다","연어를 올려 초밥을 만든다"]}',
 ARRAY['raw','seafood','light','rice']),

('japanese-002', 'seed',
 '{"ko":"참치 초밥","en":"Tuna Nigiri Sushi","ja":"マグロ握り寿司","zh":"金枪鱼寿司"}',
 '{"ko":"고급 참치로 만든 프리미엄 초밥","en":"Premium sushi with high-quality tuna"}',
 20, 'medium', 2,
 '[{"name":"초밥용 쌀","quantity":"2컵"},{"name":"참치 회","quantity":"200g"},{"name":"초밥 식초","quantity":"3큰술"},{"name":"간장","quantity":"약간"},{"name":"와사비","quantity":"약간"}]',
 '{"ko":["초밥 밥을 준비한다","참치를 얇게 썬다","밥을 작게 뭉쳐 와사비를 바른다","참치를 올려 모양을 잡는다","간장을 곁들여 낸다"]}',
 ARRAY['raw','seafood','light','rice']),

('japanese-003', 'seed',
 '{"ko":"캘리포니아 롤","en":"California Roll","ja":"カリフォルニアロール","zh":"加州卷"}',
 '{"ko":"게맛살과 아보카도로 만든 인기 롤 초밥","en":"Popular roll sushi with crab stick and avocado"}',
 30, 'medium', 2,
 '[{"name":"초밥용 쌀","quantity":"2컵"},{"name":"게맛살","quantity":"100g"},{"name":"아보카도","quantity":"1개"},{"name":"김","quantity":"3장"},{"name":"오이","quantity":"1/2개"},{"name":"초밥 식초","quantity":"3큰술"}]',
 '{"ko":["초밥 밥을 준비한다","김 위에 밥을 펴고 뒤집는다","게맛살, 아보카도, 오이를 올린다","김밥처럼 말아준다","한 입 크기로 자른다","통깨를 뿌려 마무리한다"]}',
 ARRAY['mild','seafood','light','rice']),

('japanese-004', 'seed',
 '{"ko":"모듬 사시미","en":"Assorted Sashimi","ja":"刺身盛り合わせ","zh":"综合生鱼片"}',
 '{"ko":"다양한 신선한 생선회 모듬","en":"Assorted fresh raw fish platter"}',
 15, 'easy', 2,
 '[{"name":"연어 회","quantity":"100g"},{"name":"참치 회","quantity":"100g"},{"name":"광어 회","quantity":"100g"},{"name":"무","quantity":"약간"},{"name":"와사비","quantity":"약간"},{"name":"간장","quantity":"약간"}]',
 '{"ko":["무를 채 썬다","생선을 먹기 좋게 썬다","접시에 무채를 깔고 생선을 보기 좋게 담는다","와사비와 간장을 곁들인다"]}',
 ARRAY['raw','seafood','light','quick']),

('japanese-005', 'seed',
 '{"ko":"장어 초밥","en":"Eel Nigiri Sushi","ja":"うなぎ握り寿司","zh":"鳗鱼寿司"}',
 '{"ko":"달콤한 소스를 바른 구운 장어 초밥","en":"Grilled eel sushi with sweet sauce"}',
 25, 'medium', 2,
 '[{"name":"초밥용 쌀","quantity":"2컵"},{"name":"구운 장어","quantity":"150g"},{"name":"장어 소스","quantity":"3큰술"},{"name":"김","quantity":"1장"}]',
 '{"ko":["초밥 밥을 준비한다","장어를 먹기 좋게 자른다","밥을 뭉쳐 장어를 올린다","김으로 둘러 고정한다","장어 소스를 발라 마무리한다"]}',
 ARRAY['mild','seafood','grilled','rice']),

-- === 라멘 (Ramen) ===
('japanese-006', 'seed',
 '{"ko":"돈코츠 라멘","en":"Tonkotsu Ramen","ja":"とんこつラーメン","zh":"豚骨拉面"}',
 '{"ko":"진한 돼지뼈 육수의 정통 일본 라멘","en":"Traditional Japanese ramen with rich pork bone broth"}',
 120, 'hard', 2,
 '[{"name":"돼지뼈","quantity":"1kg"},{"name":"라멘 면","quantity":"2인분"},{"name":"차슈","quantity":"4장"},{"name":"파","quantity":"1대"},{"name":"계란","quantity":"2개"},{"name":"김","quantity":"2장"}]',
 '{"ko":["돼지뼈를 삶아 핏물을 빼고 씻는다","깨끗한 물에 뼈를 넣고 2시간 이상 끓인다","계란을 삶아 반숙으로 만든다","면을 삶는다","그릇에 육수를 담고 면을 넣는다","차슈, 계란, 파, 김을 올린다"]}',
 ARRAY['mild','soupy','noodle','meat','heavy']),

('japanese-007', 'seed',
 '{"ko":"미소 라멘","en":"Miso Ramen","ja":"味噌ラーメン","zh":"味噌拉面"}',
 '{"ko":"구수한 된장 육수의 일본 라멘","en":"Japanese ramen with savory miso broth"}',
 40, 'medium', 2,
 '[{"name":"라멘 면","quantity":"2인분"},{"name":"미소","quantity":"3큰술"},{"name":"돼지고기","quantity":"150g"},{"name":"숙주","quantity":"100g"},{"name":"옥수수","quantity":"50g"},{"name":"버터","quantity":"1큰술"}]',
 '{"ko":["육수를 끓이고 미소를 푼다","돼지고기를 볶는다","면을 삶아 그릇에 담는다","육수를 붓는다","돼지고기, 숙주, 옥수수, 버터를 올린다"]}',
 ARRAY['mild','soupy','noodle','meat','heavy']),

('japanese-008', 'seed',
 '{"ko":"쇼유 라멘","en":"Shoyu Ramen","ja":"醤油ラーメン","zh":"酱油拉面"}',
 '{"ko":"깔끔한 간장 육수의 정통 라멘","en":"Classic ramen with clear soy sauce broth"}',
 40, 'medium', 2,
 '[{"name":"라멘 면","quantity":"2인분"},{"name":"간장","quantity":"4큰술"},{"name":"닭 육수","quantity":"800ml"},{"name":"차슈","quantity":"4장"},{"name":"파","quantity":"1대"},{"name":"계란","quantity":"2개"}]',
 '{"ko":["닭 육수를 끓이고 간장으로 간한다","계란을 반숙으로 삶는다","면을 삶아 그릇에 담는다","육수를 붓는다","차슈, 계란, 파를 올린다"]}',
 ARRAY['mild','soupy','noodle','meat','heavy']),

('japanese-009', 'seed',
 '{"ko":"시오 라멘","en":"Shio Ramen","ja":"塩ラーメン","zh":"盐味拉面"}',
 '{"ko":"담백한 소금 육수의 라멘","en":"Light ramen with salt-based broth"}',
 40, 'medium', 2,
 '[{"name":"라멘 면","quantity":"2인분"},{"name":"소금","quantity":"2작은술"},{"name":"닭 육수","quantity":"800ml"},{"name":"돼지고기","quantity":"100g"},{"name":"파","quantity":"1대"}]',
 '{"ko":["닭 육수를 끓이고 소금으로 간한다","돼지고기를 볶는다","면을 삶아 그릇에 담는다","육수를 붓는다","돼지고기와 파를 올린다"]}',
 ARRAY['mild','soupy','noodle','meat','light']),

('japanese-010', 'seed',
 '{"ko":"매운 라멘","en":"Spicy Ramen","ja":"辛味ラーメン","zh":"辣味拉面"}',
 '{"ko":"고추기름이 들어간 매콤한 라멘","en":"Spicy ramen with chili oil"}',
 35, 'medium', 2,
 '[{"name":"라멘 면","quantity":"2인분"},{"name":"고추기름","quantity":"2큰술"},{"name":"미소","quantity":"2큰술"},{"name":"돼지고기","quantity":"150g"},{"name":"숙주","quantity":"100g"},{"name":"파","quantity":"1대"}]',
 '{"ko":["육수를 끓이고 미소와 고추기름을 넣는다","돼지고기를 볶는다","면을 삶아 그릇에 담는다","육수를 붓는다","돼지고기, 숙주, 파를 올린다"]}',
 ARRAY['spicy','soupy','noodle','meat','heavy']),

-- === 우동/소바 (Udon & Soba) ===
('japanese-011', 'seed',
 '{"ko":"가케 우동","en":"Kake Udon","ja":"かけうどん","zh":"汤乌冬面"}',
 '{"ko":"따뜻한 육수에 담긴 심플한 우동","en":"Simple udon in warm broth"}',
 15, 'easy', 1,
 '[{"name":"우동 면","quantity":"1인분"},{"name":"다시마 육수","quantity":"400ml"},{"name":"간장","quantity":"2큰술"},{"name":"미림","quantity":"1큰술"},{"name":"파","quantity":"약간"}]',
 '{"ko":["육수를 끓이고 간장과 미림으로 간한다","우동 면을 삶는다","그릇에 면을 담고 육수를 붓는다","파를 올린다"]}',
 ARRAY['mild','soupy','noodle','veggie','light','quick']),

('japanese-012', 'seed',
 '{"ko":"템푸라 우동","en":"Tempura Udon","ja":"天ぷらうどん","zh":"天妇罗乌冬面"}',
 '{"ko":"바삭한 새우 튀김이 올라간 우동","en":"Udon with crispy shrimp tempura"}',
 30, 'medium', 2,
 '[{"name":"우동 면","quantity":"2인분"},{"name":"새우","quantity":"6마리"},{"name":"튀김가루","quantity":"100g"},{"name":"다시마 육수","quantity":"800ml"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["새우에 튀김옷을 입혀 튀긴다","육수를 끓이고 간장으로 간한다","우동 면을 삶아 그릇에 담는다","육수를 붓는다","새우 튀김을 올린다"]}',
 ARRAY['mild','soupy','noodle','seafood','deep_fried']),

('japanese-013', 'seed',
 '{"ko":"카레 우동","en":"Curry Udon","ja":"カレーうどん","zh":"咖喱乌冬面"}',
 '{"ko":"진한 카레 국물의 우동","en":"Udon in rich curry broth"}',
 30, 'easy', 2,
 '[{"name":"우동 면","quantity":"2인분"},{"name":"카레 루","quantity":"2조각"},{"name":"돼지고기","quantity":"100g"},{"name":"양파","quantity":"1개"},{"name":"당근","quantity":"1/2개"},{"name":"다시마 육수","quantity":"800ml"}]',
 '{"ko":["돼지고기와 야채를 볶는다","육수를 붓고 끓인다","카레 루를 넣어 녹인다","우동 면을 삶아 그릇에 담는다","카레 육수를 붓는다"]}',
 ARRAY['mild','soupy','noodle','meat','heavy']),

('japanese-014', 'seed',
 '{"ko":"자루 소바","en":"Zaru Soba","ja":"ざるそば","zh":"冷荞麦面"}',
 '{"ko":"차갑게 먹는 메밀국수","en":"Cold buckwheat noodles"}',
 15, 'easy', 2,
 '[{"name":"소바 면","quantity":"2인분"},{"name":"소바 육수","quantity":"200ml"},{"name":"김","quantity":"1장"},{"name":"파","quantity":"1대"},{"name":"와사비","quantity":"약간"}]',
 '{"ko":["소바 면을 삶아 찬물에 헹군다","체에 담아 물기를 뺀다","김을 채 썬다","접시에 소바를 담고 김을 올린다","소바 육수에 파와 와사비를 넣어 찍어 먹는다"]}',
 ARRAY['mild','noodle','veggie','light','quick']),

('japanese-015', 'seed',
 '{"ko":"나베야키 우동","en":"Nabeyaki Udon","ja":"鍋焼きうどん","zh":"锅烧乌冬面"}',
 '{"ko":"뚝배기에 끓여낸 따끈한 우동","en":"Hot pot udon cooked in individual pot"}',
 25, 'easy', 1,
 '[{"name":"우동 면","quantity":"1인분"},{"name":"새우 튀김","quantity":"2개"},{"name":"계란","quantity":"1개"},{"name":"표고버섯","quantity":"2개"},{"name":"파","quantity":"1대"},{"name":"다시마 육수","quantity":"400ml"}]',
 '{"ko":["뚝배기에 육수를 붓고 끓인다","우동 면과 버섯을 넣는다","새우 튀김을 올린다","계란을 깨 넣는다","파를 올려 마무리한다"]}',
 ARRAY['mild','soupy','noodle','seafood','heavy']),

-- === 덮밥류 (Donburi - Rice Bowls) ===
('japanese-016', 'seed',
 '{"ko":"규동","en":"Gyudon","ja":"牛丼","zh":"牛肉盖饭"}',
 '{"ko":"달콤짭짤한 소고기 덮밥","en":"Sweet and savory beef rice bowl"}',
 20, 'easy', 2,
 '[{"name":"소고기 불고기용","quantity":"300g"},{"name":"양파","quantity":"1개"},{"name":"간장","quantity":"3큰술"},{"name":"미림","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"밥","quantity":"2공기"}]',
 '{"ko":["양파를 채 썬다","팬에 간장, 미림, 설탕을 넣고 끓인다","소고기와 양파를 넣고 볶는다","밥 위에 소고기를 올린다","국물을 끼얹고 파를 뿌린다"]}',
 ARRAY['mild','rice','meat','heavy','quick']),

('japanese-017', 'seed',
 '{"ko":"카츠동","en":"Katsudon","ja":"カツ丼","zh":"炸猪排盖饭"}',
 '{"ko":"돈까스와 계란으로 만든 덮밥","en":"Pork cutlet and egg rice bowl"}',
 25, 'medium', 2,
 '[{"name":"돈까스","quantity":"2장"},{"name":"계란","quantity":"3개"},{"name":"양파","quantity":"1개"},{"name":"간장","quantity":"2큰술"},{"name":"미림","quantity":"2큰술"},{"name":"밥","quantity":"2공기"}]',
 '{"ko":["돈까스를 튀긴다","팬에 간장, 미림, 양파를 넣고 끓인다","돈까스를 올리고 계란을 풀어 넣는다","뚜껑을 덮어 계란이 익으면 밥 위에 올린다"]}',
 ARRAY['mild','rice','meat','heavy','deep_fried']),

('japanese-018', 'seed',
 '{"ko":"오야코동","en":"Oyakodon","ja":"親子丼","zh":"鸡肉鸡蛋盖饭"}',
 '{"ko":"닭고기와 계란으로 만든 부모자식 덮밥","en":"Chicken and egg rice bowl"}',
 20, 'easy', 2,
 '[{"name":"닭고기","quantity":"200g"},{"name":"계란","quantity":"3개"},{"name":"양파","quantity":"1개"},{"name":"간장","quantity":"2큰술"},{"name":"미림","quantity":"2큰술"},{"name":"밥","quantity":"2공기"}]',
 '{"ko":["닭고기와 양파를 한 입 크기로 자른다","팬에 간장, 미림을 넣고 끓인다","닭고기와 양파를 넣고 익힌다","계란을 풀어 넣고 반숙으로 만든다","밥 위에 올린다"]}',
 ARRAY['mild','rice','meat','heavy','quick']),

('japanese-019', 'seed',
 '{"ko":"텐동","en":"Tendon","ja":"天丼","zh":"天妇罗盖饭"}',
 '{"ko":"각종 튀김을 올린 일본식 덮밥","en":"Rice bowl with assorted tempura"}',
 30, 'medium', 2,
 '[{"name":"새우","quantity":"6마리"},{"name":"가지","quantity":"1개"},{"name":"고구마","quantity":"1개"},{"name":"튀김가루","quantity":"100g"},{"name":"텐동 소스","quantity":"3큰술"},{"name":"밥","quantity":"2공기"}]',
 '{"ko":["새우와 야채를 튀김옷 입혀 튀긴다","밥을 그릇에 담는다","튀김을 밥 위에 올린다","텐동 소스를 끼얹는다"]}',
 ARRAY['mild','rice','seafood','veggie','deep_fried']),

('japanese-020', 'seed',
 '{"ko":"우나기동","en":"Unagidon","ja":"うな丼","zh":"鳗鱼盖饭"}',
 '{"ko":"구운 장어를 올린 덮밥","en":"Grilled eel rice bowl"}',
 20, 'easy', 2,
 '[{"name":"구운 장어","quantity":"200g"},{"name":"장어 소스","quantity":"4큰술"},{"name":"밥","quantity":"2공기"},{"name":"산초가루","quantity":"약간"}]',
 '{"ko":["밥을 그릇에 담는다","구운 장어를 데운다","밥 위에 장어를 올린다","장어 소스를 끼얹는다","산초가루를 뿌린다"]}',
 ARRAY['mild','rice','seafood','grilled']),

-- === 튀김요리 (Tempura & Fried) ===
('japanese-021', 'seed',
 '{"ko":"새우 템푸라","en":"Shrimp Tempura","ja":"海老天ぷら","zh":"炸虾天妇罗"}',
 '{"ko":"바삭하게 튀긴 일본식 새우튀김","en":"Crispy Japanese-style fried shrimp"}',
 20, 'medium', 2,
 '[{"name":"새우","quantity":"8마리"},{"name":"튀김가루","quantity":"100g"},{"name":"얼음물","quantity":"100ml"},{"name":"계란","quantity":"1개"},{"name":"튀김기름","quantity":"적당량"}]',
 '{"ko":["새우 내장을 제거하고 꼬리만 남긴다","차가운 튀김옷을 만든다","새우에 튀김옷을 얇게 입힌다","180도 기름에 튀긴다","텐츠유 소스에 찍어 먹는다"]}',
 ARRAY['mild','seafood','light','deep_fried']),

('japanese-022', 'seed',
 '{"ko":"모듬 템푸라","en":"Assorted Tempura","ja":"天ぷら盛り合わせ","zh":"综合天妇罗"}',
 '{"ko":"새우와 야채로 만든 모듬 튀김","en":"Assorted tempura with shrimp and vegetables"}',
 30, 'medium', 2,
 '[{"name":"새우","quantity":"4마리"},{"name":"가지","quantity":"1개"},{"name":"고구마","quantity":"1개"},{"name":"피망","quantity":"1개"},{"name":"튀김가루","quantity":"150g"}]',
 '{"ko":["모든 재료를 먹기 좋게 자른다","차가운 튀김옷을 만든다","재료에 튀김옷을 입혀 튀긴다","무채와 텐츠유를 곁들인다"]}',
 ARRAY['mild','seafood','veggie','light','deep_fried']),

('japanese-023', 'seed',
 '{"ko":"돈까스","en":"Tonkatsu","ja":"とんかつ","zh":"日式炸猪排"}',
 '{"ko":"두툼한 돼지고기 등심 튀김","en":"Thick fried pork cutlet"}',
 25, 'medium', 2,
 '[{"name":"돼지고기 등심","quantity":"2장"},{"name":"빵가루","quantity":"100g"},{"name":"계란","quantity":"2개"},{"name":"밀가루","quantity":"50g"},{"name":"양배추","quantity":"1/4통"}]',
 '{"ko":["고기를 두들겨 펴고 칼집을 낸다","밀가루, 계란, 빵가루 순으로 입힌다","170도 기름에 튀긴다","채 썬 양배추와 함께 담는다","돈까스 소스를 곁들인다"]}',
 ARRAY['mild','meat','heavy','deep_fried']),

('japanese-024', 'seed',
 '{"ko":"치킨 가라아게","en":"Chicken Karaage","ja":"鶏の唐揚げ","zh":"日式炸鸡"}',
 '{"ko":"일본식 간장 양념 닭튀김","en":"Japanese-style soy sauce fried chicken"}',
 30, 'easy', 2,
 '[{"name":"닭다리살","quantity":"300g"},{"name":"간장","quantity":"2큰술"},{"name":"마늘","quantity":"1큰술"},{"name":"생강","quantity":"1작은술"},{"name":"감자전분","quantity":"50g"}]',
 '{"ko":["닭고기를 한 입 크기로 자른다","간장, 마늘, 생강으로 양념한다","30분 재운 후 감자전분을 묻힌다","180도 기름에 튀긴다","레몬을 곁들여 낸다"]}',
 ARRAY['mild','meat','heavy','deep_fried','quick']),

('japanese-025', 'seed',
 '{"ko":"고로케","en":"Korokke","ja":"コロッケ","zh":"日式可乐饼"}',
 '{"ko":"감자와 고기로 만든 일본식 크로켓","en":"Japanese-style potato and meat croquette"}',
 40, 'medium', 4,
 '[{"name":"감자","quantity":"4개"},{"name":"다진 소고기","quantity":"150g"},{"name":"양파","quantity":"1개"},{"name":"빵가루","quantity":"100g"},{"name":"계란","quantity":"2개"}]',
 '{"ko":["감자를 삶아 으깬다","다진 고기와 양파를 볶는다","감자와 고기를 섞어 모양을 만든다","밀가루, 계란, 빵가루를 입힌다","튀겨서 소스와 함께 낸다"]}',
 ARRAY['mild','meat','heavy','deep_fried']),

-- === 구이요리 (Grilled) ===
('japanese-026', 'seed',
 '{"ko":"야키토리","en":"Yakitori","ja":"焼き鳥","zh":"烤鸡串"}',
 '{"ko":"간장 소스로 구운 닭꼬치","en":"Grilled chicken skewers with soy sauce"}',
 25, 'easy', 2,
 '[{"name":"닭다리살","quantity":"300g"},{"name":"파","quantity":"2대"},{"name":"간장","quantity":"3큰술"},{"name":"미림","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["닭고기를 한 입 크기로 자른다","꼬치에 닭고기와 파를 번갈아 꿴다","간장, 미림, 설탕을 섞어 소스를 만든다","구우면서 소스를 발라준다"]}',
 ARRAY['mild','meat','grilled','quick']),

('japanese-027', 'seed',
 '{"ko":"야키니쿠","en":"Yakiniku","ja":"焼肉","zh":"日式烤肉"}',
 '{"ko":"일본식 석쇠 구이 고기","en":"Japanese-style grilled meat"}',
 20, 'easy', 2,
 '[{"name":"소고기 구이용","quantity":"300g"},{"name":"야키니쿠 소스","quantity":"3큰술"},{"name":"상추","quantity":"4장"},{"name":"마늘","quantity":"3쪽"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["고기를 먹기 좋게 자른다","팬이나 석쇠를 달군다","고기를 구워가며 야키니쿠 소스를 찍어 먹는다","상추에 싸 먹는다"]}',
 ARRAY['mild','meat','grilled','quick']),

('japanese-028', 'seed',
 '{"ko":"사바 시오야키","en":"Grilled Mackerel","ja":"鯖の塩焼き","zh":"盐烤青花鱼"}',
 '{"ko":"소금구이한 고등어","en":"Salt-grilled mackerel"}',
 20, 'easy', 2,
 '[{"name":"고등어","quantity":"2마리"},{"name":"소금","quantity":"적당량"},{"name":"무","quantity":"약간"},{"name":"간장","quantity":"약간"}]',
 '{"ko":["고등어에 소금을 뿌려 10분 둔다","석쇠나 오븐에 굽는다","무채와 간장을 곁들여 낸다"]}',
 ARRAY['mild','seafood','grilled','light','quick']),

('japanese-029', 'seed',
 '{"ko":"테리야키 치킨","en":"Teriyaki Chicken","ja":"照り焼きチキン","zh":"照烧鸡肉"}',
 '{"ko":"달콤한 테리야키 소스의 닭고기 구이","en":"Chicken grilled with sweet teriyaki sauce"}',
 25, 'easy', 2,
 '[{"name":"닭다리살","quantity":"2장"},{"name":"간장","quantity":"3큰술"},{"name":"미림","quantity":"3큰술"},{"name":"설탕","quantity":"2큰술"},{"name":"생강","quantity":"1작은술"}]',
 '{"ko":["닭고기를 팬에 굽는다","간장, 미림, 설탕, 생강을 섞어 소스를 만든다","닭고기가 익으면 소스를 넣고 졸인다","윤기나게 마무리한다"]}',
 ARRAY['mild','meat','grilled','quick']),

('japanese-030', 'seed',
 '{"ko":"미소 된장 가지구이","en":"Miso Eggplant","ja":"茄子の味噌焼き","zh":"味噌烤茄子"}',
 '{"ko":"된장 소스를 바른 가지구이","en":"Grilled eggplant with miso sauce"}',
 20, 'easy', 2,
 '[{"name":"가지","quantity":"2개"},{"name":"미소","quantity":"2큰술"},{"name":"미림","quantity":"1큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"참깨","quantity":"약간"}]',
 '{"ko":["가지를 반으로 자르고 칼집을 낸다","미소, 미림, 설탕을 섞어 소스를 만든다","가지를 구워 소스를 바른다","참깨를 뿌려 마무리한다"]}',
 ARRAY['mild','veggie','grilled','light','quick']),

-- === 나베/전골 (Hot Pot) ===
('japanese-031', 'seed',
 '{"ko":"샤브샤브","en":"Shabu Shabu","ja":"しゃぶしゃぶ","zh":"涮涮锅"}',
 '{"ko":"얇은 고기와 야채를 데쳐 먹는 전골","en":"Hot pot with thinly sliced meat and vegetables"}',
 30, 'easy', 4,
 '[{"name":"샤브샤브용 소고기","quantity":"300g"},{"name":"배추","quantity":"1/4통"},{"name":"두부","quantity":"1모"},{"name":"버섯","quantity":"100g"},{"name":"다시마","quantity":"1장"},{"name":"폰즈 소스","quantity":"적당량"}]',
 '{"ko":["냄비에 물과 다시마를 넣고 끓인다","야채와 두부를 준비한다","고기와 야채를 데쳐 먹는다","폰즈 소스에 찍어 먹는다"]}',
 ARRAY['mild','soupy','meat','veggie','light']),

('japanese-032', 'seed',
 '{"ko":"스키야키","en":"Sukiyaki","ja":"すき焼き","zh":"寿喜烧"}',
 '{"ko":"달콤짭짤한 간장 육수의 소고기 전골","en":"Beef hot pot with sweet soy sauce broth"}',
 30, 'medium', 4,
 '[{"name":"소고기 불고기용","quantity":"400g"},{"name":"배추","quantity":"1/4통"},{"name":"두부","quantity":"1모"},{"name":"당면","quantity":"100g"},{"name":"간장","quantity":"4큰술"},{"name":"설탕","quantity":"3큰술"}]',
 '{"ko":["냄비에 간장, 설탕, 미림을 섞어 육수를 만든다","소고기를 먼저 볶는다","야채와 두부, 당면을 넣고 끓인다","날계란에 찍어 먹는다"]}',
 ARRAY['mild','soupy','meat','veggie','heavy']),

('japanese-033', 'seed',
 '{"ko":"치리나베","en":"Chirinabe","ja":"ちり鍋","zh":"鱼片火锅"}',
 '{"ko":"흰살생선과 야채의 맑은 전골","en":"Clear hot pot with white fish and vegetables"}',
 30, 'easy', 4,
 '[{"name":"흰살생선","quantity":"300g"},{"name":"배추","quantity":"1/4통"},{"name":"두부","quantity":"1모"},{"name":"버섯","quantity":"100g"},{"name":"다시마","quantity":"1장"},{"name":"폰즈 소스","quantity":"적당량"}]',
 '{"ko":["냄비에 다시마 육수를 끓인다","야채와 두부를 넣는다","생선을 넣고 익힌다","폰즈 소스에 찍어 먹는다"]}',
 ARRAY['mild','soupy','seafood','veggie','light']),

('japanese-034', 'seed',
 '{"ko":"모츠나베","en":"Motsunabe","ja":"もつ鍋","zh":"内脏火锅"}',
 '{"ko":"소 곱창 전골","en":"Beef offal hot pot"}',
 40, 'medium', 4,
 '[{"name":"소 곱창","quantity":"300g"},{"name":"부추","quantity":"1단"},{"name":"양배추","quantity":"1/4통"},{"name":"두부","quantity":"1모"},{"name":"미소","quantity":"3큰술"},{"name":"마늘","quantity":"5쪽"}]',
 '{"ko":["곱창을 깨끗이 씻는다","냄비에 육수를 끓이고 미소를 푼다","곱창과 마늘을 넣고 끓인다","야채와 두부를 넣어 익힌다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('japanese-035', 'seed',
 '{"ko":"요세나베","en":"Yosenabe","ja":"寄せ鍋","zh":"杂烩火锅"}',
 '{"ko":"해산물과 고기가 들어간 모듬 전골","en":"Mixed hot pot with seafood and meat"}',
 35, 'easy', 4,
 '[{"name":"새우","quantity":"4마리"},{"name":"생선","quantity":"150g"},{"name":"닭고기","quantity":"100g"},{"name":"배추","quantity":"1/4통"},{"name":"두부","quantity":"1모"},{"name":"버섯","quantity":"100g"}]',
 '{"ko":["냄비에 다시마 육수를 끓인다","닭고기를 먼저 넣는다","해산물과 야채를 넣고 끓인다","간장으로 간하여 마무리한다"]}',
 ARRAY['mild','soupy','seafood','meat','heavy']),

-- === 카레 (Curry) ===
('japanese-036', 'seed',
 '{"ko":"일본 카레","en":"Japanese Curry","ja":"カレーライス","zh":"日式咖喱饭"}',
 '{"ko":"감자와 당근이 들어간 일본식 카레","en":"Japanese-style curry with potatoes and carrots"}',
 40, 'easy', 4,
 '[{"name":"카레 루","quantity":"4조각"},{"name":"돼지고기","quantity":"200g"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"밥","quantity":"4공기"}]',
 '{"ko":["고기와 야채를 한 입 크기로 자른다","팬에 기름을 두르고 재료를 볶는다","물을 붓고 15분 끓인다","카레 루를 넣어 녹인다","밥과 함께 담아낸다"]}',
 ARRAY['mild','rice','meat','heavy']),

('japanese-037', 'seed',
 '{"ko":"카츠 카레","en":"Katsu Curry","ja":"カツカレー","zh":"炸猪排咖喱"}',
 '{"ko":"돈까스가 올라간 카레라이스","en":"Curry rice with pork cutlet"}',
 40, 'medium', 2,
 '[{"name":"돈까스","quantity":"2장"},{"name":"카레 루","quantity":"3조각"},{"name":"감자","quantity":"1개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"밥","quantity":"2공기"}]',
 '{"ko":["돈까스를 튀긴다","카레를 끓인다","밥을 그릇에 담고 카레를 붓는다","돈까스를 올린다"]}',
 ARRAY['mild','rice','meat','heavy','deep_fried']),

('japanese-038', 'seed',
 '{"ko":"해산물 카레","en":"Seafood Curry","ja":"シーフードカレー","zh":"海鲜咖喱"}',
 '{"ko":"새우와 오징어가 들어간 카레","en":"Curry with shrimp and squid"}',
 35, 'easy', 4,
 '[{"name":"새우","quantity":"8마리"},{"name":"오징어","quantity":"1마리"},{"name":"카레 루","quantity":"4조각"},{"name":"양파","quantity":"1개"},{"name":"토마토","quantity":"1개"},{"name":"밥","quantity":"4공기"}]',
 '{"ko":["해산물을 손질한다","양파와 토마토를 볶는다","물을 붓고 끓인다","해산물을 넣는다","카레 루를 녹여 밥과 함께 낸다"]}',
 ARRAY['mild','rice','seafood','heavy']),

('japanese-039', 'seed',
 '{"ko":"야채 카레","en":"Vegetable Curry","ja":"野菜カレー","zh":"蔬菜咖喱"}',
 '{"ko":"다양한 야채가 듬뿍 들어간 카레","en":"Curry packed with various vegetables"}',
 35, 'easy', 4,
 '[{"name":"카레 루","quantity":"4조각"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"가지","quantity":"1개"},{"name":"피망","quantity":"1개"},{"name":"양파","quantity":"1개"}]',
 '{"ko":["모든 야채를 한 입 크기로 자른다","팬에 야채를 볶는다","물을 붓고 야채가 익을 때까지 끓인다","카레 루를 넣어 녹인다","밥과 함께 낸다"]}',
 ARRAY['mild','rice','veggie','light']),

('japanese-040', 'seed',
 '{"ko":"치킨 카레","en":"Chicken Curry","ja":"チキンカレー","zh":"鸡肉咖喱"}',
 '{"ko":"부드러운 닭고기가 들어간 카레","en":"Curry with tender chicken"}',
 40, 'easy', 4,
 '[{"name":"닭다리살","quantity":"300g"},{"name":"카레 루","quantity":"4조각"},{"name":"감자","quantity":"2개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"밥","quantity":"4공기"}]',
 '{"ko":["닭고기를 한 입 크기로 자른다","팬에 닭고기와 야채를 볶는다","물을 붓고 20분 끓인다","카레 루를 넣어 녹인다","밥과 함께 담아낸다"]}',
 ARRAY['mild','rice','meat','heavy']),

-- === 이자카야 안주 (Izakaya Dishes) ===
('japanese-041', 'seed',
 '{"ko":"에다마메","en":"Edamame","ja":"枝豆","zh":"毛豆"}',
 '{"ko":"소금을 뿌린 삶은 완두콩","en":"Boiled soybeans with salt"}',
 10, 'easy', 2,
 '[{"name":"에다마메","quantity":"200g"},{"name":"소금","quantity":"1큰술"}]',
 '{"ko":["물을 끓인다","에다마메를 넣고 5분 삶는다","건져서 소금을 뿌린다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-042', 'seed',
 '{"ko":"교자","en":"Gyoza","ja":"餃子","zh":"煎饺"}',
 '{"ko":"일본식 군만두","en":"Japanese pan-fried dumplings"}',
 30, 'medium', 2,
 '[{"name":"만두피","quantity":"20장"},{"name":"다진 돼지고기","quantity":"150g"},{"name":"배추","quantity":"100g"},{"name":"부추","quantity":"30g"},{"name":"마늘","quantity":"1큰술"},{"name":"생강","quantity":"1작은술"}]',
 '{"ko":["배추와 부추를 잘게 썬다","다진 고기와 야채, 양념을 섞는다","만두피에 소를 넣고 빚는다","팬에 기름을 두르고 굽는다","물을 넣고 뚜껑을 덮어 찐다"]}',
 ARRAY['mild','meat','side_dish','deep_fried']),

('japanese-043', 'seed',
 '{"ko":"타코야키","en":"Takoyaki","ja":"たこ焼き","zh":"章鱼烧"}',
 '{"ko":"문어가 들어간 일본식 공 모양 간식","en":"Japanese octopus balls"}',
 25, 'medium', 2,
 '[{"name":"타코야키 가루","quantity":"100g"},{"name":"문어","quantity":"100g"},{"name":"파","quantity":"2대"},{"name":"타코야키 소스","quantity":"적당량"},{"name":"가다랑이포","quantity":"적당량"}]',
 '{"ko":["반죽을 만든다","타코야키 팬을 달군다","반죽을 붓고 문어와 파를 넣는다","동그랗게 굴려가며 굽는다","소스와 가다랑이포를 올린다"]}',
 ARRAY['mild','seafood','light','side_dish']),

('japanese-044', 'seed',
 '{"ko":"아게다시 도후","en":"Agedashi Tofu","ja":"揚げ出し豆腐","zh":"炸豆腐"}',
 '{"ko":"튀긴 두부에 육수를 부은 요리","en":"Fried tofu in dashi broth"}',
 20, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"감자전분","quantity":"3큰술"},{"name":"다시마 육수","quantity":"200ml"},{"name":"간장","quantity":"2큰술"},{"name":"미림","quantity":"1큰술"}]',
 '{"ko":["두부를 물기 빼고 네모지게 자른다","감자전분을 묻혀 튀긴다","육수, 간장, 미림을 끓인다","두부를 그릇에 담고 육수를 붓는다","파와 무채를 올린다"]}',
 ARRAY['mild','veggie','light','deep_fried','side_dish']),

('japanese-045', 'seed',
 '{"ko":"차슈","en":"Chashu","ja":"チャーシュー","zh":"叉烧"}',
 '{"ko":"일본식 돼지고기 구이","en":"Japanese braised pork"}',
 90, 'medium', 4,
 '[{"name":"돼지고기 삼겹살","quantity":"500g"},{"name":"간장","quantity":"100ml"},{"name":"미림","quantity":"50ml"},{"name":"설탕","quantity":"2큰술"},{"name":"마늘","quantity":"3쪽"},{"name":"생강","quantity":"1조각"}]',
 '{"ko":["돼지고기를 묶어 모양을 잡는다","팬에 겉면을 굽는다","냄비에 간장, 미림, 설탕을 넣고 끓인다","고기를 넣고 1시간 조린다","식혀서 얇게 썬다"]}',
 ARRAY['mild','meat','heavy','grilled']),

-- === 오코노미야키/테판야키 (Okonomiyaki & Teppanyaki) ===
('japanese-046', 'seed',
 '{"ko":"오코노미야키","en":"Okonomiyaki","ja":"お好み焼き","zh":"大阪烧"}',
 '{"ko":"일본식 야채 팬케이크","en":"Japanese savory pancake"}',
 25, 'easy', 2,
 '[{"name":"밀가루","quantity":"100g"},{"name":"양배추","quantity":"200g"},{"name":"계란","quantity":"2개"},{"name":"돼지고기","quantity":"100g"},{"name":"오코노미야키 소스","quantity":"적당량"}]',
 '{"ko":["양배추를 채 썬다","밀가루, 계란, 물을 섞어 반죽을 만든다","양배추를 넣고 섞는다","팬에 기름을 두르고 반죽을 부은 뒤 돼지고기를 올린다","뒤집어 가며 굽는다","소스와 마요네즈, 가다랑이포를 올린다"]}',
 ARRAY['mild','meat','veggie','heavy']),

('japanese-047', 'seed',
 '{"ko":"모던야키","en":"Modanyaki","ja":"モダン焼き","zh":"摩登烧"}',
 '{"ko":"야키소바가 들어간 오코노미야키","en":"Okonomiyaki with yakisoba noodles"}',
 30, 'medium', 2,
 '[{"name":"오코노미야키 반죽","quantity":"1인분"},{"name":"야키소바 면","quantity":"1인분"},{"name":"돼지고기","quantity":"100g"},{"name":"양배추","quantity":"100g"},{"name":"오코노미야키 소스","quantity":"적당량"}]',
 '{"ko":["오코노미야키 반죽을 준비한다","팬에 반죽을 부은 뒤 야키소바를 올린다","돼지고기를 올리고 뒤집는다","소스와 마요네즈를 뿌린다"]}',
 ARRAY['mild','meat','noodle','heavy']),

('japanese-048', 'seed',
 '{"ko":"야키소바","en":"Yakisoba","ja":"焼きそば","zh":"炒面"}',
 '{"ko":"일본식 볶음면","en":"Japanese stir-fried noodles"}',
 15, 'easy', 2,
 '[{"name":"야키소바 면","quantity":"2인분"},{"name":"돼지고기","quantity":"100g"},{"name":"양배추","quantity":"100g"},{"name":"당근","quantity":"1/2개"},{"name":"야키소바 소스","quantity":"3큰술"}]',
 '{"ko":["야채와 고기를 한 입 크기로 자른다","팬에 고기를 먼저 볶는다","야채를 넣고 볶는다","면을 넣고 볶는다","소스를 넣어 마무리한다"]}',
 ARRAY['mild','noodle','meat','stir_fry','quick']),

('japanese-049', 'seed',
 '{"ko":"히로시마야키","en":"Hiroshimayaki","ja":"広島焼き","zh":"广岛烧"}',
 '{"ko":"히로시마식 층층이 쌓은 오코노미야키","en":"Hiroshima-style layered okonomiyaki"}',
 35, 'hard', 2,
 '[{"name":"밀가루","quantity":"100g"},{"name":"양배추","quantity":"300g"},{"name":"야키소바 면","quantity":"2인분"},{"name":"돼지고기","quantity":"150g"},{"name":"계란","quantity":"2개"}]',
 '{"ko":["얇게 크레이프처럼 반죽을 부른다","양배추를 듬뿍 올린다","야키소바를 올린다","돼지고기를 올리고 뒤집는다","계란을 부어 그 위에 올린다","소스를 발라 완성한다"]}',
 ARRAY['mild','meat','noodle','heavy']),

('japanese-050', 'seed',
 '{"ko":"텟판 스테이크","en":"Teppan Steak","ja":"鉄板ステーキ","zh":"铁板牛排"}',
 '{"ko":"철판에 구운 스테이크","en":"Steak grilled on iron plate"}',
 20, 'easy', 2,
 '[{"name":"소고기 스테이크","quantity":"2장"},{"name":"마늘","quantity":"3쪽"},{"name":"버터","quantity":"2큰술"},{"name":"간장","quantity":"1큰술"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["고기에 소금, 후추로 밑간한다","철판을 달군다","마늘을 먼저 굽는다","고기를 올려 원하는 정도로 굽는다","버터와 간장을 발라 마무리한다"]}',
 ARRAY['mild','meat','grilled','heavy']),

-- === 도시락/반찬 (Bento & Side Dishes) ===
('japanese-051', 'seed',
 '{"ko":"타마고야키","en":"Tamagoyaki","ja":"卵焼き","zh":"日式煎蛋卷"}',
 '{"ko":"일본식 달걀말이","en":"Japanese rolled omelette"}',
 15, 'easy', 2,
 '[{"name":"계란","quantity":"3개"},{"name":"설탕","quantity":"1큰술"},{"name":"소금","quantity":"약간"},{"name":"다시마 육수","quantity":"2큰술"}]',
 '{"ko":["계란에 설탕, 소금, 육수를 넣고 섞는다","팬에 기름을 두르고 달군다","계란물을 조금씩 부어 말아준다","반복해서 두툼하게 만든다","식혀서 먹기 좋게 자른다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-052', 'seed',
 '{"ko":"킨피라 고보","en":"Kinpira Gobo","ja":"きんぴらごぼう","zh":"金平牛蒡"}',
 '{"ko":"우엉과 당근 볶음","en":"Stir-fried burdock root and carrot"}',
 20, 'easy', 2,
 '[{"name":"우엉","quantity":"1개"},{"name":"당근","quantity":"1/2개"},{"name":"간장","quantity":"2큰술"},{"name":"미림","quantity":"1큰술"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["우엉과 당근을 채 썬다","팬에 참기름을 두르고 우엉을 볶는다","당근을 넣고 볶는다","간장과 미림을 넣고 볶는다","통깨를 뿌린다"]}',
 ARRAY['mild','veggie','light','stir_fry','side_dish']),

('japanese-053', 'seed',
 '{"ko":"히지키 조림","en":"Simmered Hijiki","ja":"ひじきの煮物","zh":"羊栖菜煮物"}',
 '{"ko":"히지키 해조류 조림","en":"Simmered hijiki seaweed"}',
 25, 'easy', 2,
 '[{"name":"히지키","quantity":"30g"},{"name":"당근","quantity":"1/2개"},{"name":"유부","quantity":"2장"},{"name":"간장","quantity":"2큰술"},{"name":"미림","quantity":"1큰술"}]',
 '{"ko":["히지키를 물에 불린다","당근과 유부를 채 썬다","팬에 재료를 볶는다","간장, 미림을 넣고 조린다"]}',
 ARRAY['mild','veggie','seafood','light','side_dish']),

('japanese-054', 'seed',
 '{"ko":"호렌소 오히타시","en":"Spinach Ohitashi","ja":"ほうれん草のおひたし","zh":"凉拌菠菜"}',
 '{"ko":"시금치 무침","en":"Blanched spinach with soy sauce"}',
 10, 'easy', 2,
 '[{"name":"시금치","quantity":"200g"},{"name":"간장","quantity":"1큰술"},{"name":"다시마 육수","quantity":"2큰술"},{"name":"가다랑이포","quantity":"약간"}]',
 '{"ko":["시금치를 데친다","찬물에 헹구고 물기를 짠다","먹기 좋게 자른다","간장과 육수를 섞어 부른다","가다랑이포를 올린다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-055', 'seed',
 '{"ko":"니쿠자가","en":"Nikujaga","ja":"肉じゃが","zh":"土豆炖肉"}',
 '{"ko":"고기와 감자 조림","en":"Simmered meat and potatoes"}',
 35, 'easy', 2,
 '[{"name":"소고기","quantity":"150g"},{"name":"감자","quantity":"3개"},{"name":"당근","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"간장","quantity":"3큰술"},{"name":"미림","quantity":"2큰술"}]',
 '{"ko":["고기와 야채를 한 입 크기로 자른다","팬에 고기를 볶는다","야채를 넣고 볶는다","물, 간장, 미림을 넣고 끓인다","감자가 부드러워질 때까지 조린다"]}',
 ARRAY['mild','meat','veggie','heavy','side_dish']),

('japanese-056', 'seed',
 '{"ko":"츠케모노","en":"Tsukemono","ja":"漬物","zh":"日式腌菜"}',
 '{"ko":"일본식 절임 야채","en":"Japanese pickled vegetables"}',
 20, 'easy', 4,
 '[{"name":"오이","quantity":"2개"},{"name":"무","quantity":"1/4개"},{"name":"소금","quantity":"2큰술"},{"name":"식초","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["야채를 얇게 썬다","소금에 절여 물기를 뺀다","식초와 설탕을 섞어 절임물을 만든다","야채를 담가 30분 둔다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-057', 'seed',
 '{"ko":"고마에 아에","en":"Gomae","ja":"胡麻和え","zh":"芝麻拌菜"}',
 '{"ko":"참깨 소스로 버무린 야채","en":"Vegetables dressed with sesame sauce"}',
 15, 'easy', 2,
 '[{"name":"시금치","quantity":"200g"},{"name":"볶은 참깨","quantity":"3큰술"},{"name":"간장","quantity":"1큰술"},{"name":"설탕","quantity":"1작은술"}]',
 '{"ko":["시금치를 데쳐 물기를 짠다","참깨를 갈아 간장, 설탕과 섞는다","시금치에 참깨 소스를 버무린다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-058', 'seed',
 '{"ko":"다시마키 타마고","en":"Dashimaki Tamago","ja":"だし巻き卵","zh":"高汤蛋卷"}',
 '{"ko":"육수를 넣은 일본식 달걀말이","en":"Japanese rolled omelette with dashi"}',
 15, 'easy', 2,
 '[{"name":"계란","quantity":"3개"},{"name":"다시마 육수","quantity":"3큰술"},{"name":"간장","quantity":"1작은술"},{"name":"미림","quantity":"1작은술"}]',
 '{"ko":["계란에 육수, 간장, 미림을 섞는다","팬에 기름을 두르고 계란물을 부어 말아준다","반복해서 두툼하게 만든다","식혀서 자른다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-059', 'seed',
 '{"ko":"나마스","en":"Namasu","ja":"紅白なます","zh":"醋拌萝卜"}',
 '{"ko":"무와 당근 식초 절임","en":"Pickled daikon and carrot with vinegar"}',
 20, 'easy', 4,
 '[{"name":"무","quantity":"1/2개"},{"name":"당근","quantity":"1/2개"},{"name":"식초","quantity":"3큰술"},{"name":"설탕","quantity":"2큰술"},{"name":"소금","quantity":"1작은술"}]',
 '{"ko":["무와 당근을 채 썬다","소금에 절여 물기를 뺀다","식초와 설탕을 섞는다","야채에 부어 30분 재운다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-060', 'seed',
 '{"ko":"니모노","en":"Nimono","ja":"煮物","zh":"炖菜"}',
 '{"ko":"일본식 야채 조림","en":"Japanese simmered vegetables"}',
 30, 'easy', 4,
 '[{"name":"무","quantity":"1/2개"},{"name":"당근","quantity":"1개"},{"name":"곤약","quantity":"1팩"},{"name":"간장","quantity":"3큰술"},{"name":"미림","quantity":"2큰술"},{"name":"다시마 육수","quantity":"400ml"}]',
 '{"ko":["야채를 큼직하게 자른다","냄비에 육수를 끓인다","야채를 넣고 간장, 미림으로 간한다","약불로 20분 조린다"]}',
 ARRAY['mild','veggie','light','side_dish']),

-- === 해산물 요리 (Seafood) ===
('japanese-061', 'seed',
 '{"ko":"에비 프라이","en":"Ebi Fry","ja":"海老フライ","zh":"炸虾"}',
 '{"ko":"빵가루 입힌 새우튀김","en":"Breaded fried shrimp"}',
 25, 'medium', 2,
 '[{"name":"새우","quantity":"8마리"},{"name":"밀가루","quantity":"50g"},{"name":"계란","quantity":"2개"},{"name":"빵가루","quantity":"100g"},{"name":"타르타르 소스","quantity":"적당량"}]',
 '{"ko":["새우 내장을 제거하고 펴서 칼집을 낸다","밀가루, 계란, 빵가루 순으로 입힌다","180도 기름에 튀긴다","타르타르 소스를 곁들인다"]}',
 ARRAY['mild','seafood','light','deep_fried']),

('japanese-062', 'seed',
 '{"ko":"사케 시오야키","en":"Grilled Salmon","ja":"鮭の塩焼き","zh":"盐烤三文鱼"}',
 '{"ko":"소금구이한 연어","en":"Salt-grilled salmon"}',
 15, 'easy', 2,
 '[{"name":"연어","quantity":"2토막"},{"name":"소금","quantity":"약간"},{"name":"레몬","quantity":"1/2개"}]',
 '{"ko":["연어에 소금을 뿌려 10분 둔다","그릴이나 오븐에 굽는다","레몬을 곁들여 낸다"]}',
 ARRAY['mild','seafood','grilled','light','quick']),

('japanese-063', 'seed',
 '{"ko":"부리 테리야키","en":"Yellowtail Teriyaki","ja":"ブリの照り焼き","zh":"照烧黄尾鱼"}',
 '{"ko":"방어 데리야키 구이","en":"Grilled yellowtail with teriyaki sauce"}',
 20, 'easy', 2,
 '[{"name":"방어","quantity":"2토막"},{"name":"간장","quantity":"3큰술"},{"name":"미림","quantity":"3큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["방어를 팬에 굽는다","간장, 미림, 설탕을 섞어 소스를 만든다","생선이 익으면 소스를 넣고 졸인다","윤기나게 마무리한다"]}',
 ARRAY['mild','seafood','grilled','light','quick']),

('japanese-064', 'seed',
 '{"ko":"카키 후라이","en":"Fried Oyster","ja":"カキフライ","zh":"炸牡蛎"}',
 '{"ko":"굴 튀김","en":"Breaded fried oyster"}',
 20, 'medium', 2,
 '[{"name":"굴","quantity":"12개"},{"name":"밀가루","quantity":"50g"},{"name":"계란","quantity":"2개"},{"name":"빵가루","quantity":"100g"},{"name":"타르타르 소스","quantity":"적당량"}]',
 '{"ko":["굴을 씻어 물기를 뺀다","밀가루, 계란, 빵가루 순으로 입힌다","180도 기름에 튀긴다","타르타르 소스를 곁들인다"]}',
 ARRAY['mild','seafood','light','deep_fried']),

('japanese-065', 'seed',
 '{"ko":"이카 게소 가라아게","en":"Fried Squid Legs","ja":"イカゲソ唐揚げ","zh":"炸鱿鱼须"}',
 '{"ko":"오징어 다리 튀김","en":"Fried squid tentacles"}',
 20, 'easy', 2,
 '[{"name":"오징어 다리","quantity":"200g"},{"name":"간장","quantity":"1큰술"},{"name":"마늘","quantity":"1작은술"},{"name":"생강","quantity":"1작은술"},{"name":"감자전분","quantity":"50g"}]',
 '{"ko":["오징어를 먹기 좋게 자른다","간장, 마늘, 생강으로 양념한다","감자전분을 묻힌다","180도 기름에 튀긴다","레몬을 곁들인다"]}',
 ARRAY['mild','seafood','light','deep_fried','quick']),

-- === 나물/샐러드 (Salads) ===
('japanese-066', 'seed',
 '{"ko":"와카메 샐러드","en":"Seaweed Salad","ja":"わかめサラダ","zh":"海藻沙拉"}',
 '{"ko":"미역 샐러드","en":"Wakame seaweed salad"}',
 10, 'easy', 2,
 '[{"name":"미역","quantity":"30g"},{"name":"오이","quantity":"1개"},{"name":"식초","quantity":"2큰술"},{"name":"간장","quantity":"1큰술"},{"name":"참기름","quantity":"1작은술"}]',
 '{"ko":["미역을 물에 불린다","오이를 채 썬다","식초, 간장, 참기름을 섞어 드레싱을 만든다","미역과 오이에 드레싱을 버무린다"]}',
 ARRAY['mild','veggie','seafood','light','quick','salad']),

('japanese-067', 'seed',
 '{"ko":"두부 샐러드","en":"Tofu Salad","ja":"豆腐サラダ","zh":"豆腐沙拉"}',
 '{"ko":"차가운 두부 샐러드","en":"Cold tofu salad"}',
 10, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"토마토","quantity":"1개"},{"name":"상추","quantity":"4장"},{"name":"폰즈 소스","quantity":"2큰술"},{"name":"파","quantity":"약간"}]',
 '{"ko":["두부를 사방으로 자른다","토마토와 상추를 준비한다","접시에 담는다","폰즈 소스를 뿌리고 파를 올린다"]}',
 ARRAY['mild','veggie','light','quick','salad']),

('japanese-068', 'seed',
 '{"ko":"단무지 샐러드","en":"Daikon Salad","ja":"大根サラダ","zh":"萝卜沙拉"}',
 '{"ko":"무채 샐러드","en":"Shredded daikon salad"}',
 10, 'easy', 2,
 '[{"name":"무","quantity":"1/4개"},{"name":"당근","quantity":"1/2개"},{"name":"참깨 드레싱","quantity":"3큰술"}]',
 '{"ko":["무와 당근을 채 썬다","찬물에 담가 아삭하게 한다","물기를 빼고 드레싱을 버무린다"]}',
 ARRAY['mild','veggie','light','quick','salad']),

('japanese-069', 'seed',
 '{"ko":"고마 드레싱 샐러드","en":"Sesame Dressing Salad","ja":"胡麻ドレッシングサラダ","zh":"芝麻酱沙拉"}',
 '{"ko":"참깨 드레싱을 곁들인 샐러드","en":"Salad with sesame dressing"}',
 10, 'easy', 2,
 '[{"name":"상추","quantity":"4장"},{"name":"토마토","quantity":"1개"},{"name":"오이","quantity":"1개"},{"name":"참깨 드레싱","quantity":"3큰술"}]',
 '{"ko":["야채를 씻어 먹기 좋게 자른다","그릇에 담는다","참깨 드레싱을 뿌린다"]}',
 ARRAY['mild','veggie','light','quick','salad']),

('japanese-070', 'seed',
 '{"ko":"히야야코","en":"Hiyayakko","ja":"冷奴","zh":"冷豆腐"}',
 '{"ko":"차가운 두부 요리","en":"Cold tofu"}',
 5, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"파","quantity":"약간"},{"name":"생강","quantity":"약간"},{"name":"가다랑이포","quantity":"약간"},{"name":"간장","quantity":"적당량"}]',
 '{"ko":["두부를 차갑게 한다","먹기 좋게 자른다","파, 생강, 가다랑이포를 올린다","간장을 곁들여 낸다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

-- === 주먹밥/초밥류 (Onigiri & Rice) ===
('japanese-071', 'seed',
 '{"ko":"연어 오니기리","en":"Salmon Onigiri","ja":"鮭おにぎり","zh":"三文鱼饭团"}',
 '{"ko":"구운 연어를 넣은 주먹밥","en":"Rice ball with grilled salmon"}',
 15, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"구운 연어","quantity":"50g"},{"name":"김","quantity":"2장"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["밥에 소금을 약간 넣는다","연어를 잘게 부순다","밥에 연어를 넣고 주먹밥을 만든다","김을 붙인다"]}',
 ARRAY['mild','rice','seafood','light','quick']),

('japanese-072', 'seed',
 '{"ko":"우메보시 오니기리","en":"Umeboshi Onigiri","ja":"梅おにぎり","zh":"梅子饭团"}',
 '{"ko":"매실 장아찌를 넣은 주먹밥","en":"Rice ball with pickled plum"}',
 10, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"우메보시","quantity":"2개"},{"name":"김","quantity":"2장"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["밥에 소금을 약간 넣는다","밥에 우메보시를 넣고 주먹밥을 만든다","김을 붙인다"]}',
 ARRAY['mild','rice','veggie','light','quick']),

('japanese-073', 'seed',
 '{"ko":"참치 마요 오니기리","en":"Tuna Mayo Onigiri","ja":"ツナマヨおにぎり","zh":"吞拿鱼蛋黄酱饭团"}',
 '{"ko":"참치 마요네즈를 넣은 주먹밥","en":"Rice ball with tuna mayo"}',
 15, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"참치 캔","quantity":"1캔"},{"name":"마요네즈","quantity":"2큰술"},{"name":"김","quantity":"2장"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["참치에 물기를 빼고 마요네즈와 섞는다","밥에 소금을 약간 넣는다","밥에 참치마요를 넣고 주먹밥을 만든다","김을 붙인다"]}',
 ARRAY['mild','rice','seafood','light','quick']),

('japanese-074', 'seed',
 '{"ko":"치킨 라이스","en":"Chicken Rice","ja":"チキンライス","zh":"鸡肉炒饭"}',
 '{"ko":"일본식 케첩 볶음밥","en":"Japanese ketchup fried rice"}',
 15, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"닭고기","quantity":"100g"},{"name":"양파","quantity":"1/2개"},{"name":"케첩","quantity":"4큰술"},{"name":"버터","quantity":"1큰술"}]',
 '{"ko":["닭고기와 양파를 다진다","팬에 버터를 녹이고 닭고기를 볶는다","양파를 넣고 볶는다","밥을 넣고 볶는다","케첩을 넣고 섞는다"]}',
 ARRAY['mild','rice','meat','heavy','quick','stir_fry']),

('japanese-075', 'seed',
 '{"ko":"오차즈케","en":"Ochazuke","ja":"お茶漬け","zh":"茶泡饭"}',
 '{"ko":"녹차를 부은 밥 요리","en":"Rice with green tea"}',
 5, 'easy', 1,
 '[{"name":"밥","quantity":"1공기"},{"name":"녹차","quantity":"200ml"},{"name":"연어","quantity":"30g"},{"name":"김","quantity":"약간"},{"name":"와사비","quantity":"약간"}]',
 '{"ko":["밥을 그릇에 담는다","연어와 김을 올린다","뜨거운 녹차를 붓는다","와사비를 곁들인다"]}',
 ARRAY['mild','rice','seafood','light','quick']),

-- === 면요리 추가 (More Noodles) ===
('japanese-076', 'seed',
 '{"ko":"하이야시 츄카","en":"Hiyashi Chuka","ja":"冷やし中華","zh":"凉拌中华面"}',
 '{"ko":"차갑게 먹는 중화풍 냉면","en":"Cold Chinese-style noodles"}',
 20, 'easy', 2,
 '[{"name":"라멘 면","quantity":"2인분"},{"name":"계란","quantity":"2개"},{"name":"오이","quantity":"1개"},{"name":"토마토","quantity":"1개"},{"name":"햄","quantity":"4장"},{"name":"식초 간장 소스","quantity":"4큰술"}]',
 '{"ko":["면을 삶아 찬물에 헹군다","계란을 지단으로 부쳐 채 썬다","오이와 햄을 채 썬다","면 위에 재료를 올린다","식초 간장 소스를 뿌린다"]}',
 ARRAY['mild','noodle','light','quick','salad']),

('japanese-077', 'seed',
 '{"ko":"타누키 우동","en":"Tanuki Udon","ja":"たぬきうどん","zh":"天花乌冬面"}',
 '{"ko":"튀김 부스러기를 올린 우동","en":"Udon with tempura flakes"}',
 15, 'easy', 1,
 '[{"name":"우동 면","quantity":"1인분"},{"name":"텐카스","quantity":"2큰술"},{"name":"다시마 육수","quantity":"400ml"},{"name":"간장","quantity":"2큰술"},{"name":"파","quantity":"약간"}]',
 '{"ko":["육수를 끓이고 간장으로 간한다","우동 면을 삶는다","그릇에 면을 담고 육수를 붓는다","텐카스와 파를 올린다"]}',
 ARRAY['mild','soupy','noodle','light','quick']),

('japanese-078', 'seed',
 '{"ko":"키츠네 우동","en":"Kitsune Udon","ja":"きつねうどん","zh":"油豆腐乌冬面"}',
 '{"ko":"유부를 올린 우동","en":"Udon with sweet fried tofu"}',
 15, 'easy', 1,
 '[{"name":"우동 면","quantity":"1인분"},{"name":"유부","quantity":"2장"},{"name":"다시마 육수","quantity":"400ml"},{"name":"간장","quantity":"2큰술"},{"name":"미림","quantity":"1큰술"}]',
 '{"ko":["유부를 간장과 미림에 조린다","육수를 끓이고 간장으로 간한다","우동 면을 삶는다","그릇에 면을 담고 육수를 붓는다","유부를 올린다"]}',
 ARRAY['mild','soupy','noodle','veggie','light','quick']),

('japanese-079', 'seed',
 '{"ko":"냉소바","en":"Cold Soba","ja":"冷やしそば","zh":"冷荞麦面"}',
 '{"ko":"차가운 소바 국수","en":"Chilled soba noodles"}',
 15, 'easy', 2,
 '[{"name":"소바 면","quantity":"2인분"},{"name":"소바 육수","quantity":"200ml"},{"name":"파","quantity":"1대"},{"name":"김","quantity":"1장"},{"name":"와사비","quantity":"약간"}]',
 '{"ko":["소바 면을 삶아 찬물에 헹군다","물기를 빼고 접시에 담는다","김과 파를 올린다","소바 육수에 와사비를 넣어 찍어 먹는다"]}',
 ARRAY['mild','noodle','light','quick']),

('japanese-080', 'seed',
 '{"ko":"차슈멘","en":"Chashu Men","ja":"チャーシューメン","zh":"叉烧面"}',
 '{"ko":"차슈가 듬뿍 올라간 라멘","en":"Ramen with plenty of chashu"}',
 45, 'medium', 2,
 '[{"name":"라멘 면","quantity":"2인분"},{"name":"차슈","quantity":"8장"},{"name":"라멘 육수","quantity":"800ml"},{"name":"파","quantity":"1대"},{"name":"계란","quantity":"2개"}]',
 '{"ko":["육수를 끓인다","계란을 반숙으로 삶는다","면을 삶아 그릇에 담는다","육수를 붓는다","차슈를 듬뿍 올리고 계란, 파를 곁들인다"]}',
 ARRAY['mild','soupy','noodle','meat','heavy']),

-- === 찜/조림 (Steamed & Braised) ===
('japanese-081', 'seed',
 '{"ko":"차완무시","en":"Chawanmushi","ja":"茶碗蒸し","zh":"茶碗蒸"}',
 '{"ko":"일본식 계란찜","en":"Japanese savory egg custard"}',
 20, 'easy', 2,
 '[{"name":"계란","quantity":"3개"},{"name":"다시마 육수","quantity":"300ml"},{"name":"닭고기","quantity":"50g"},{"name":"새우","quantity":"4마리"},{"name":"표고버섯","quantity":"2개"}]',
 '{"ko":["계란에 육수를 넣고 잘 섞는다","그릇에 닭고기, 새우, 버섯을 담는다","계란물을 부어 체로 거른다","찜기에 넣고 15분 찐다"]}',
 ARRAY['mild','meat','seafood','steamed','light']),

('japanese-082', 'seed',
 '{"ko":"호일 구이","en":"Foil Yaki","ja":"ホイル焼き","zh":"锡纸烧"}',
 '{"ko":"호일에 싸서 찐 생선과 야채","en":"Fish and vegetables steamed in foil"}',
 25, 'easy', 2,
 '[{"name":"연어","quantity":"2토막"},{"name":"버섯","quantity":"100g"},{"name":"파","quantity":"1대"},{"name":"버터","quantity":"2큰술"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["호일에 연어를 올린다","버섯과 파를 올린다","버터와 간장을 올린다","호일로 싸서 오븐에 20분 굽는다"]}',
 ARRAY['mild','seafood','veggie','steamed','light']),

('japanese-083', 'seed',
 '{"ko":"카부라무시","en":"Kaburamushi","ja":"かぶら蒸し","zh":"萝卜泥蒸"}',
 '{"ko":"무채를 올린 찜 요리","en":"Steamed dish with grated turnip"}',
 30, 'medium', 2,
 '[{"name":"무","quantity":"1/2개"},{"name":"계란 흰자","quantity":"1개"},{"name":"흰살생선","quantity":"100g"},{"name":"은행","quantity":"4개"},{"name":"다시마 육수","quantity":"200ml"}]',
 '{"ko":["무를 갈아 즙을 낸다","계란 흰자를 머랭처럼 거품낸다","무채와 섞는다","그릇에 생선과 은행을 담고 무채를 올린다","찐다"]}',
 ARRAY['mild','seafood','veggie','steamed','light']),

('japanese-084', 'seed',
 '{"ko":"부타노 가쿠니","en":"Braised Pork Belly","ja":"豚の角煮","zh":"红烧猪肉"}',
 '{"ko":"일본식 돼지고기 조림","en":"Japanese braised pork belly"}',
 120, 'hard', 4,
 '[{"name":"돼지 삼겹살","quantity":"600g"},{"name":"간장","quantity":"100ml"},{"name":"미림","quantity":"50ml"},{"name":"설탕","quantity":"3큰술"},{"name":"생강","quantity":"1조각"},{"name":"파","quantity":"1대"}]',
 '{"ko":["돼지고기를 큼직하게 자른다","냄비에 고기를 넣고 물을 부어 1시간 삶는다","새 냄비에 간장, 미림, 설탕을 넣고 끓인다","고기를 넣고 1시간 조린다","부드럽게 익으면 완성"]}',
 ARRAY['mild','meat','heavy']),

('japanese-085', 'seed',
 '{"ko":"사바 미소니","en":"Mackerel in Miso","ja":"鯖の味噌煮","zh":"味噌煮青花鱼"}',
 '{"ko":"된장으로 조린 고등어","en":"Mackerel simmered in miso"}',
 30, 'easy', 2,
 '[{"name":"고등어","quantity":"2토막"},{"name":"미소","quantity":"3큰술"},{"name":"미림","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"생강","quantity":"1조각"}]',
 '{"ko":["냄비에 물, 미소, 미림, 설탕을 넣고 끓인다","고등어와 생강을 넣는다","약불로 20분 조린다"]}',
 ARRAY['mild','seafood','light']),

-- === 디저트 (Desserts) ===
('japanese-086', 'seed',
 '{"ko":"모찌","en":"Mochi","ja":"餅","zh":"麻糬"}',
 '{"ko":"일본식 떡","en":"Japanese rice cake"}',
 30, 'medium', 4,
 '[{"name":"찹쌀가루","quantity":"200g"},{"name":"설탕","quantity":"50g"},{"name":"물","quantity":"200ml"},{"name":"감자전분","quantity":"적당량"}]',
 '{"ko":["찹쌀가루에 설탕과 물을 넣고 섞는다","찜기에 20분 찐다","치대어 부드럽게 만든다","감자전분을 뿌린 판에 펼친다","먹기 좋게 자른다"]}',
 ARRAY['mild','veggie','light','steamed']),

('japanese-087', 'seed',
 '{"ko":"다이후쿠","en":"Daifuku","ja":"大福","zh":"大福饼"}',
 '{"ko":"팥소를 넣은 모찌","en":"Mochi filled with sweet red bean paste"}',
 40, 'medium', 8,
 '[{"name":"찹쌀가루","quantity":"200g"},{"name":"설탕","quantity":"50g"},{"name":"팥소","quantity":"200g"},{"name":"물","quantity":"200ml"}]',
 '{"ko":["찹쌀가루로 모찌를 만든다","팥소를 작게 둥글게 만든다","모찌를 펴서 팥소를 넣는다","감싼다"]}',
 ARRAY['mild','veggie','light','steamed']),

('japanese-088', 'seed',
 '{"ko":"도라야키","en":"Dorayaki","ja":"どら焼き","zh":"铜锣烧"}',
 '{"ko":"팥소를 넣은 팬케이크","en":"Pancake sandwich with red bean filling"}',
 30, 'easy', 6,
 '[{"name":"밀가루","quantity":"150g"},{"name":"계란","quantity":"2개"},{"name":"설탕","quantity":"80g"},{"name":"베이킹파우더","quantity":"1작은술"},{"name":"팥소","quantity":"200g"}]',
 '{"ko":["계란과 설탕을 섞는다","밀가루와 베이킹파우더를 넣고 섞는다","팬에 작은 팬케이크를 굽는다","팥소를 발라 두 장을 겹친다"]}',
 ARRAY['mild','veggie','light','baked']),

('japanese-089', 'seed',
 '{"ko":"미츠마메","en":"Mitsumame","ja":"みつまめ","zh":"蜜豆"}',
 '{"ko":"한천과 과일의 일본식 디저트","en":"Japanese dessert with agar jelly and fruits"}',
 20, 'easy', 4,
 '[{"name":"한천","quantity":"1팩"},{"name":"과일 통조림","quantity":"1캔"},{"name":"팥","quantity":"100g"},{"name":"흑밀","quantity":"4큰술"}]',
 '{"ko":["한천을 사방으로 자른다","과일을 준비한다","그릇에 한천, 과일, 팥을 담는다","흑밀을 뿌린다"]}',
 ARRAY['mild','veggie','light','quick']),

('japanese-090', 'seed',
 '{"ko":"당고","en":"Dango","ja":"団子","zh":"团子"}',
 '{"ko":"떡 경단","en":"Japanese rice dumplings"}',
 30, 'easy', 8,
 '[{"name":"떡가루","quantity":"200g"},{"name":"물","quantity":"150ml"},{"name":"간장","quantity":"3큰술"},{"name":"미림","quantity":"2큰술"},{"name":"설탕","quantity":"2큰술"}]',
 '{"ko":["떡가루에 물을 넣고 반죽한다","작은 공 모양으로 만든다","끓는 물에 삶는다","꼬치에 꿴다","간장, 미림, 설탕을 끓여 소스를 만든다","소스를 발라 굽는다"]}',
 ARRAY['mild','veggie','light','grilled']),

('japanese-091', 'seed',
 '{"ko":"타이야키","en":"Taiyaki","ja":"たい焼き","zh":"鲷鱼烧"}',
 '{"ko":"붕어빵처럼 생긴 일본 간식","en":"Fish-shaped cake with filling"}',
 30, 'medium', 6,
 '[{"name":"밀가루","quantity":"150g"},{"name":"계란","quantity":"1개"},{"name":"설탕","quantity":"50g"},{"name":"베이킹파우더","quantity":"1작은술"},{"name":"팥소","quantity":"200g"}]',
 '{"ko":["밀가루, 계란, 설탕, 베이킹파우더를 섞는다","타이야키 틀을 달군다","반죽을 붓고 팥소를 넣는다","반죽을 더 붓고 구워낸다"]}',
 ARRAY['mild','veggie','light','baked']),

('japanese-092', 'seed',
 '{"ko":"카스테라","en":"Castella","ja":"カステラ","zh":"蜂蜜蛋糕"}',
 '{"ko":"일본식 스펀지 케이크","en":"Japanese sponge cake"}',
 50, 'medium', 8,
 '[{"name":"계란","quantity":"4개"},{"name":"설탕","quantity":"120g"},{"name":"밀가루","quantity":"120g"},{"name":"꿀","quantity":"2큰술"},{"name":"물","quantity":"2큰술"}]',
 '{"ko":["계란과 설탕을 잘 섞는다","꿀과 물을 넣는다","밀가루를 체쳐 넣고 섞는다","틀에 붓고 170도 오븐에 40분 굽는다","식혀서 자른다"]}',
 ARRAY['mild','veggie','light','baked']),

('japanese-093', 'seed',
 '{"ko":"요칸","en":"Yokan","ja":"羊羹","zh":"羊羹"}',
 '{"ko":"팥으로 만든 일본 전통 과자","en":"Traditional Japanese red bean jelly"}',
 40, 'medium', 8,
 '[{"name":"팥소","quantity":"300g"},{"name":"한천","quantity":"1팩"},{"name":"설탕","quantity":"100g"},{"name":"물","quantity":"400ml"}]',
 '{"ko":["물에 한천을 넣고 끓여 녹인다","설탕을 넣어 녹인다","팥소를 넣고 섞는다","틀에 부어 굳힌다","자른다"]}',
 ARRAY['mild','veggie','light']),

('japanese-094', 'seed',
 '{"ko":"안미츠","en":"Anmitsu","ja":"あんみつ","zh":"蜜豆"}',
 '{"ko":"팥과 한천의 일본 디저트","en":"Japanese dessert with agar jelly and sweet red beans"}',
 20, 'easy', 4,
 '[{"name":"한천","quantity":"1팩"},{"name":"팥소","quantity":"150g"},{"name":"과일","quantity":"적당량"},{"name":"흑밀","quantity":"4큰술"},{"name":"아이스크림","quantity":"4스쿱"}]',
 '{"ko":["한천을 사방으로 자른다","그릇에 한천을 담는다","팥소와 과일을 올린다","아이스크림을 올리고 흑밀을 뿌린다"]}',
 ARRAY['mild','veggie','light','quick']),

('japanese-095', 'seed',
 '{"ko":"마차 아이스크림","en":"Matcha Ice Cream","ja":"抹茶アイスクリーム","zh":"抹茶冰淇淋"}',
 '{"ko":"녹차 아이스크림","en":"Green tea ice cream"}',
 30, 'easy', 4,
 '[{"name":"생크림","quantity":"300ml"},{"name":"연유","quantity":"100g"},{"name":"말차 가루","quantity":"2큰술"}]',
 '{"ko":["생크림을 휘핑한다","연유와 말차 가루를 넣고 섞는다","용기에 담아 냉동실에 넣는다","2시간마다 저어준다","굳으면 완성"]}',
 ARRAY['mild','veggie','light']),

-- === 기타 요리 (Other Dishes) ===
('japanese-096', 'seed',
 '{"ko":"오뎅","en":"Oden","ja":"おでん","zh":"关东煮"}',
 '{"ko":"일본식 어묵 전골","en":"Japanese fish cake hot pot"}',
 40, 'easy', 4,
 '[{"name":"무","quantity":"1/2개"},{"name":"어묵","quantity":"6개"},{"name":"곤약","quantity":"1팩"},{"name":"계란","quantity":"4개"},{"name":"다시마 육수","quantity":"1L"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["무를 큼직하게 자른다","계란을 삶는다","냄비에 육수를 끓인다","무를 넣고 20분 끓인다","어묵, 곤약, 계란을 넣는다","간장으로 간하고 끓인다"]}',
 ARRAY['mild','soupy','seafood','light']),

('japanese-097', 'seed',
 '{"ko":"나토","en":"Natto","ja":"納豆","zh":"纳豆"}',
 '{"ko":"발효 콩","en":"Fermented soybeans"}',
 5, 'easy', 1,
 '[{"name":"나토","quantity":"1팩"},{"name":"간장","quantity":"약간"},{"name":"겨자","quantity":"약간"},{"name":"파","quantity":"약간"}]',
 '{"ko":["나토를 그릇에 담는다","간장과 겨자를 넣고 섞는다","파를 올린다","밥과 함께 먹는다"]}',
 ARRAY['mild','veggie','light','quick','side_dish']),

('japanese-098', 'seed',
 '{"ko":"코로케 샌드위치","en":"Korokke Sandwich","ja":"コロッケサンド","zh":"可乐饼三明治"}',
 '{"ko":"고로케를 넣은 샌드위치","en":"Sandwich with potato croquette"}',
 15, 'easy', 2,
 '[{"name":"식빵","quantity":"4장"},{"name":"고로케","quantity":"2개"},{"name":"양배추","quantity":"50g"},{"name":"돈까스 소스","quantity":"2큰술"}]',
 '{"ko":["고로케를 준비한다","양배추를 채 썬다","빵에 양배추를 깔고 고로케를 올린다","소스를 뿌리고 빵으로 덮는다"]}',
 ARRAY['mild','veggie','meat','heavy','bread']),

('japanese-099', 'seed',
 '{"ko":"가츠산도","en":"Katsu Sando","ja":"カツサンド","zh":"炸猪排三明治"}',
 '{"ko":"돈까스 샌드위치","en":"Pork cutlet sandwich"}',
 20, 'easy', 2,
 '[{"name":"식빵","quantity":"4장"},{"name":"돈까스","quantity":"2장"},{"name":"양배추","quantity":"50g"},{"name":"돈까스 소스","quantity":"2큰술"}]',
 '{"ko":["돈까스를 튀긴다","양배추를 채 썬다","빵에 양배추를 깔고 돈까스를 올린다","소스를 뿌리고 빵으로 덮는다","반으로 자른다"]}',
 ARRAY['mild','meat','heavy','bread','deep_fried']),

('japanese-100', 'seed',
 '{"ko":"타마고 산도","en":"Egg Sandwich","ja":"卵サンド","zh":"鸡蛋三明治"}',
 '{"ko":"일본식 계란 샌드위치","en":"Japanese-style egg sandwich"}',
 15, 'easy', 2,
 '[{"name":"식빵","quantity":"4장"},{"name":"계란","quantity":"3개"},{"name":"마요네즈","quantity":"3큰술"},{"name":"소금","quantity":"약간"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["계란을 삶아 으깬다","마요네즈, 소금, 후추를 넣고 섞는다","빵에 계란 샐러드를 펴 바른다","빵으로 덮고 반으로 자른다"]}',
 ARRAY['mild','veggie','light','quick','bread']);
