-- 중식 레시피 시드 데이터 (100개 중식 레시피)
-- Supabase SQL Editor에서 실행하세요
-- tags: spicy, mild, soupy, stir_fry, grilled, steamed, raw, meat, seafood, veggie, heavy, light, quick, noodle, rice, side_dish, deep_fried, dim_sum

-- 기존 중식 시드 데이터 중복 방지
DELETE FROM public.recipes WHERE source = 'seed' AND external_id LIKE 'chinese-%';

INSERT INTO public.recipes (external_id, source, title, description, cooking_time, difficulty, servings, ingredients, instructions, tags) VALUES

-- === 면 요리 (Noodles) ===
('chinese-001', 'seed',
 '{"ko":"짜장면","en":"Jajangmyeon","ja":"ジャージャー麺","zh":"炸酱面"}',
 '{"ko":"달콤한 춘장 소스로 버무린 중국식 국수","en":"Chinese-style noodles with sweet black bean sauce"}',
 25, 'easy', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"춘장","quantity":"3큰술"},{"name":"돼지고기","quantity":"150g"},{"name":"양파","quantity":"1개"},{"name":"감자","quantity":"1개"},{"name":"호박","quantity":"1/2개"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["양파, 감자, 호박을 깍둑썰기한다","팬에 기름을 두르고 돼지고기를 볶는다","야채를 넣고 볶는다","춘장을 넣고 볶다가 물을 붓는다","설탕을 넣고 졸인다","삶은 면에 소스를 얹는다"]}',
 ARRAY['mild','stir_fry','meat','heavy','noodle']),

('chinese-002', 'seed',
 '{"ko":"짬뽕","en":"Jjamppong","ja":"チャンポン","zh":"炒码面"}',
 '{"ko":"얼큰한 해물 국물에 면을 말아먹는 중화요리","en":"Spicy seafood noodle soup"}',
 30, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"오징어","quantity":"100g"},{"name":"새우","quantity":"5마리"},{"name":"홍합","quantity":"5개"},{"name":"양배추","quantity":"2잎"},{"name":"대파","quantity":"1대"},{"name":"고춧가루","quantity":"2큰술"},{"name":"고추기름","quantity":"1큰술"}]',
 '{"ko":["해물을 손질한다","팬에 고추기름을 두르고 고춧가루를 볶는다","해물과 야채를 넣고 볶는다","물을 붓고 끓인다","삶은 면을 넣고 한소끔 끓인다"]}',
 ARRAY['spicy','soupy','seafood','heavy','noodle']),

('chinese-003', 'seed',
 '{"ko":"간짜장","en":"Gan Jjajang","ja":"乾炸醤麺","zh":"干炸酱面"}',
 '{"ko":"국물 없이 볶은 진한 춘장면","en":"Dry jajangmyeon with thick black bean sauce"}',
 20, 'easy', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"춘장","quantity":"4큰술"},{"name":"돼지고기","quantity":"100g"},{"name":"양파","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"설탕","quantity":"1큰술"},{"name":"식용유","quantity":"3큰술"}]',
 '{"ko":["양파, 대파를 다진다","팬에 기름을 넉넉히 두르고 춘장을 볶는다","돼지고기와 야채를 넣고 볶는다","설탕을 넣고 잘 섞는다","삶은 면에 비벼서 먹는다"]}',
 ARRAY['mild','stir_fry','meat','heavy','noodle','quick']),

('chinese-004', 'seed',
 '{"ko":"유니짜장","en":"Uni Jjajang","ja":"ウニ炸醤麺","zh":"海胆炸酱面"}',
 '{"ko":"성게알이 들어간 고급 짜장면","en":"Premium jajangmyeon with sea urchin"}',
 25, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"춘장","quantity":"3큰술"},{"name":"성게알","quantity":"50g"},{"name":"양파","quantity":"1개"},{"name":"대파","quantity":"1대"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["양파를 다진다","팬에 춘장을 볶는다","양파를 넣고 볶다가 물을 붓는다","성게알을 넣고 섞는다","삶은 면에 얹어 낸다"]}',
 ARRAY['mild','stir_fry','seafood','heavy','noodle']),

('chinese-005', 'seed',
 '{"ko":"삼선짜장","en":"Samseon Jjajang","ja":"三鮮炸醤麺","zh":"三鲜炸酱面"}',
 '{"ko":"해물이 들어간 고급 짜장면","en":"Premium jajangmyeon with seafood"}',
 30, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"춘장","quantity":"3큰술"},{"name":"새우","quantity":"5마리"},{"name":"오징어","quantity":"100g"},{"name":"해삼","quantity":"1개"},{"name":"양파","quantity":"1개"},{"name":"죽순","quantity":"50g"}]',
 '{"ko":["해물을 손질한다","팬에 춘장을 볶는다","해물과 야채를 넣고 볶는다","물을 붓고 졸인다","삶은 면에 얹는다"]}',
 ARRAY['mild','stir_fry','seafood','heavy','noodle']),

('chinese-006', 'seed',
 '{"ko":"삼선짬뽕","en":"Samseon Jjamppong","ja":"三鮮チャンポン","zh":"三鲜炒码面"}',
 '{"ko":"고급 해물이 듬뿍 들어간 얼큰한 짬뽕","en":"Premium spicy seafood noodle soup"}',
 35, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"새우","quantity":"7마리"},{"name":"오징어","quantity":"150g"},{"name":"전복","quantity":"2개"},{"name":"양배추","quantity":"3잎"},{"name":"대파","quantity":"2대"},{"name":"고춧가루","quantity":"2큰술"}]',
 '{"ko":["해물을 손질한다","팬에 고추기름을 두르고 해물을 볶는다","고춧가루를 넣고 볶는다","물을 붓고 끓인다","면을 넣고 끓인다"]}',
 ARRAY['spicy','soupy','seafood','heavy','noodle']),

('chinese-007', 'seed',
 '{"ko":"울면","en":"Ulmyeon","ja":"ウルメン","zh":"烩面"}',
 '{"ko":"해물과 야채가 들어간 걸쭉한 국물 요리","en":"Thick seafood and vegetable noodle soup"}',
 30, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"새우","quantity":"5마리"},{"name":"오징어","quantity":"100g"},{"name":"양배추","quantity":"3잎"},{"name":"죽순","quantity":"50g"},{"name":"전분물","quantity":"5큰술"}]',
 '{"ko":["해물과 야채를 손질한다","팬에 해물을 볶는다","야채를 넣고 볶다가 물을 붓는다","끓으면 전분물로 걸쭉하게 만든다","삶은 면에 부어낸다"]}',
 ARRAY['mild','soupy','seafood','heavy','noodle']),

('chinese-008', 'seed',
 '{"ko":"라조기","en":"La Zi Ji","ja":"ラーズーチー","zh":"辣子鸡"}',
 '{"ko":"마른 고추와 함께 바삭하게 튀긴 닭고기","en":"Crispy fried chicken with dried chili peppers"}',
 40, 'medium', 3,
 '[{"name":"닭다리살","quantity":"400g"},{"name":"마른고추","quantity":"30개"},{"name":"화자오","quantity":"1큰술"},{"name":"생강","quantity":"1톨"},{"name":"마늘","quantity":"5쪽"},{"name":"전분","quantity":"5큰술"}]',
 '{"ko":["닭고기를 한입 크기로 자르고 양념한다","전분을 묻혀 바삭하게 튀긴다","팬에 기름을 두르고 마른고추와 화자오를 볶는다","튀긴 닭을 넣고 볶는다","생강, 마늘을 넣고 마무리한다"]}',
 ARRAY['spicy','deep_fried','meat','heavy']),

('chinese-009', 'seed',
 '{"ko":"마라탕","en":"Malatang","ja":"麻辣湯","zh":"麻辣烫"}',
 '{"ko":"얼얼하고 매운 사천식 훠궈 국물 요리","en":"Sichuan-style spicy hot pot soup"}',
 25, 'easy', 2,
 '[{"name":"중화면","quantity":"1인분"},{"name":"양고기","quantity":"100g"},{"name":"배추","quantity":"3잎"},{"name":"팽이버섯","quantity":"1봉"},{"name":"두부","quantity":"1모"},{"name":"마라탕 소스","quantity":"3큰술"},{"name":"화자오","quantity":"1큰술"}]',
 '{"ko":["냄비에 물을 끓인다","마라탕 소스와 화자오를 넣는다","양고기를 넣고 익힌다","야채와 두부를 넣는다","면을 넣고 끓인다"]}',
 ARRAY['spicy','soupy','meat','heavy','noodle']),

('chinese-010', 'seed',
 '{"ko":"우육면","en":"Beef Noodle Soup","ja":"牛肉麺","zh":"牛肉面"}',
 '{"ko":"푹 고아낸 소고기 육수의 중국식 국수","en":"Chinese beef noodle soup with rich broth"}',
 90, 'medium', 3,
 '[{"name":"중화면","quantity":"3인분"},{"name":"소고기","quantity":"500g"},{"name":"무","quantity":"1개"},{"name":"대파","quantity":"2대"},{"name":"생강","quantity":"1톨"},{"name":"팔각","quantity":"2개"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["소고기를 큼직하게 썬다","냄비에 소고기, 무, 향신료를 넣고 물을 붓는다","1시간 반 동안 푹 끓인다","간장으로 간을 한다","삶은 면에 고기와 국물을 부어낸다"]}',
 ARRAY['mild','soupy','meat','heavy','noodle']),

-- === 볶음밥/밥 요리 (Fried Rice) ===
('chinese-011', 'seed',
 '{"ko":"볶음밥","en":"Fried Rice","ja":"チャーハン","zh":"炒饭"}',
 '{"ko":"계란과 야채로 볶은 간단한 중국식 볶음밥","en":"Simple Chinese fried rice with egg and vegetables"}',
 15, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"당근","quantity":"1/2개"},{"name":"양파","quantity":"1/2개"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["야채를 잘게 다진다","팬에 계란을 풀어 볶는다","밥을 넣고 볶는다","야채를 넣고 볶는다","간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','quick','rice']),

('chinese-012', 'seed',
 '{"ko":"새우볶음밥","en":"Shrimp Fried Rice","ja":"海老チャーハン","zh":"虾仁炒饭"}',
 '{"ko":"탱글한 새우가 들어간 볶음밥","en":"Fried rice with plump shrimp"}',
 20, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"새우","quantity":"10마리"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"완두콩","quantity":"50g"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["새우를 손질한다","팬에 새우를 볶는다","계란을 풀어 넣고 밥을 넣는다","완두콩과 대파를 넣는다","간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','seafood','quick','rice']),

('chinese-013', 'seed',
 '{"ko":"게살볶음밥","en":"Crab Fried Rice","ja":"蟹チャーハン","zh":"蟹肉炒饭"}',
 '{"ko":"게살이 들어간 고급 볶음밥","en":"Premium fried rice with crab meat"}',
 20, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"게살","quantity":"100g"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"굴소스","quantity":"1큰술"}]',
 '{"ko":["팬에 계란을 볶는다","밥을 넣고 볶는다","게살을 넣는다","대파를 넣는다","굴소스로 간을 한다"]}',
 ARRAY['mild','stir_fry','seafood','rice','quick']),

('chinese-014', 'seed',
 '{"ko":"양장피","en":"Yangjangpi","ja":"ヤンジャンピー","zh":"凉拌粉皮"}',
 '{"ko":"쫄깃한 녹말전분 면에 해물과 야채를 얹은 냉채","en":"Cold jellyfish salad with seafood and vegetables"}',
 30, 'medium', 3,
 '[{"name":"녹말전분면","quantity":"200g"},{"name":"오징어","quantity":"100g"},{"name":"새우","quantity":"5마리"},{"name":"해파리","quantity":"100g"},{"name":"오이","quantity":"1개"},{"name":"겨자","quantity":"1큰술"},{"name":"식초","quantity":"2큰술"}]',
 '{"ko":["녹말전분면을 삶아 찬물에 헹군다","해물을 삶아 식힌다","오이를 채썬다","겨자 소스를 만든다","모든 재료를 섞어 소스를 뿌린다"]}',
 ARRAY['mild','seafood','light','noodle']),

('chinese-015', 'seed',
 '{"ko":"마파두부","en":"Mapo Tofu","ja":"麻婆豆腐","zh":"麻婆豆腐"}',
 '{"ko":"얼얼하고 매운 사천식 두부 요리","en":"Spicy Sichuan-style tofu with ground pork"}',
 20, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"돼지고기","quantity":"150g"},{"name":"대파","quantity":"1대"},{"name":"두반장","quantity":"2큰술"},{"name":"화자오","quantity":"1큰술"},{"name":"고춧가루","quantity":"1큰술"}]',
 '{"ko":["두부를 깍둑썰기한다","팬에 돼지고기를 볶는다","두반장을 넣고 볶는다","두부를 넣고 조심스럽게 섞는다","화자오와 대파를 올린다"]}',
 ARRAY['spicy','stir_fry','meat','heavy','quick']),

-- === 튀김 요리 (Deep Fried) ===
('chinese-016', 'seed',
 '{"ko":"탕수육","en":"Tangsuyuk","ja":"酢豚","zh":"糖醋肉"}',
 '{"ko":"바삭하게 튀긴 돼지고기에 새콤달콤한 소스를 곁들인 요리","en":"Sweet and sour crispy pork"}',
 40, 'medium', 3,
 '[{"name":"돼지고기","quantity":"400g"},{"name":"양파","quantity":"1개"},{"name":"파프리카","quantity":"1개"},{"name":"당근","quantity":"1/2개"},{"name":"전분","quantity":"1컵"},{"name":"설탕","quantity":"4큰술"},{"name":"식초","quantity":"3큰술"}]',
 '{"ko":["돼지고기를 한입 크기로 썬다","전분을 묻혀 바삭하게 튀긴다","야채를 썬다","팬에 설탕, 식초, 물로 소스를 만든다","야채를 넣고 전분물로 걸쭉하게 만든다","튀긴 고기에 소스를 부어낸다"]}',
 ARRAY['mild','deep_fried','meat','heavy']),

('chinese-017', 'seed',
 '{"ko":"깐풍기","en":"Dry Fried Chicken","ja":"乾烤鶏","zh":"干烹鸡"}',
 '{"ko":"바삭하게 튀긴 닭고기를 매콤달콤하게 볶은 요리","en":"Crispy fried chicken stir-fried in spicy sweet sauce"}',
 35, 'medium', 3,
 '[{"name":"닭다리살","quantity":"400g"},{"name":"마늘","quantity":"10쪽"},{"name":"고추","quantity":"5개"},{"name":"전분","quantity":"1컵"},{"name":"간장","quantity":"2큰술"},{"name":"설탕","quantity":"2큰술"}]',
 '{"ko":["닭고기를 한입 크기로 자른다","전분을 묻혀 튀긴다","팬에 마늘과 고추를 볶는다","튀긴 닭을 넣는다","간장, 설탕 양념으로 볶는다"]}',
 ARRAY['spicy','deep_fried','meat','heavy']),

('chinese-018', 'seed',
 '{"ko":"유린기","en":"Chicken with Scallion Sauce","ja":"油淋鶏","zh":"油淋鸡"}',
 '{"ko":"바삭한 닭고기에 대파 소스를 끼얹은 요리","en":"Crispy chicken with green onion sauce"}',
 40, 'medium', 3,
 '[{"name":"닭다리살","quantity":"500g"},{"name":"대파","quantity":"3대"},{"name":"간장","quantity":"4큰술"},{"name":"식초","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"전분","quantity":"1컵"}]',
 '{"ko":["닭고기에 밑간을 한다","전분을 묻혀 바삭하게 튀긴다","대파를 채썬다","간장, 식초, 설탕으로 소스를 만든다","뜨거운 기름을 부어 대파를 익힌다","튀긴 닭에 소스를 끼얹는다"]}',
 ARRAY['mild','deep_fried','meat','heavy']),

('chinese-019', 'seed',
 '{"ko":"꿔바로우","en":"Guobaorou","ja":"锅包肉","zh":"锅包肉"}',
 '{"ko":"바삭한 돼지고기에 새콤달콤한 소스를 입힌 동북식 요리","en":"Sweet and sour crispy pork, Northeast Chinese style"}',
 40, 'medium', 3,
 '[{"name":"돼지고기","quantity":"400g"},{"name":"당근","quantity":"1개"},{"name":"오이","quantity":"1개"},{"name":"전분","quantity":"1컵"},{"name":"설탕","quantity":"5큰술"},{"name":"식초","quantity":"4큰술"}]',
 '{"ko":["돼지고기를 얇게 저민다","전분을 묻혀 두 번 튀긴다","야채를 채썬다","팬에 설탕, 식초로 소스를 만든다","고기와 야채를 넣고 빠르게 볶는다"]}',
 ARRAY['mild','deep_fried','meat','heavy']),

('chinese-020', 'seed',
 '{"ko":"라유새우","en":"Spicy Oil Shrimp","ja":"ラー油エビ","zh":"辣油虾"}',
 '{"ko":"매콤한 라유에 볶은 새우 요리","en":"Shrimp stir-fried in spicy chili oil"}',
 20, 'easy', 2,
 '[{"name":"새우","quantity":"300g"},{"name":"마늘","quantity":"5쪽"},{"name":"대파","quantity":"1대"},{"name":"라유","quantity":"3큰술"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["새우를 손질한다","팬에 마늘을 볶는다","새우를 넣고 볶는다","라유를 넣는다","간장으로 간하고 대파를 올린다"]}',
 ARRAY['spicy','stir_fry','seafood','quick']),

('chinese-021', 'seed',
 '{"ko":"칠리새우","en":"Chili Shrimp","ja":"エビチリ","zh":"干烧虾仁"}',
 '{"ko":"매콤달콤한 소스에 볶은 새우 요리","en":"Shrimp in sweet and spicy tomato sauce"}',
 25, 'easy', 2,
 '[{"name":"새우","quantity":"300g"},{"name":"케첩","quantity":"3큰술"},{"name":"두반장","quantity":"1큰술"},{"name":"설탕","quantity":"2큰술"},{"name":"마늘","quantity":"3쪽"},{"name":"생강","quantity":"1톨"}]',
 '{"ko":["새우를 손질한다","마늘, 생강을 다진다","팬에 마늘, 생강을 볶는다","새우를 넣고 볶는다","케첩, 두반장, 설탕으로 만든 소스를 넣고 볶는다"]}',
 ARRAY['spicy','stir_fry','seafood','quick']),

('chinese-022', 'seed',
 '{"ko":"고추잡채","en":"Gochujapchae","ja":"唐辛子雑菜","zh":"辣椒杂菜"}',
 '{"ko":"고추와 야채, 고기를 볶은 중국식 잡채","en":"Stir-fried vegetables and meat with peppers"}',
 25, 'easy', 3,
 '[{"name":"당면","quantity":"200g"},{"name":"돼지고기","quantity":"150g"},{"name":"청양고추","quantity":"3개"},{"name":"양파","quantity":"1개"},{"name":"파프리카","quantity":"1개"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["당면을 삶는다","고기와 야채를 썬다","팬에 고기를 볶는다","야채를 넣고 볶는다","당면을 넣고 간장으로 간을 한다"]}',
 ARRAY['spicy','stir_fry','meat','noodle']),

('chinese-023', 'seed',
 '{"ko":"팔보채","en":"Palbochae","ja":"八宝菜","zh":"八宝菜"}',
 '{"ko":"8가지 재료가 들어간 걸쭉한 중국식 볶음 요리","en":"Eight treasure stir-fry with thick sauce"}',
 30, 'medium', 3,
 '[{"name":"새우","quantity":"100g"},{"name":"오징어","quantity":"100g"},{"name":"돼지고기","quantity":"100g"},{"name":"배추","quantity":"3잎"},{"name":"당근","quantity":"1개"},{"name":"죽순","quantity":"100g"},{"name":"목이버섯","quantity":"50g"},{"name":"전분물","quantity":"5큰술"}]',
 '{"ko":["모든 재료를 손질한다","팬에 고기와 해물을 볶는다","야채를 넣고 볶는다","물을 붓고 끓인다","전분물로 걸쭉하게 만든다"]}',
 ARRAY['mild','stir_fry','seafood','heavy']),

('chinese-024', 'seed',
 '{"ko":"동파육","en":"Dongpo Pork","ja":"東坡肉","zh":"东坡肉"}',
 '{"ko":"간장에 오래 조린 부드러운 돼지고기 요리","en":"Braised pork belly in soy sauce"}',
 120, 'hard', 4,
 '[{"name":"삼겹살","quantity":"800g"},{"name":"대파","quantity":"2대"},{"name":"생강","quantity":"1톨"},{"name":"간장","quantity":"1/2컵"},{"name":"설탕","quantity":"5큰술"},{"name":"청주","quantity":"1/2컵"}]',
 '{"ko":["삼겹살을 큼직하게 자른다","끓는 물에 데친다","냄비에 삼겹살을 담고 간장, 설탕, 청주를 넣는다","대파, 생강을 넣는다","약불에서 2시간 조린다","부드럽게 익을 때까지 졸인다"]}',
 ARRAY['mild','meat','heavy']),

('chinese-025', 'seed',
 '{"ko":"류산슬","en":"Yuxiang Shredded Pork","ja":"魚香肉絲","zh":"鱼香肉丝"}',
 '{"ko":"어향 소스에 볶은 돼지고기 채 요리","en":"Shredded pork in garlic sauce"}',
 25, 'easy', 2,
 '[{"name":"돼지고기","quantity":"200g"},{"name":"목이버섯","quantity":"30g"},{"name":"죽순","quantity":"100g"},{"name":"당근","quantity":"1/2개"},{"name":"두반장","quantity":"1큰술"},{"name":"간장","quantity":"2큰술"},{"name":"식초","quantity":"1큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["모든 재료를 채썬다","팬에 돼지고기를 볶는다","야채를 넣고 볶는다","두반장, 간장, 식초, 설탕으로 만든 소스를 넣는다","잘 볶아 완성한다"]}',
 ARRAY['spicy','stir_fry','meat','quick']),

-- === 만두/딤섬 (Dumplings & Dim Sum) ===
('chinese-026', 'seed',
 '{"ko":"군만두","en":"Pan-fried Dumplings","ja":"焼き餃子","zh":"煎饺"}',
 '{"ko":"바삭하게 구운 중국식 만두","en":"Crispy pan-fried Chinese dumplings"}',
 30, 'medium', 3,
 '[{"name":"만두피","quantity":"30장"},{"name":"돼지고기","quantity":"300g"},{"name":"배추","quantity":"3잎"},{"name":"부추","quantity":"50g"},{"name":"생강","quantity":"1톨"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["배추와 부추를 다진다","돼지고기에 야채와 양념을 섞는다","만두피에 소를 넣고 빚는다","팬에 기름을 두르고 만두를 올린다","물을 붓고 뚜껑을 덮어 찐다","바닥이 바삭해질 때까지 굽는다"]}',
 ARRAY['mild','meat','side_dish','dim_sum']),

('chinese-027', 'seed',
 '{"ko":"물만두","en":"Boiled Dumplings","ja":"水餃子","zh":"水饺"}',
 '{"ko":"끓는 물에 삶은 중국식 만두","en":"Boiled Chinese dumplings"}',
 25, 'medium', 3,
 '[{"name":"만두피","quantity":"30장"},{"name":"돼지고기","quantity":"300g"},{"name":"배추","quantity":"3잎"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["배추와 대파를 다진다","돼지고기에 야채와 양념을 섞는다","만두피에 소를 넣고 빚는다","끓는 물에 만두를 넣는다","떠오르면 찬물을 붓고 다시 끓인다","3번 반복해서 완전히 익힌다"]}',
 ARRAY['mild','meat','dim_sum']),

('chinese-028', 'seed',
 '{"ko":"찐만두","en":"Steamed Dumplings","ja":"蒸し餃子","zh":"蒸饺"}',
 '{"ko":"쪄서 만든 부드러운 중국식 만두","en":"Soft steamed Chinese dumplings"}',
 25, 'medium', 3,
 '[{"name":"만두피","quantity":"30장"},{"name":"새우","quantity":"200g"},{"name":"돼지고기","quantity":"100g"},{"name":"죽순","quantity":"50g"},{"name":"생강","quantity":"1톨"}]',
 '{"ko":["새우를 다진다","돼지고기, 죽순, 생강을 섞는다","만두피에 소를 넣고 빚는다","찜통에 면보를 깔고 만두를 올린다","15분간 찐다"]}',
 ARRAY['mild','seafood','dim_sum']),

('chinese-029', 'seed',
 '{"ko":"샤오롱바오","en":"Xiaolongbao","ja":"小籠包","zh":"小笼包"}',
 '{"ko":"육즙이 가득한 상하이식 찐만두","en":"Shanghainese soup dumplings"}',
 60, 'hard', 4,
 '[{"name":"만두피","quantity":"40장"},{"name":"돼지고기","quantity":"300g"},{"name":"돼지껍질","quantity":"100g"},{"name":"대파","quantity":"2대"},{"name":"생강","quantity":"1톨"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["돼지껍질을 삶아 육수를 만들고 식혀 굳힌다","돼지고기에 양념을 한다","굳힌 육수를 깍둑썰기해서 고기에 섞는다","만두피에 소를 넣고 주름을 잡아 빚는다","찜통에 쪄낸다"]}',
 ARRAY['mild','meat','dim_sum']),

('chinese-030', 'seed',
 '{"ko":"하가우","en":"Har Gow","ja":"蝦餃","zh":"虾饺"}',
 '{"ko":"새우가 들어간 투명한 피의 광둥식 딤섬","en":"Cantonese shrimp dumplings with translucent wrapper"}',
 45, 'hard', 3,
 '[{"name":"밀가루","quantity":"100g"},{"name":"감자전분","quantity":"100g"},{"name":"새우","quantity":"300g"},{"name":"죽순","quantity":"50g"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["밀가루와 전분을 섞어 반죽한다","새우를 다지고 죽순을 다진다","새우에 양념을 한다","얇게 민 피에 새우소를 넣고 빚는다","찜통에 쪄낸다"]}',
 ARRAY['mild','seafood','dim_sum']),

('chinese-031', 'seed',
 '{"ko":"슈마이","en":"Shumai","ja":"シュウマイ","zh":"烧卖"}',
 '{"ko":"위가 열린 형태의 중국식 찐만두","en":"Open-topped Chinese steamed dumplings"}',
 30, 'medium', 3,
 '[{"name":"만두피","quantity":"30장"},{"name":"돼지고기","quantity":"200g"},{"name":"새우","quantity":"100g"},{"name":"표고버섯","quantity":"3개"},{"name":"생강","quantity":"1톨"}]',
 '{"ko":["새우와 표고버섯을 다진다","돼지고기에 섞어 양념한다","만두피에 소를 넣고 위를 열어 모양을 만든다","찜통에 쪄낸다"]}',
 ARRAY['mild','meat','seafood','dim_sum']),

('chinese-032', 'seed',
 '{"ko":"완탕","en":"Wonton","ja":"ワンタン","zh":"馄饨"}',
 '{"ko":"국물에 넣어 먹는 작은 중국식 만두","en":"Small Chinese dumplings in soup"}',
 30, 'easy', 3,
 '[{"name":"완탕피","quantity":"40장"},{"name":"돼지고기","quantity":"200g"},{"name":"새우","quantity":"100g"},{"name":"대파","quantity":"1대"},{"name":"육수","quantity":"4컵"}]',
 '{"ko":["돼지고기와 새우를 다진다","대파를 다져 섞는다","완탕피에 소를 넣고 빚는다","육수를 끓인다","완탕을 넣고 떠오를 때까지 끓인다"]}',
 ARRAY['mild','soupy','meat','seafood','dim_sum']),

('chinese-033', 'seed',
 '{"ko":"춘권","en":"Spring Roll","ja":"春巻き","zh":"春卷"}',
 '{"ko":"바삭하게 튀긴 중국식 봄말이","en":"Crispy fried spring rolls"}',
 35, 'medium', 4,
 '[{"name":"춘권피","quantity":"20장"},{"name":"돼지고기","quantity":"150g"},{"name":"당면","quantity":"100g"},{"name":"배추","quantity":"3잎"},{"name":"당근","quantity":"1개"},{"name":"표고버섯","quantity":"3개"}]',
 '{"ko":["당면을 불린다","야채를 채썬다","팬에 고기와 야채를 볶는다","춘권피에 소를 넣고 만다","기름에 튀긴다"]}',
 ARRAY['mild','deep_fried','meat','side_dish','dim_sum']),

('chinese-034', 'seed',
 '{"ko":"차슈바오","en":"Char Siu Bao","ja":"チャーシューバオ","zh":"叉烧包"}',
 '{"ko":"달콤한 차슈가 들어간 찐빵","en":"Steamed buns with sweet barbecue pork"}',
 90, 'hard', 6,
 '[{"name":"밀가루","quantity":"300g"},{"name":"이스트","quantity":"5g"},{"name":"차슈","quantity":"200g"},{"name":"설탕","quantity":"3큰술"},{"name":"굴소스","quantity":"2큰술"}]',
 '{"ko":["밀가루에 이스트를 넣고 반죽해 발효시킨다","차슈를 다지고 설탕, 굴소스로 양념한다","반죽을 나눠 소를 넣고 빚는다","찜통에 넣고 15분 찐다"]}',
 ARRAY['mild','meat','dim_sum']),

('chinese-035', 'seed',
 '{"ko":"꽃빵","en":"Flower Bun","ja":"花巻","zh":"花卷"}',
 '{"ko":"나선형 모양의 중국식 찐빵","en":"Chinese steamed spiral buns"}',
 70, 'medium', 6,
 '[{"name":"밀가루","quantity":"300g"},{"name":"이스트","quantity":"5g"},{"name":"설탕","quantity":"2큰술"},{"name":"참기름","quantity":"2큰술"},{"name":"대파","quantity":"2대"}]',
 '{"ko":["밀가루에 이스트를 넣고 반죽해 발효시킨다","반죽을 밀어 참기름과 대파를 바른다","돌돌 말아 썬다","꼬아서 모양을 만든다","찜통에 15분 찐다"]}',
 ARRAY['mild','veggie','dim_sum']),

-- === 해물 요리 (Seafood) ===
('chinese-036', 'seed',
 '{"ko":"깐쇼새우","en":"Dry Fried Shrimp","ja":"乾焼蝦仁","zh":"干烧虾"}',
 '{"ko":"바삭하게 튀긴 새우를 매콤달콤하게 볶은 요리","en":"Crispy fried shrimp in sweet and spicy sauce"}',
 30, 'medium', 2,
 '[{"name":"새우","quantity":"300g"},{"name":"마늘","quantity":"5쪽"},{"name":"생강","quantity":"1톨"},{"name":"케첩","quantity":"3큰술"},{"name":"설탕","quantity":"2큰술"},{"name":"전분","quantity":"1/2컵"}]',
 '{"ko":["새우를 손질하고 전분을 묻힌다","바삭하게 튀긴다","팬에 마늘과 생강을 볶는다","케첩, 설탕으로 소스를 만든다","튀긴 새우를 넣고 볶는다"]}',
 ARRAY['spicy','deep_fried','seafood']),

('chinese-037', 'seed',
 '{"ko":"게요리","en":"Stir-fried Crab","ja":"蟹炒め","zh":"炒蟹"}',
 '{"ko":"통게를 매콤하게 볶은 요리","en":"Spicy stir-fried whole crab"}',
 35, 'medium', 3,
 '[{"name":"게","quantity":"2마리"},{"name":"마늘","quantity":"10쪽"},{"name":"생강","quantity":"1톨"},{"name":"대파","quantity":"2대"},{"name":"두반장","quantity":"2큰술"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["게를 손질해 토막낸다","팬에 마늘, 생강을 볶는다","게를 넣고 볶는다","두반장과 간장을 넣는다","대파를 넣고 마무리한다"]}',
 ARRAY['spicy','stir_fry','seafood','heavy']),

('chinese-038', 'seed',
 '{"ko":"게살배추","en":"Crab with Napa Cabbage","ja":"蟹肉白菜","zh":"蟹粉白菜"}',
 '{"ko":"게살과 배추를 부드럽게 볶은 요리","en":"Stir-fried napa cabbage with crab meat"}',
 20, 'easy', 2,
 '[{"name":"게살","quantity":"150g"},{"name":"배추","quantity":"1/2포기"},{"name":"마늘","quantity":"3쪽"},{"name":"굴소스","quantity":"2큰술"},{"name":"전분물","quantity":"3큰술"}]',
 '{"ko":["배추를 썬다","팬에 마늘을 볶는다","배추를 넉넉히 볶는다","게살을 넣는다","굴소스로 간하고 전분물로 걸쭉하게 만든다"]}',
 ARRAY['mild','stir_fry','seafood','light','quick']),

('chinese-039', 'seed',
 '{"ko":"새우칠리소스","en":"Shrimp in Chili Sauce","ja":"エビのチリソース煮","zh":"辣酱虾"}',
 '{"ko":"새우를 걸쭉한 칠리소스에 조린 요리","en":"Shrimp braised in thick chili sauce"}',
 25, 'easy', 2,
 '[{"name":"새우","quantity":"300g"},{"name":"케첩","quantity":"4큰술"},{"name":"두반장","quantity":"1큰술"},{"name":"설탕","quantity":"2큰술"},{"name":"전분물","quantity":"3큰술"}]',
 '{"ko":["새우를 손질한다","팬에 새우를 볶는다","케첩, 두반장, 설탕을 섞어 넣는다","물을 붓고 끓인다","전분물로 걸쭉하게 만든다"]}',
 ARRAY['spicy','stir_fry','seafood','quick']),

('chinese-040', 'seed',
 '{"ko":"전복요리","en":"Braised Abalone","ja":"アワビの煮込み","zh":"红烧鲍鱼"}',
 '{"ko":"전복을 간장에 조린 고급 요리","en":"Premium abalone braised in soy sauce"}',
 90, 'hard', 4,
 '[{"name":"전복","quantity":"8개"},{"name":"간장","quantity":"1/2컵"},{"name":"설탕","quantity":"3큰술"},{"name":"대파","quantity":"2대"},{"name":"생강","quantity":"1톨"},{"name":"청주","quantity":"1/4컵"}]',
 '{"ko":["전복을 손질한다","냄비에 전복과 양념을 넣는다","물을 붓고 끓인다","약불에서 1시간 조린다","소스가 걸쭉해질 때까지 졸인다"]}',
 ARRAY['mild','seafood','heavy']),

('chinese-041', 'seed',
 '{"ko":"마늘새우","en":"Garlic Shrimp","ja":"ガーリックシュリンプ","zh":"蒜蓉虾"}',
 '{"ko":"마늘을 듬뿍 넣어 볶은 새우 요리","en":"Shrimp stir-fried with plenty of garlic"}',
 15, 'easy', 2,
 '[{"name":"새우","quantity":"300g"},{"name":"마늘","quantity":"15쪽"},{"name":"버터","quantity":"30g"},{"name":"청주","quantity":"2큰술"},{"name":"파슬리","quantity":"약간"}]',
 '{"ko":["새우를 손질한다","마늘을 다진다","팬에 버터를 녹이고 마늘을 볶는다","새우를 넣고 볶는다","청주를 넣고 파슬리를 뿌린다"]}',
 ARRAY['mild','stir_fry','seafood','quick']),

('chinese-042', 'seed',
 '{"ko":"깐쇼새우살","en":"Dry Fried Shrimp Meat","ja":"海老のピリ辛炒め","zh":"干烧虾仁"}',
 '{"ko":"새우살을 바삭하게 튀겨 매콤하게 볶은 요리","en":"Crispy fried shrimp meat in spicy sauce"}',
 25, 'medium', 2,
 '[{"name":"새우살","quantity":"250g"},{"name":"건고추","quantity":"10개"},{"name":"마늘","quantity":"5쪽"},{"name":"두반장","quantity":"1큰술"},{"name":"전분","quantity":"5큰술"}]',
 '{"ko":["새우살에 전분을 묻혀 튀긴다","팬에 건고추와 마늘을 볶는다","두반장을 넣는다","튀긴 새우를 넣고 빠르게 볶는다"]}',
 ARRAY['spicy','deep_fried','seafood','quick']),

('chinese-043', 'seed',
 '{"ko":"오징어볶음","en":"Stir-fried Squid","ja":"イカ炒め","zh":"炒鱿鱼"}',
 '{"ko":"오징어와 야채를 볶은 요리","en":"Stir-fried squid with vegetables"}',
 20, 'easy', 2,
 '[{"name":"오징어","quantity":"2마리"},{"name":"양파","quantity":"1개"},{"name":"피망","quantity":"2개"},{"name":"당근","quantity":"1/2개"},{"name":"굴소스","quantity":"2큰술"}]',
 '{"ko":["오징어를 손질해 썬다","야채를 썬다","팬에 오징어를 볶는다","야채를 넣고 볶는다","굴소스로 간을 한다"]}',
 ARRAY['mild','stir_fry','seafood','quick']),

('chinese-044', 'seed',
 '{"ko":"마늘소스새우","en":"Shrimp in Garlic Sauce","ja":"ガーリックソースエビ","zh":"蒜茸汁虾"}',
 '{"ko":"진한 마늘 소스에 버무린 새우 요리","en":"Shrimp tossed in rich garlic sauce"}',
 20, 'easy', 2,
 '[{"name":"새우","quantity":"300g"},{"name":"마늘","quantity":"10쪽"},{"name":"굴소스","quantity":"2큰술"},{"name":"전분물","quantity":"2큰술"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["새우를 손질한다","마늘을 다진다","팬에 마늘을 볶는다","새우를 넣고 볶는다","굴소스와 전분물로 소스를 만들어 버무린다"]}',
 ARRAY['mild','stir_fry','seafood','quick']),

('chinese-045', 'seed',
 '{"ko":"랍스터요리","en":"Lobster Cantonese","ja":"ロブスター広東風","zh":"龙虾广东"}',
 '{"ko":"랍스터를 광둥식으로 찐 고급 요리","en":"Premium Cantonese-style steamed lobster"}',
 25, 'medium', 3,
 '[{"name":"랍스터","quantity":"1마리"},{"name":"마늘","quantity":"10쪽"},{"name":"생강","quantity":"1톨"},{"name":"대파","quantity":"2대"},{"name":"간장","quantity":"3큰술"},{"name":"청주","quantity":"2큰술"}]',
 '{"ko":["랍스터를 손질한다","마늘, 생강, 대파를 썬다","랍스터에 간장, 청주를 바른다","마늘과 생강을 얹어 찐다","대파를 올리고 뜨거운 기름을 부어낸다"]}',
 ARRAY['mild','steamed','seafood','heavy']),

-- === 야채 요리 (Vegetable) ===
('chinese-046', 'seed',
 '{"ko":"깐풍두부","en":"Dry Fried Tofu","ja":"乾焼豆腐","zh":"干烹豆腐"}',
 '{"ko":"두부를 튀겨 매콤하게 볶은 요리","en":"Crispy fried tofu in spicy sauce"}',
 25, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"마늘","quantity":"5쪽"},{"name":"고추","quantity":"5개"},{"name":"간장","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"},{"name":"전분","quantity":"5큰술"}]',
 '{"ko":["두부를 깍둑썰기해 전분을 묻힌다","바삭하게 튀긴다","팬에 마늘과 고추를 볶는다","간장, 설탕 양념을 넣는다","튀긴 두부를 넣고 볶는다"]}',
 ARRAY['spicy','deep_fried','veggie','quick']),

('chinese-047', 'seed',
 '{"ko":"마라가지","en":"Spicy Eggplant","ja":"麻辣茄子","zh":"麻辣茄子"}',
 '{"ko":"가지를 얼얼하게 볶은 사천식 요리","en":"Sichuan-style spicy eggplant"}',
 20, 'easy', 2,
 '[{"name":"가지","quantity":"3개"},{"name":"마늘","quantity":"5쪽"},{"name":"두반장","quantity":"2큰술"},{"name":"화자오","quantity":"1큰술"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["가지를 썬다","팬에 가지를 볶는다","마늘을 넣고 볶는다","두반장과 화자오를 넣는다","간장으로 간을 한다"]}',
 ARRAY['spicy','stir_fry','veggie','quick']),

('chinese-048', 'seed',
 '{"ko":"버섯볶음","en":"Stir-fried Mushrooms","ja":"きのこ炒め","zh":"炒蘑菇"}',
 '{"ko":"여러 가지 버섯을 볶은 요리","en":"Stir-fried mixed mushrooms"}',
 15, 'easy', 2,
 '[{"name":"표고버섯","quantity":"5개"},{"name":"느타리버섯","quantity":"100g"},{"name":"팽이버섯","quantity":"1봉"},{"name":"마늘","quantity":"3쪽"},{"name":"굴소스","quantity":"2큰술"}]',
 '{"ko":["버섯을 손질한다","팬에 마늘을 볶는다","버섯을 넣고 볶는다","굴소스로 간을 한다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

('chinese-049', 'seed',
 '{"ko":"청경채볶음","en":"Stir-fried Bok Choy","ja":"チンゲン菜炒め","zh":"炒青菜"}',
 '{"ko":"청경채를 간단하게 볶은 요리","en":"Simple stir-fried bok choy"}',
 10, 'easy', 2,
 '[{"name":"청경채","quantity":"3포기"},{"name":"마늘","quantity":"3쪽"},{"name":"굴소스","quantity":"1큰술"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["청경채를 씻는다","팬에 마늘을 볶는다","청경채를 넣고 볶는다","굴소스로 간을 하고 참기름을 두른다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

('chinese-050', 'seed',
 '{"ko":"토마토계란볶음","en":"Tomato and Egg Stir-fry","ja":"トマト卵炒め","zh":"番茄炒蛋"}',
 '{"ko":"토마토와 계란을 볶은 중국 가정식","en":"Chinese home-style tomato and egg stir-fry"}',
 15, 'easy', 2,
 '[{"name":"토마토","quantity":"3개"},{"name":"계란","quantity":"4개"},{"name":"설탕","quantity":"1큰술"},{"name":"소금","quantity":"약간"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["토마토를 깍둑썰기한다","계란을 풀어 볶아 덜어둔다","팬에 토마토를 볶는다","설탕과 소금으로 간을 한다","계란을 다시 넣고 섞는다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

('chinese-051', 'seed',
 '{"ko":"건두부볶음","en":"Stir-fried Dried Tofu","ja":"干し豆腐炒め","zh":"炒豆腐干"}',
 '{"ko":"건두부를 채썰어 볶은 요리","en":"Stir-fried shredded dried tofu"}',
 15, 'easy', 2,
 '[{"name":"건두부","quantity":"200g"},{"name":"부추","quantity":"50g"},{"name":"당근","quantity":"1/2개"},{"name":"간장","quantity":"2큰술"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["건두부를 채썬다","부추와 당근을 썬다","팬에 건두부를 볶는다","야채를 넣고 볶는다","간장으로 간을 하고 참기름을 두른다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

('chinese-052', 'seed',
 '{"ko":"공심채볶음","en":"Stir-fried Water Spinach","ja":"空芯菜炒め","zh":"炒空心菜"}',
 '{"ko":"공심채를 마늘과 함께 볶은 요리","en":"Water spinach stir-fried with garlic"}',
 10, 'easy', 2,
 '[{"name":"공심채","quantity":"300g"},{"name":"마늘","quantity":"5쪽"},{"name":"굴소스","quantity":"1큰술"},{"name":"고추","quantity":"2개"}]',
 '{"ko":["공심채를 씻어 자른다","팬에 마늘과 고추를 볶는다","공심채를 넣고 센불에서 빠르게 볶는다","굴소스로 간을 한다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

('chinese-053', 'seed',
 '{"ko":"숙주나물볶음","en":"Stir-fried Bean Sprouts","ja":"もやし炒め","zh":"炒豆芽"}',
 '{"ko":"숙주나물을 볶은 간단한 요리","en":"Simple stir-fried bean sprouts"}',
 10, 'easy', 2,
 '[{"name":"숙주나물","quantity":"300g"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"},{"name":"참기름","quantity":"1큰술"},{"name":"소금","quantity":"약간"}]',
 '{"ko":["숙주나물을 씻는다","팬에 대파를 볶는다","숙주나물을 넣고 센불에서 빠르게 볶는다","간장과 소금으로 간을 하고 참기름을 두른다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

('chinese-054', 'seed',
 '{"ko":"브로콜리볶음","en":"Stir-fried Broccoli","ja":"ブロッコリー炒め","zh":"炒西兰花"}',
 '{"ko":"브로콜리를 마늘과 함께 볶은 요리","en":"Broccoli stir-fried with garlic"}',
 15, 'easy', 2,
 '[{"name":"브로콜리","quantity":"1개"},{"name":"마늘","quantity":"4쪽"},{"name":"굴소스","quantity":"2큰술"},{"name":"전분물","quantity":"2큰술"}]',
 '{"ko":["브로콜리를 손질해 데친다","팬에 마늘을 볶는다","브로콜리를 넣고 볶는다","굴소스와 전분물로 소스를 만들어 버무린다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

('chinese-055', 'seed',
 '{"ko":"콩나물볶음","en":"Stir-fried Soybean Sprouts","ja":"大豆もやし炒め","zh":"炒黄豆芽"}',
 '{"ko":"콩나물을 고추와 함께 볶은 요리","en":"Soybean sprouts stir-fried with peppers"}',
 12, 'easy', 2,
 '[{"name":"콩나물","quantity":"300g"},{"name":"고추","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["콩나물을 씻는다","팬에 고추와 대파를 볶는다","콩나물을 넣고 볶는다","간장으로 간을 하고 참기름을 두른다"]}',
 ARRAY['mild','stir_fry','veggie','light','quick']),

-- === 탕/찜 (Soup & Steamed) ===
('chinese-056', 'seed',
 '{"ko":"훠궈","en":"Hot Pot","ja":"火鍋","zh":"火锅"}',
 '{"ko":"다양한 재료를 육수에 넣어 끓이며 먹는 중국식 전골","en":"Chinese hot pot with various ingredients"}',
 60, 'easy', 4,
 '[{"name":"양고기","quantity":"300g"},{"name":"소고기","quantity":"200g"},{"name":"배추","quantity":"1/2포기"},{"name":"버섯","quantity":"200g"},{"name":"두부","quantity":"1모"},{"name":"당면","quantity":"200g"},{"name":"훠궈 육수","quantity":"1팩"}]',
 '{"ko":["육수를 끓인다","고기와 야채를 손질해 준비한다","끓는 육수에 원하는 재료를 넣어 익혀 먹는다","참깨 소스나 마늘 소스에 찍어 먹는다"]}',
 ARRAY['spicy','soupy','meat','heavy']),

('chinese-057', 'seed',
 '{"ko":"사골탕","en":"Bone Soup","ja":"骨スープ","zh":"骨头汤"}',
 '{"ko":"사골을 오래 끓인 구수한 육수","en":"Rich soup made from simmered beef bones"}',
 180, 'easy', 6,
 '[{"name":"사골","quantity":"2kg"},{"name":"대파","quantity":"3대"},{"name":"마늘","quantity":"10쪽"},{"name":"생강","quantity":"1톨"},{"name":"청주","quantity":"1/2컵"}]',
 '{"ko":["사골을 물에 담가 핏물을 뺀다","끓는 물에 사골을 데쳐 씻는다","냄비에 사골과 물을 넉넉히 붓는다","대파, 마늘, 생강을 넣는다","3시간 이상 푹 끓인다","소금으로 간을 한다"]}',
 ARRAY['mild','soupy','meat','heavy']),

('chinese-058', 'seed',
 '{"ko":"완자탕","en":"Meatball Soup","ja":"肉団子スープ","zh":"丸子汤"}',
 '{"ko":"고기 완자가 들어간 맑은 국물","en":"Clear soup with meat balls"}',
 30, 'easy', 3,
 '[{"name":"돼지고기","quantity":"300g"},{"name":"두부","quantity":"1/2모"},{"name":"대파","quantity":"2대"},{"name":"계란","quantity":"1개"},{"name":"배추","quantity":"3잎"},{"name":"육수","quantity":"6컵"}]',
 '{"ko":["돼지고기를 다져 두부, 계란을 섞어 완자를 빚는다","육수를 끓인다","완자를 넣고 끓인다","배추와 대파를 넣는다","소금으로 간을 한다"]}',
 ARRAY['mild','soupy','meat','light']),

('chinese-059', 'seed',
 '{"ko":"신라탕","en":"Hot and Sour Soup","ja":"酸辣湯","zh":"酸辣汤"}',
 '{"ko":"새콤하고 매콤한 중국식 수프","en":"Chinese hot and sour soup"}',
 25, 'easy', 3,
 '[{"name":"두부","quantity":"1모"},{"name":"죽순","quantity":"100g"},{"name":"목이버섯","quantity":"30g"},{"name":"계란","quantity":"2개"},{"name":"식초","quantity":"3큰술"},{"name":"고춧가루","quantity":"1큰술"},{"name":"전분물","quantity":"5큰술"}]',
 '{"ko":["두부, 죽순, 버섯을 채썬다","육수를 끓이고 재료를 넣는다","식초와 고춧가루로 맛을 낸다","전분물로 걸쭉하게 만든다","계란을 풀어 넣는다"]}',
 ARRAY['spicy','soupy','veggie','light','quick']),

('chinese-060', 'seed',
 '{"ko":"계란탕","en":"Egg Drop Soup","ja":"卵スープ","zh":"蛋花汤"}',
 '{"ko":"계란을 풀어 넣은 간단한 중국식 수프","en":"Simple Chinese egg drop soup"}',
 10, 'easy', 2,
 '[{"name":"계란","quantity":"3개"},{"name":"대파","quantity":"1대"},{"name":"육수","quantity":"4컵"},{"name":"소금","quantity":"약간"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["육수를 끓인다","소금으로 간을 한다","계란을 풀어 천천히 붓는다","대파를 썰어 올린다","참기름을 두른다"]}',
 ARRAY['mild','soupy','light','quick']),

('chinese-061', 'seed',
 '{"ko":"옥수수수프","en":"Corn Soup","ja":"コーンスープ","zh":"玉米羹"}',
 '{"ko":"옥수수가 들어간 걸쭉한 중국식 수프","en":"Thick Chinese corn soup"}',
 20, 'easy', 3,
 '[{"name":"옥수수","quantity":"2개"},{"name":"계란","quantity":"2개"},{"name":"게살","quantity":"50g"},{"name":"우유","quantity":"1컵"},{"name":"전분물","quantity":"5큰술"}]',
 '{"ko":["옥수수를 갈아 육수와 섞는다","끓이면서 우유를 넣는다","게살을 넣는다","전분물로 걸쭉하게 만든다","계란을 풀어 넣는다"]}',
 ARRAY['mild','soupy','light','quick']),

('chinese-062', 'seed',
 '{"ko":"어향가지찜","en":"Steamed Eggplant in Garlic Sauce","ja":"蒸し茄子魚香風味","zh":"鱼香茄子"}',
 '{"ko":"가지를 쪄서 어향 소스를 곁들인 요리","en":"Steamed eggplant with garlic sauce"}',
 25, 'easy', 2,
 '[{"name":"가지","quantity":"3개"},{"name":"마늘","quantity":"5쪽"},{"name":"생강","quantity":"1톨"},{"name":"두반장","quantity":"1큰술"},{"name":"간장","quantity":"2큰술"},{"name":"식초","quantity":"1큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["가지를 쪄낸다","마늘과 생강을 다진다","팬에 두반장을 볶는다","간장, 식초, 설탕을 넣어 소스를 만든다","찐 가지에 소스를 부어낸다"]}',
 ARRAY['spicy','steamed','veggie','light']),

('chinese-063', 'seed',
 '{"ko":"청경채찜","en":"Steamed Bok Choy","ja":"蒸し青梗菜","zh":"蒸青菜"}',
 '{"ko":"청경채를 쪄서 소스를 곁들인 요리","en":"Steamed bok choy with sauce"}',
 15, 'easy', 2,
 '[{"name":"청경채","quantity":"4포기"},{"name":"마늘","quantity":"5쪽"},{"name":"굴소스","quantity":"2큰술"},{"name":"간장","quantity":"1큰술"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["청경채를 씻는다","찜통에 쪄낸다","마늘을 다져 굴소스, 간장과 섞는다","뜨거운 참기름을 부어 소스를 만든다","찐 청경채에 소스를 뿌린다"]}',
 ARRAY['mild','steamed','veggie','light','quick']),

('chinese-064', 'seed',
 '{"ko":"계란찜","en":"Steamed Egg","ja":"蒸し卵","zh":"蒸蛋"}',
 '{"ko":"부드럽게 쪄낸 중국식 계란찜","en":"Silky Chinese steamed egg"}',
 15, 'easy', 2,
 '[{"name":"계란","quantity":"3개"},{"name":"물","quantity":"1컵"},{"name":"소금","quantity":"약간"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["계란을 풀어 물과 섞는다","소금으로 간을 한다","체에 거른다","찜통에 넣고 약불에서 찐다","대파와 간장을 올려 낸다"]}',
 ARRAY['mild','steamed','light','quick']),

('chinese-065', 'seed',
 '{"ko":"생선찜","en":"Steamed Fish","ja":"蒸し魚","zh":"清蒸鱼"}',
 '{"ko":"생선을 통째로 쪄내는 광둥식 요리","en":"Cantonese-style whole steamed fish"}',
 25, 'medium', 3,
 '[{"name":"도미","quantity":"1마리"},{"name":"대파","quantity":"3대"},{"name":"생강","quantity":"1톨"},{"name":"간장","quantity":"3큰술"},{"name":"청주","quantity":"2큰술"},{"name":"참기름","quantity":"2큰술"}]',
 '{"ko":["생선을 손질한다","생강과 대파를 얹는다","청주를 뿌리고 찜통에 찐다","뜨거운 간장과 참기름을 부어낸다","채썬 대파를 올린다"]}',
 ARRAY['mild','steamed','seafood','light']),

-- === 특별 요리 (Special) ===
('chinese-066', 'seed',
 '{"ko":"북경오리","en":"Peking Duck","ja":"北京ダック","zh":"北京烤鸭"}',
 '{"ko":"바삭하게 구운 오리를 얇은 전병에 싸먹는 북경 요리","en":"Crispy roasted duck wrapped in thin pancakes"}',
 180, 'hard', 6,
 '[{"name":"오리","quantity":"1마리"},{"name":"꿀","quantity":"3큰술"},{"name":"식초","quantity":"2큰술"},{"name":"전병","quantity":"20장"},{"name":"오이","quantity":"1개"},{"name":"대파","quantity":"3대"},{"name":"춘장","quantity":"5큰술"}]',
 '{"ko":["오리를 손질하고 끓는 물을 끼얹는다","꿀과 식초를 발라 말린다","오븐에서 1시간 반 굽는다","오이와 대파를 채썬다","오리 껍질을 저며 전병에 야채와 춘장을 곁들여 싸먹는다"]}',
 ARRAY['mild','grilled','meat','heavy']),

('chinese-067', 'seed',
 '{"ko":"양꼬치","en":"Lamb Skewers","ja":"羊肉串","zh":"羊肉串"}',
 '{"ko":"향신료를 뿌려 구운 양고기 꼬치","en":"Grilled lamb skewers with spices"}',
 30, 'easy', 3,
 '[{"name":"양고기","quantity":"500g"},{"name":"양파","quantity":"1개"},{"name":"쿠민","quantity":"2큰술"},{"name":"고춧가루","quantity":"1큰술"},{"name":"소금","quantity":"1큰술"}]',
 '{"ko":["양고기를 한입 크기로 자른다","꼬치에 양고기와 양파를 번갈아 꿴다","쿠민, 고춧가루, 소금을 섞는다","꼬치를 굽는다","향신료를 뿌리며 굽는다"]}',
 ARRAY['spicy','grilled','meat','heavy']),

('chinese-068', 'seed',
 '{"ko":"마늘쫑볶음","en":"Stir-fried Garlic Scapes","ja":"にんにくの芽炒め","zh":"炒蒜苔"}',
 '{"ko":"마늘쫑과 고기를 볶은 요리","en":"Stir-fried garlic scapes with meat"}',
 15, 'easy', 2,
 '[{"name":"마늘쫑","quantity":"200g"},{"name":"돼지고기","quantity":"150g"},{"name":"간장","quantity":"2큰술"},{"name":"굴소스","quantity":"1큰술"}]',
 '{"ko":["마늘쫑을 썬다","팬에 돼지고기를 볶는다","마늘쫑을 넣고 볶는다","간장과 굴소스로 간을 한다"]}',
 ARRAY['mild','stir_fry','veggie','meat','quick']),

('chinese-069', 'seed',
 '{"ko":"새우토스트","en":"Shrimp Toast","ja":"エビトースト","zh":"虾多士"}',
 '{"ko":"새우를 갈아 식빵에 발라 튀긴 요리","en":"Deep-fried bread topped with minced shrimp"}',
 25, 'medium', 4,
 '[{"name":"식빵","quantity":"8장"},{"name":"새우","quantity":"300g"},{"name":"계란","quantity":"1개"},{"name":"전분","quantity":"2큰술"},{"name":"참깨","quantity":"2큰술"}]',
 '{"ko":["새우를 다진다","계란과 전분을 섞는다","식빵에 새우를 펴 바른다","참깨를 뿌린다","기름에 튀긴다"]}',
 ARRAY['mild','deep_fried','seafood','side_dish','dim_sum']),

('chinese-070', 'seed',
 '{"ko":"라조면","en":"Sesame Noodles","ja":"汁なし担々麺","zh":"拌面"}',
 '{"ko":"참깨 소스에 비빈 면 요리","en":"Noodles tossed in sesame sauce"}',
 20, 'easy', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"참깨 페이스트","quantity":"3큰술"},{"name":"간장","quantity":"2큰술"},{"name":"식초","quantity":"1큰술"},{"name":"오이","quantity":"1개"},{"name":"당근","quantity":"1/2개"}]',
 '{"ko":["면을 삶아 찬물에 헹군다","참깨 페이스트, 간장, 식초를 섞어 소스를 만든다","오이와 당근을 채썬다","면에 소스를 넣고 비빈다","야채를 올려 낸다"]}',
 ARRAY['mild','noodle','veggie','quick']),

('chinese-071', 'seed',
 '{"ko":"물만두탕","en":"Wonton Soup","ja":"ワンタンスープ","zh":"馄饨汤"}',
 '{"ko":"완탕이 들어간 맑은 국물","en":"Clear soup with wontons"}',
 25, 'easy', 3,
 '[{"name":"완탕","quantity":"20개"},{"name":"육수","quantity":"6컵"},{"name":"청경채","quantity":"3포기"},{"name":"대파","quantity":"2대"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["육수를 끓인다","완탕을 넣고 끓인다","청경채를 넣는다","간장으로 간을 한다","대파를 올려 낸다"]}',
 ARRAY['mild','soupy','meat','light','dim_sum']),

('chinese-072', 'seed',
 '{"ko":"해파리냉채","en":"Jellyfish Salad","ja":"クラゲの冷菜","zh":"凉拌海蜇"}',
 '{"ko":"해파리를 새콤하게 무친 냉채","en":"Cold jellyfish salad with vinegar"}',
 20, 'easy', 3,
 '[{"name":"해파리","quantity":"200g"},{"name":"오이","quantity":"1개"},{"name":"당근","quantity":"1/2개"},{"name":"식초","quantity":"3큰술"},{"name":"설탕","quantity":"2큰술"},{"name":"참기름","quantity":"1큰술"}]',
 '{"ko":["해파리를 물에 담가 소금기를 뺀다","오이와 당근을 채썬다","식초, 설탕, 참기름으로 소스를 만든다","모든 재료를 섞어 차게 식힌다"]}',
 ARRAY['mild','seafood','light']),

('chinese-073', 'seed',
 '{"ko":"부추전","en":"Chive Pancake","ja":"ニラ焼き","zh":"韭菜盒子"}',
 '{"ko":"부추가 들어간 중국식 전","en":"Chinese pancake with chives"}',
 30, 'medium', 4,
 '[{"name":"밀가루","quantity":"2컵"},{"name":"부추","quantity":"200g"},{"name":"계란","quantity":"2개"},{"name":"새우","quantity":"100g"},{"name":"참기름","quantity":"2큰술"}]',
 '{"ko":["밀가루에 물을 넣어 반죽한다","부추와 새우를 다진다","계란을 섞어 소를 만든다","반죽을 밀어 소를 넣고 접는다","팬에 기름을 두르고 굽는다"]}',
 ARRAY['mild','veggie','seafood','side_dish']),

('chinese-074', 'seed',
 '{"ko":"중국식 미역국","en":"Chinese Seaweed Soup","ja":"中華わかめスープ","zh":"海带汤"}',
 '{"ko":"미역과 고기가 들어간 중국식 국물","en":"Chinese-style seaweed soup with meat"}',
 25, 'easy', 3,
 '[{"name":"미역","quantity":"30g"},{"name":"돼지고기","quantity":"150g"},{"name":"두부","quantity":"1모"},{"name":"대파","quantity":"1대"},{"name":"육수","quantity":"6컵"}]',
 '{"ko":["미역을 불린다","돼지고기를 볶는다","육수를 붓고 끓인다","미역과 두부를 넣는다","대파를 올려 낸다"]}',
 ARRAY['mild','soupy','meat','light']),

('chinese-075', 'seed',
 '{"ko":"중국식잡채","en":"Chinese Japchae","ja":"中華雑菜","zh":"炒粉丝"}',
 '{"ko":"당면과 야채를 볶은 중국식 잡채","en":"Chinese-style stir-fried glass noodles"}',
 25, 'easy', 3,
 '[{"name":"당면","quantity":"200g"},{"name":"돼지고기","quantity":"150g"},{"name":"배추","quantity":"3잎"},{"name":"당근","quantity":"1개"},{"name":"표고버섯","quantity":"3개"},{"name":"간장","quantity":"3큰술"}]',
 '{"ko":["당면을 불린다","야채와 고기를 썬다","팬에 고기를 볶는다","야채를 넣고 볶는다","당면을 넣고 간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','meat','noodle']),

('chinese-076', 'seed',
 '{"ko":"짜사이볶음","en":"Stir-fried Pickled Mustard Greens","ja":"搾菜炒め","zh":"炒榨菜"}',
 '{"ko":"짜사이와 고기를 볶은 요리","en":"Stir-fried pickled mustard greens with meat"}',
 15, 'easy', 2,
 '[{"name":"짜사이","quantity":"150g"},{"name":"돼지고기","quantity":"100g"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["짜사이를 씻어 물기를 뺀다","팬에 돼지고기를 볶는다","짜사이를 넣고 볶는다","대파를 넣고 간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','meat','quick']),

('chinese-077', 'seed',
 '{"ko":"아몬드두부","en":"Almond Tofu","ja":"杏仁豆腐","zh":"杏仁豆腐"}',
 '{"ko":"아몬드 향이 나는 중국식 디저트","en":"Chinese almond jelly dessert"}',
 30, 'easy', 4,
 '[{"name":"우유","quantity":"2컵"},{"name":"아몬드 에센스","quantity":"1큰술"},{"name":"한천가루","quantity":"2큰술"},{"name":"설탕","quantity":"5큰술"},{"name":"과일","quantity":"적당량"}]',
 '{"ko":["우유에 설탕을 넣고 데운다","한천가루를 넣고 녹인다","아몬드 에센스를 넣는다","틀에 부어 굳힌다","과일을 올려 차게 먹는다"]}',
 ARRAY['mild','light']),

('chinese-078', 'seed',
 '{"ko":"군밤","en":"Roasted Chestnuts","ja":"焼き栗","zh":"糖炒栗子"}',
 '{"ko":"설탕을 입혀 볶은 달콤한 밤","en":"Sweet roasted chestnuts with sugar coating"}',
 40, 'easy', 4,
 '[{"name":"밤","quantity":"500g"},{"name":"설탕","quantity":"3큰술"},{"name":"물","quantity":"1/2컵"},{"name":"식용유","quantity":"2큰술"}]',
 '{"ko":["밤에 칼집을 낸다","팬에 기름을 두르고 밤을 볶는다","설탕물을 부어가며 볶는다","밤이 터지고 익을 때까지 볶는다"]}',
 ARRAY['mild','light']),

('chinese-079', 'seed',
 '{"ko":"누룽지탕","en":"Scorched Rice Soup","ja":"おこげスープ","zh":"锅巴汤"}',
 '{"ko":"바삭한 누룽지에 뜨거운 국물을 부어 먹는 요리","en":"Crispy scorched rice with hot soup poured over"}',
 30, 'medium', 3,
 '[{"name":"누룽지","quantity":"200g"},{"name":"새우","quantity":"100g"},{"name":"오징어","quantity":"100g"},{"name":"야채","quantity":"200g"},{"name":"육수","quantity":"4컵"},{"name":"전분물","quantity":"5큰술"}]',
 '{"ko":["누룽지를 튀긴다","팬에 해물과 야채를 볶는다","육수를 붓고 끓인다","전분물로 걸쭉하게 만든다","누룽지에 뜨거운 국물을 부어낸다"]}',
 ARRAY['mild','soupy','seafood']),

('chinese-080', 'seed',
 '{"ko":"바싹두부","en":"Crispy Tofu","ja":"カリカリ豆腐","zh":"脆皮豆腐"}',
 '{"ko":"두부를 바삭하게 튀긴 요리","en":"Crispy fried tofu"}',
 20, 'easy', 2,
 '[{"name":"두부","quantity":"1모"},{"name":"전분","quantity":"1컵"},{"name":"소금","quantity":"1작은술"},{"name":"후추","quantity":"약간"}]',
 '{"ko":["두부를 깍둑썰기한다","전분에 소금, 후추를 섞는다","두부에 전분을 묻힌다","기름에 바삭하게 튀긴다","소금을 뿌려 낸다"]}',
 ARRAY['mild','deep_fried','veggie','quick']),

-- === 추가 볶음/고기 요리 ===
('chinese-081', 'seed',
 '{"ko":"삼선볶음밥","en":"Samseon Fried Rice","ja":"三鮮炒飯","zh":"三鲜炒饭"}',
 '{"ko":"새우, 오징어, 해삼이 들어간 고급 볶음밥","en":"Premium fried rice with shrimp, squid, and sea cucumber"}',
 25, 'medium', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"새우","quantity":"5마리"},{"name":"오징어","quantity":"100g"},{"name":"해삼","quantity":"1개"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["해물을 손질한다","팬에 계란을 볶는다","밥을 넣고 볶는다","해물을 넣고 볶는다","대파를 넣고 간을 한다"]}',
 ARRAY['mild','stir_fry','seafood','rice']),

('chinese-082', 'seed',
 '{"ko":"송이버섯볶음밥","en":"Mushroom Fried Rice","ja":"松茸炒飯","zh":"松茸炒饭"}',
 '{"ko":"송이버섯이 들어간 향긋한 볶음밥","en":"Fragrant fried rice with pine mushrooms"}',
 20, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"송이버섯","quantity":"2개"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"1대"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["송이버섯을 썬다","팬에 버섯을 볶는다","계란을 풀어 넣는다","밥을 넣고 볶는다","간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','veggie','rice']),

('chinese-083', 'seed',
 '{"ko":"오향장육","en":"Five Spice Pork","ja":"五香醤肉","zh":"五香酱肉"}',
 '{"ko":"오향 향신료로 양념한 돼지고기 요리","en":"Pork seasoned with five-spice powder"}',
 90, 'medium', 4,
 '[{"name":"삼겹살","quantity":"600g"},{"name":"오향분","quantity":"2큰술"},{"name":"간장","quantity":"1/2컵"},{"name":"설탕","quantity":"3큰술"},{"name":"대파","quantity":"2대"},{"name":"생강","quantity":"1톨"}]',
 '{"ko":["삼겹살을 큼직하게 자른다","냄비에 삼겹살과 양념을 넣는다","물을 붓고 끓인다","약불에서 1시간 조린다","썰어서 낸다"]}',
 ARRAY['mild','meat','heavy']),

('chinese-084', 'seed',
 '{"ko":"회과육","en":"Twice Cooked Pork","ja":"回鍋肉","zh":"回锅肉"}',
 '{"ko":"삶은 돼지고기를 야채와 함께 볶은 사천 요리","en":"Sichuan-style twice-cooked pork with vegetables"}',
 40, 'medium', 3,
 '[{"name":"삼겹살","quantity":"400g"},{"name":"양배추","quantity":"1/4통"},{"name":"피망","quantity":"2개"},{"name":"두반장","quantity":"2큰술"},{"name":"간장","quantity":"2큰술"},{"name":"설탕","quantity":"1큰술"}]',
 '{"ko":["삼겹살을 삶아 얇게 썬다","야채를 썬다","팬에 삼겹살을 볶는다","두반장을 넣고 볶는다","야채를 넣고 간장, 설탕으로 간을 한다"]}',
 ARRAY['spicy','stir_fry','meat','heavy']),

('chinese-085', 'seed',
 '{"ko":"쇠고기볶음","en":"Stir-fried Beef","ja":"牛肉炒め","zh":"炒牛肉"}',
 '{"ko":"소고기와 야채를 볶은 요리","en":"Stir-fried beef with vegetables"}',
 20, 'easy', 2,
 '[{"name":"소고기","quantity":"300g"},{"name":"양파","quantity":"1개"},{"name":"파프리카","quantity":"1개"},{"name":"굴소스","quantity":"2큰술"},{"name":"간장","quantity":"1큰술"}]',
 '{"ko":["소고기를 얇게 썬다","야채를 썬다","팬에 소고기를 볶는다","야채를 넣고 볶는다","굴소스와 간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','meat','quick']),

('chinese-086', 'seed',
 '{"ko":"새송이버섯볶음","en":"Stir-fried King Oyster Mushroom","ja":"エリンギ炒め","zh":"炒杏鲍菇"}',
 '{"ko":"새송이버섯을 고기처럼 볶은 요리","en":"King oyster mushrooms stir-fried like meat"}',
 15, 'easy', 2,
 '[{"name":"새송이버섯","quantity":"3개"},{"name":"마늘","quantity":"5쪽"},{"name":"대파","quantity":"1대"},{"name":"굴소스","quantity":"2큰술"},{"name":"버터","quantity":"20g"}]',
 '{"ko":["새송이버섯을 어슷썬다","팬에 버터와 마늘을 볶는다","버섯을 넣고 볶는다","굴소스로 간을 한다","대파를 올린다"]}',
 ARRAY['mild','stir_fry','veggie','quick']),

('chinese-087', 'seed',
 '{"ko":"고기완자조림","en":"Braised Meatballs","ja":"肉団子の煮込み","zh":"红烧狮子头"}',
 '{"ko":"큼직한 고기완자를 조린 요리","en":"Large meatballs braised in sauce"}',
 45, 'medium', 4,
 '[{"name":"돼지고기","quantity":"500g"},{"name":"배추","quantity":"1/2포기"},{"name":"계란","quantity":"1개"},{"name":"전분","quantity":"3큰술"},{"name":"간장","quantity":"4큰술"},{"name":"설탕","quantity":"2큰술"}]',
 '{"ko":["돼지고기를 다져 계란, 전분을 섞어 큰 완자를 빚는다","팬에 완자를 튀긴다","냄비에 배추를 깔고 완자를 올린다","간장, 설탕, 물을 부어 30분 조린다"]}',
 ARRAY['mild','meat','heavy']),

('chinese-088', 'seed',
 '{"ko":"닭날개조림","en":"Braised Chicken Wings","ja":"手羽先の煮込み","zh":"红烧鸡翅"}',
 '{"ko":"닭날개를 간장에 조린 요리","en":"Chicken wings braised in soy sauce"}',
 35, 'easy', 3,
 '[{"name":"닭날개","quantity":"12개"},{"name":"간장","quantity":"1/2컵"},{"name":"설탕","quantity":"3큰술"},{"name":"대파","quantity":"2대"},{"name":"생강","quantity":"1톨"},{"name":"청주","quantity":"2큰술"}]',
 '{"ko":["닭날개를 씻는다","팬에 닭날개를 볶는다","간장, 설탕, 청주를 넣는다","대파, 생강을 넣고 물을 붓는다","약불에서 25분 조린다"]}',
 ARRAY['mild','meat','heavy']),

('chinese-089', 'seed',
 '{"ko":"양파돼지고기볶음","en":"Pork with Onions","ja":"玉ねぎ豚肉炒め","zh":"洋葱炒肉"}',
 '{"ko":"양파와 돼지고기를 볶은 간단한 요리","en":"Simple stir-fried pork with onions"}',
 15, 'easy', 2,
 '[{"name":"돼지고기","quantity":"250g"},{"name":"양파","quantity":"2개"},{"name":"간장","quantity":"2큰술"},{"name":"굴소스","quantity":"1큰술"},{"name":"설탕","quantity":"1작은술"}]',
 '{"ko":["돼지고기를 썬다","양파를 썬다","팬에 돼지고기를 볶는다","양파를 넣고 볶는다","간장, 굴소스, 설탕으로 간을 한다"]}',
 ARRAY['mild','stir_fry','meat','quick']),

('chinese-090', 'seed',
 '{"ko":"피망고기볶음","en":"Pork with Bell Peppers","ja":"ピーマン肉炒め","zh":"青椒肉丝"}',
 '{"ko":"피망과 고기를 채썰어 볶은 요리","en":"Shredded pork stir-fried with bell peppers"}',
 20, 'easy', 2,
 '[{"name":"돼지고기","quantity":"200g"},{"name":"피망","quantity":"3개"},{"name":"간장","quantity":"2큰술"},{"name":"전분","quantity":"1큰술"},{"name":"마늘","quantity":"3쪽"}]',
 '{"ko":["돼지고기와 피망을 채썬다","돼지고기에 전분을 묻힌다","팬에 마늘을 볶는다","돼지고기를 볶는다","피망을 넣고 간장으로 간을 한다"]}',
 ARRAY['mild','stir_fry','meat','quick']),

-- === 추가 해물/면 요리 ===
('chinese-091', 'seed',
 '{"ko":"해물짬뽕밥","en":"Seafood Jjamppong Rice","ja":"海鮮チャンポンご飯","zh":"海鲜炒饭"}',
 '{"ko":"얼큰한 해물을 밥에 곁들인 요리","en":"Spicy seafood served over rice"}',
 25, 'medium', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"새우","quantity":"5마리"},{"name":"오징어","quantity":"100g"},{"name":"홍합","quantity":"5개"},{"name":"양배추","quantity":"2잎"},{"name":"고춧가루","quantity":"2큰술"}]',
 '{"ko":["해물을 손질한다","팬에 고춧가루를 볶는다","해물을 넣고 볶는다","양배추를 넣고 물을 붓는다","밥 위에 얹어 낸다"]}',
 ARRAY['spicy','stir_fry','seafood','rice']),

('chinese-092', 'seed',
 '{"ko":"쟁반짜장","en":"Jajang on a Platter","ja":"皿盛りジャージャー麺","zh":"炸酱拌面"}',
 '{"ko":"면과 춘장 소스를 따로 담아내는 짜장면","en":"Jajangmyeon served with sauce on the side"}',
 30, 'medium', 4,
 '[{"name":"중화면","quantity":"4인분"},{"name":"춘장","quantity":"5큰술"},{"name":"돼지고기","quantity":"200g"},{"name":"양파","quantity":"2개"},{"name":"오이","quantity":"1개"},{"name":"계란","quantity":"2개"}]',
 '{"ko":["야채를 다진다","팬에 춘장 소스를 만든다","계란을 부쳐 채썬다","오이를 채썬다","쟁반에 면, 소스, 고명을 예쁘게 담는다"]}',
 ARRAY['mild','stir_fry','meat','noodle']),

('chinese-093', 'seed',
 '{"ko":"냉짬뽕","en":"Cold Jjamppong","ja":"冷やしチャンポン","zh":"冷面海鲜汤"}',
 '{"ko":"차갑게 식힌 얼큰한 해물 국수","en":"Chilled spicy seafood noodle soup"}',
 30, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"새우","quantity":"5마리"},{"name":"오징어","quantity":"100g"},{"name":"양배추","quantity":"2잎"},{"name":"오이","quantity":"1개"},{"name":"고춧가루","quantity":"2큰술"}]',
 '{"ko":["해물을 익혀 식힌다","국물을 만들어 차게 식힌다","면을 삶아 찬물에 헹군다","오이를 채썬다","차가운 국물에 면과 해물을 담는다"]}',
 ARRAY['spicy','soupy','seafood','noodle']),

('chinese-094', 'seed',
 '{"ko":"유산슬","en":"Yusanseul","ja":"ユサンスル","zh":"烩什锦"}',
 '{"ko":"해물과 야채를 걸쭉한 소스에 볶은 요리","en":"Seafood and vegetables in thick sauce"}',
 30, 'medium', 3,
 '[{"name":"새우","quantity":"100g"},{"name":"오징어","quantity":"100g"},{"name":"돼지고기","quantity":"100g"},{"name":"목이버섯","quantity":"50g"},{"name":"죽순","quantity":"100g"},{"name":"전분물","quantity":"5큰술"}]',
 '{"ko":["모든 재료를 손질한다","팬에 고기를 볶는다","해물과 야채를 넣고 볶는다","물을 붓고 끓인다","전분물로 걸쭉하게 만든다"]}',
 ARRAY['mild','stir_fry','seafood','heavy']),

('chinese-095', 'seed',
 '{"ko":"잡채밥","en":"Japchae Rice","ja":"雑菜ご飯","zh":"炒粉饭"}',
 '{"ko":"중국식 잡채를 밥 위에 얹은 요리","en":"Chinese-style japchae served over rice"}',
 25, 'easy', 2,
 '[{"name":"밥","quantity":"2공기"},{"name":"당면","quantity":"100g"},{"name":"돼지고기","quantity":"100g"},{"name":"배추","quantity":"3잎"},{"name":"당근","quantity":"1개"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["당면을 불린다","야채와 고기를 볶는다","당면을 넣고 간장으로 간을 한다","밥 위에 얹어 낸다"]}',
 ARRAY['mild','stir_fry','meat','rice','noodle']),

('chinese-096', 'seed',
 '{"ko":"새우완탕면","en":"Shrimp Wonton Noodles","ja":"海老ワンタン麺","zh":"虾仁馄饨面"}',
 '{"ko":"새우 완탕과 면이 들어간 국물 요리","en":"Noodle soup with shrimp wontons"}',
 30, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"새우완탕","quantity":"10개"},{"name":"육수","quantity":"4컵"},{"name":"청경채","quantity":"2포기"},{"name":"대파","quantity":"1대"}]',
 '{"ko":["육수를 끓인다","완탕을 삶는다","면을 삶는다","그릇에 면과 완탕을 담는다","육수를 붓고 청경채를 올린다"]}',
 ARRAY['mild','soupy','seafood','noodle','dim_sum']),

('chinese-097', 'seed',
 '{"ko":"고기완탕면","en":"Pork Wonton Noodles","ja":"肉ワンタン麺","zh":"鲜肉馄饨面"}',
 '{"ko":"돼지고기 완탕과 면이 들어간 국물 요리","en":"Noodle soup with pork wontons"}',
 30, 'medium', 2,
 '[{"name":"중화면","quantity":"2인분"},{"name":"돼지고기완탕","quantity":"10개"},{"name":"육수","quantity":"4컵"},{"name":"대파","quantity":"2대"},{"name":"간장","quantity":"2큰술"}]',
 '{"ko":["육수를 끓인다","완탕을 삶는다","면을 삶는다","그릇에 담고 육수를 붓는다","대파와 간장을 올린다"]}',
 ARRAY['mild','soupy','meat','noodle','dim_sum']),

('chinese-098', 'seed',
 '{"ko":"칠리크랩","en":"Chili Crab","ja":"チリクラブ","zh":"辣椒螃蟹"}',
 '{"ko":"매콤달콤한 칠리소스에 볶은 게 요리","en":"Crab stir-fried in sweet and spicy chili sauce"}',
 35, 'medium', 3,
 '[{"name":"게","quantity":"2마리"},{"name":"케첩","quantity":"5큰술"},{"name":"칠리소스","quantity":"3큰술"},{"name":"마늘","quantity":"10쪽"},{"name":"생강","quantity":"1톨"},{"name":"계란","quantity":"1개"}]',
 '{"ko":["게를 손질해 토막낸다","팬에 마늘과 생강을 볶는다","게를 넣고 볶는다","케첩과 칠리소스를 넣는다","계란을 풀어 넣어 소스를 걸쭉하게 만든다"]}',
 ARRAY['spicy','stir_fry','seafood','heavy']),

('chinese-099', 'seed',
 '{"ko":"새우구이","en":"Grilled Shrimp","ja":"海老の炭火焼き","zh":"烤虾"}',
 '{"ko":"소금구이로 만든 새우 요리","en":"Salt-grilled shrimp"}',
 15, 'easy', 2,
 '[{"name":"새우","quantity":"300g"},{"name":"소금","quantity":"2큰술"},{"name":"마늘","quantity":"5쪽"},{"name":"레몬","quantity":"1개"}]',
 '{"ko":["새우를 손질한다","소금과 마늘을 섞는다","새우에 소금을 뿌려 굽는다","레몬을 곁들여 낸다"]}',
 ARRAY['mild','grilled','seafood','quick']),

('chinese-100', 'seed',
 '{"ko":"중국식 동태전","en":"Chinese Pollack Pancake","ja":"中華スケトウダラのチヂミ","zh":"煎明太鱼"}',
 '{"ko":"동태를 부쳐낸 중국식 전","en":"Chinese-style pan-fried pollack"}',
 25, 'easy', 2,
 '[{"name":"동태","quantity":"2마리"},{"name":"밀가루","quantity":"1컵"},{"name":"계란","quantity":"2개"},{"name":"대파","quantity":"2대"},{"name":"간장","quantity":"3큰술"},{"name":"식초","quantity":"2큰술"}]',
 '{"ko":["동태를 손질해 포를 뜬다","밀가루와 계란을 섞어 옷을 입힌다","팬에 부친다","간장, 식초, 대파로 소스를 만든다","소스에 찍어 먹는다"]}',
 ARRAY['mild','seafood','side_dish']);
